// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type countDebugletKey struct {
	_    structs.HostLayout
	Uuid [16]uint8
	Ipv6 [16]uint8
}

type countDebugletUuid struct {
	_    structs.HostLayout
	Uuid [16]uint8
}

type countExecKey struct {
	_    structs.HostLayout
	Uuid [16]uint8
}

type countTbState struct {
	_      structs.HostLayout
	Tokens uint64
	T_last uint64
	Lock   struct {
		_   structs.HostLayout
		Val uint32
	}
	_ [4]byte
}

// loadCount returns the embedded CollectionSpec for count.
func loadCount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load count: %w", err)
	}

	return spec, err
}

// loadCountObjects loads count and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*countObjects
//	*countPrograms
//	*countMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// countSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type countSpecs struct {
	countProgramSpecs
	countMapSpecs
	countVariableSpecs
}

// countProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type countProgramSpecs struct {
	HandleEgress  *ebpf.ProgramSpec `ebpf:"handle_egress"`
	HandleIngress *ebpf.ProgramSpec `ebpf:"handle_ingress"`
}

// countMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type countMapSpecs struct {
	DebugletSkMap     *ebpf.MapSpec `ebpf:"debuglet_sk_map"`
	ExecPacketSizeMap *ebpf.MapSpec `ebpf:"exec_packet_size_map"`
	ExecRatesMap      *ebpf.MapSpec `ebpf:"exec_rates_map"`
	PacketSizeMap     *ebpf.MapSpec `ebpf:"packet_size_map"`
	RatesMap          *ebpf.MapSpec `ebpf:"rates_map"`
}

// countVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type countVariableSpecs struct {
}

// countObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type countObjects struct {
	countPrograms
	countMaps
	countVariables
}

func (o *countObjects) Close() error {
	return _CountClose(
		&o.countPrograms,
		&o.countMaps,
	)
}

// countMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type countMaps struct {
	DebugletSkMap     *ebpf.Map `ebpf:"debuglet_sk_map"`
	ExecPacketSizeMap *ebpf.Map `ebpf:"exec_packet_size_map"`
	ExecRatesMap      *ebpf.Map `ebpf:"exec_rates_map"`
	PacketSizeMap     *ebpf.Map `ebpf:"packet_size_map"`
	RatesMap          *ebpf.Map `ebpf:"rates_map"`
}

func (m *countMaps) Close() error {
	return _CountClose(
		m.DebugletSkMap,
		m.ExecPacketSizeMap,
		m.ExecRatesMap,
		m.PacketSizeMap,
		m.RatesMap,
	)
}

// countVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type countVariables struct {
}

// countPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type countPrograms struct {
	HandleEgress  *ebpf.Program `ebpf:"handle_egress"`
	HandleIngress *ebpf.Program `ebpf:"handle_ingress"`
}

func (p *countPrograms) Close() error {
	return _CountClose(
		p.HandleEgress,
		p.HandleIngress,
	)
}

func _CountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed count_bpfeb.o
var _CountBytes []byte
