// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Debuglet struct {
	ID                    int64
	Uuid                  uuid.UUID
	StartTime             UTCTime
	Args                  CommaSeparatedList
	Wasm                  []byte
	TransactionID         string
	FloorBw               int64
	CeilBw                int64
	TimeoutMs             int64
	Addresses             CommaSeparatedList
	RequireIcmp           bool
	ListenUdp             bool
	ListenTcp             bool
	ListenScion           bool
	StartedAt             UTCTime
	DispatcherIncarnation string
	SessionID             string
}

type DebugletExit struct {
	DebugletID            string
	DispatcherIncarnation string
	SessionID             string
	ExitCode              int64
	ErrorMessage          sql.NullString
	RecordedAt            UTCTime
	Attempts              int64
	LastAttemptAt         UTCTime
	LastError             string
	Rejected              bool
}

type DebugletLog struct {
	ID         int64
	DebugletID int64
	Timestamp  time.Time
	Output     []byte
}

type OutputFrame struct {
	RunID       string
	Sequence    int64
	TimestampNs int64
	Output      []byte
}

type OutputRun struct {
	RunID                 string
	DispatcherIncarnation string
	SessionID             string
	OutputVersion         int64
	LastSequence          int64
	AcknowledgedSequence  int64
	EmittedBytes          int64
	QueuedBytes           int64
	QueuedFrames          int64
	Status                string
	Reason                string
	EndAcknowledged       bool
	ReceiptSequence       sql.NullInt64
	ReceiptReason         string
}

type OutputUsage struct {
	Singleton    int64
	ChargedBytes int64
}

type TeslaChain struct {
	Generation      int64
	Anchor          []byte
	EpochBase       time.Time
	DelayNs         int64
	ChainLength     int64
	CreatedAt       time.Time
	DisclosureDelay sql.NullInt64
}
