// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Debuglet struct {
	ID            string
	StartTime     UTCTime
	Args          CommaSeparatedList
	Wasm          []byte
	TransactionID string
	FloorBw       int64
	CeilBw        int64
	TimeoutMs     int64
	Addresses     CommaSeparatedList
	RequireIcmp   bool
	ListenUdp     bool
	ListenTcp     bool
	ListenIcmp    bool
	ListenScion   bool
	StartedAt     UTCTime
}

type DebugletLog struct {
	ID         int64
	DebugletID string
	Timestamp  time.Time
	Output     []byte
}
