// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: output.sql

package database

import (
	"context"
	"database/sql"
)

const abandonOutputRun = `-- name: AbandonOutputRun :exec
UPDATE output_runs SET queued_bytes = 0, queued_frames = 0, end_acknowledged = TRUE
WHERE run_id = ? AND NOT end_acknowledged
`

func (q *Queries) AbandonOutputRun(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, abandonOutputRun, runID)
	return err
}

const acceptOutputTruncation = `-- name: AcceptOutputTruncation :exec
UPDATE output_runs SET receipt_sequence = ?1, receipt_reason = ?2,
    acknowledged_sequence = ?1, queued_bytes = 0, queued_frames = 0,
    end_acknowledged = TRUE WHERE run_id = ?3
`

type AcceptOutputTruncationParams struct {
	Sequence sql.NullInt64
	Reason   string
	RunID    string
}

func (q *Queries) AcceptOutputTruncation(ctx context.Context, arg AcceptOutputTruncationParams) error {
	_, err := q.db.ExecContext(ctx, acceptOutputTruncation, arg.Sequence, arg.Reason, arg.RunID)
	return err
}

const acknowledgeOutputRun = `-- name: AcknowledgeOutputRun :exec
UPDATE output_runs SET acknowledged_sequence = ?1,
    queued_bytes = queued_bytes - ?2, queued_frames = queued_frames - ?3,
    end_acknowledged = ?4 WHERE run_id = ?5
`

type AcknowledgeOutputRunParams struct {
	AcknowledgedSequence int64
	Bytes                int64
	Frames               int64
	EndAcknowledged      bool
	RunID                string
}

func (q *Queries) AcknowledgeOutputRun(ctx context.Context, arg AcknowledgeOutputRunParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeOutputRun,
		arg.AcknowledgedSequence,
		arg.Bytes,
		arg.Frames,
		arg.EndAcknowledged,
		arg.RunID,
	)
	return err
}

const addOutputUsage = `-- name: AddOutputUsage :exec
UPDATE output_usage SET charged_bytes = charged_bytes + ? WHERE singleton = 1
`

func (q *Queries) AddOutputUsage(ctx context.Context, chargedBytes int64) error {
	_, err := q.db.ExecContext(ctx, addOutputUsage, chargedBytes)
	return err
}

const advanceOutputRun = `-- name: AdvanceOutputRun :exec
UPDATE output_runs SET last_sequence = last_sequence + 1,
    emitted_bytes = emitted_bytes + ?1, queued_bytes = queued_bytes + ?1,
    queued_frames = queued_frames + 1 WHERE run_id = ?2
`

type AdvanceOutputRunParams struct {
	Bytes int64
	RunID string
}

func (q *Queries) AdvanceOutputRun(ctx context.Context, arg AdvanceOutputRunParams) error {
	_, err := q.db.ExecContext(ctx, advanceOutputRun, arg.Bytes, arg.RunID)
	return err
}

const countOutputRuns = `-- name: CountOutputRuns :one
SELECT COUNT(*) FROM output_runs WHERE NOT end_acknowledged
`

// A run whose end the dispatcher acknowledged holds no further spool capacity.
func (q *Queries) CountOutputRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutputRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutputFrame = `-- name: CreateOutputFrame :exec
INSERT INTO output_frames (run_id, sequence, timestamp_ns, output) VALUES (?, ?, ?, ?)
`

type CreateOutputFrameParams struct {
	RunID       string
	Sequence    int64
	TimestampNs int64
	Output      []byte
}

func (q *Queries) CreateOutputFrame(ctx context.Context, arg CreateOutputFrameParams) error {
	_, err := q.db.ExecContext(ctx, createOutputFrame,
		arg.RunID,
		arg.Sequence,
		arg.TimestampNs,
		arg.Output,
	)
	return err
}

const createOutputRun = `-- name: CreateOutputRun :exec
INSERT INTO output_runs (run_id, dispatcher_incarnation, session_id, output_version)
VALUES (?, ?, ?, ?)
`

type CreateOutputRunParams struct {
	RunID                 string
	DispatcherIncarnation string
	SessionID             string
	OutputVersion         int64
}

func (q *Queries) CreateOutputRun(ctx context.Context, arg CreateOutputRunParams) error {
	_, err := q.db.ExecContext(ctx, createOutputRun,
		arg.RunID,
		arg.DispatcherIncarnation,
		arg.SessionID,
		arg.OutputVersion,
	)
	return err
}

const deleteAcknowledgedOutput = `-- name: DeleteAcknowledgedOutput :exec
DELETE FROM output_frames WHERE run_id = ? AND sequence <= ?
`

type DeleteAcknowledgedOutputParams struct {
	RunID    string
	Sequence int64
}

func (q *Queries) DeleteAcknowledgedOutput(ctx context.Context, arg DeleteAcknowledgedOutputParams) error {
	_, err := q.db.ExecContext(ctx, deleteAcknowledgedOutput, arg.RunID, arg.Sequence)
	return err
}

const finishOutputRun = `-- name: FinishOutputRun :exec
UPDATE output_runs SET status = ?, reason = ? WHERE run_id = ? AND status = 'open'
`

type FinishOutputRunParams struct {
	Status string
	Reason string
	RunID  string
}

func (q *Queries) FinishOutputRun(ctx context.Context, arg FinishOutputRunParams) error {
	_, err := q.db.ExecContext(ctx, finishOutputRun, arg.Status, arg.Reason, arg.RunID)
	return err
}

const getOutputRun = `-- name: GetOutputRun :one
SELECT run_id, dispatcher_incarnation, session_id, output_version, last_sequence, acknowledged_sequence, emitted_bytes, queued_bytes, queued_frames, status, reason, end_acknowledged, receipt_sequence, receipt_reason FROM output_runs WHERE run_id = ?1
`

func (q *Queries) GetOutputRun(ctx context.Context, runID string) (OutputRun, error) {
	row := q.db.QueryRowContext(ctx, getOutputRun, runID)
	var i OutputRun
	err := row.Scan(
		&i.RunID,
		&i.DispatcherIncarnation,
		&i.SessionID,
		&i.OutputVersion,
		&i.LastSequence,
		&i.AcknowledgedSequence,
		&i.EmittedBytes,
		&i.QueuedBytes,
		&i.QueuedFrames,
		&i.Status,
		&i.Reason,
		&i.EndAcknowledged,
		&i.ReceiptSequence,
		&i.ReceiptReason,
	)
	return i, err
}

const getOutputUsage = `-- name: GetOutputUsage :one
SELECT charged_bytes FROM output_usage WHERE singleton = 1
`

func (q *Queries) GetOutputUsage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOutputUsage)
	var charged_bytes int64
	err := row.Scan(&charged_bytes)
	return charged_bytes, err
}

const interruptOpenOutputRuns = `-- name: InterruptOpenOutputRuns :exec
UPDATE output_runs SET status = 'truncated', reason = 'executor_interrupted' WHERE status = 'open'
`

func (q *Queries) InterruptOpenOutputRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, interruptOpenOutputRuns)
	return err
}

const listOutputFrames = `-- name: ListOutputFrames :many
SELECT run_id, sequence, timestamp_ns, output FROM output_frames WHERE run_id = ? AND sequence > ? ORDER BY sequence LIMIT ?
`

type ListOutputFramesParams struct {
	RunID    string
	Sequence int64
	Limit    int64
}

func (q *Queries) ListOutputFrames(ctx context.Context, arg ListOutputFramesParams) ([]OutputFrame, error) {
	rows, err := q.db.QueryContext(ctx, listOutputFrames, arg.RunID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutputFrame
	for rows.Next() {
		var i OutputFrame
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.TimestampNs,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutputRuns = `-- name: ListPendingOutputRuns :many
SELECT run_id, dispatcher_incarnation, session_id, output_version, last_sequence, acknowledged_sequence, emitted_bytes, queued_bytes, queued_frames, status, reason, end_acknowledged, receipt_sequence, receipt_reason FROM output_runs WHERE NOT end_acknowledged AND run_id > ? ORDER BY run_id LIMIT ?
`

type ListPendingOutputRunsParams struct {
	RunID string
	Limit int64
}

func (q *Queries) ListPendingOutputRuns(ctx context.Context, arg ListPendingOutputRunsParams) ([]OutputRun, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutputRuns, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutputRun
	for rows.Next() {
		var i OutputRun
		if err := rows.Scan(
			&i.RunID,
			&i.DispatcherIncarnation,
			&i.SessionID,
			&i.OutputVersion,
			&i.LastSequence,
			&i.AcknowledgedSequence,
			&i.EmittedBytes,
			&i.QueuedBytes,
			&i.QueuedFrames,
			&i.Status,
			&i.Reason,
			&i.EndAcknowledged,
			&i.ReceiptSequence,
			&i.ReceiptReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAcknowledgedOutput = `-- name: SumAcknowledgedOutput :one
SELECT CAST(COALESCE(SUM(length(output)), 0) AS INTEGER) AS byte_count, COUNT(*) AS frame_count
FROM output_frames WHERE run_id = ? AND sequence <= ?
`

type SumAcknowledgedOutputParams struct {
	RunID    string
	Sequence int64
}

type SumAcknowledgedOutputRow struct {
	ByteCount  int64
	FrameCount int64
}

func (q *Queries) SumAcknowledgedOutput(ctx context.Context, arg SumAcknowledgedOutputParams) (SumAcknowledgedOutputRow, error) {
	row := q.db.QueryRowContext(ctx, sumAcknowledgedOutput, arg.RunID, arg.Sequence)
	var i SumAcknowledgedOutputRow
	err := row.Scan(&i.ByteCount, &i.FrameCount)
	return i, err
}
