// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package database

import (
	"context"
	"database/sql"
)

const countDebugletExits = `-- name: CountDebugletExits :one
SELECT count(*) FROM debuglet_exits
`

func (q *Queries) CountDebugletExits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDebugletExits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDebugletExit = `-- name: GetDebugletExit :one
SELECT debuglet_id, dispatcher_incarnation, session_id, exit_code, error_message, recorded_at, attempts, last_attempt_at, last_error, rejected FROM debuglet_exits
WHERE debuglet_id = ?
`

func (q *Queries) GetDebugletExit(ctx context.Context, debugletID string) (DebugletExit, error) {
	row := q.db.QueryRowContext(ctx, getDebugletExit, debugletID)
	var i DebugletExit
	err := row.Scan(
		&i.DebugletID,
		&i.DispatcherIncarnation,
		&i.SessionID,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.RecordedAt,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.LastError,
		&i.Rejected,
	)
	return i, err
}

const listDebugletExits = `-- name: ListDebugletExits :many
SELECT debuglet_id, dispatcher_incarnation, session_id, exit_code, error_message, recorded_at, attempts, last_attempt_at, last_error, rejected FROM debuglet_exits
ORDER BY recorded_at, debuglet_id
LIMIT ?
`

func (q *Queries) ListDebugletExits(ctx context.Context, limit int64) ([]DebugletExit, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletExits, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletExit
	for rows.Next() {
		var i DebugletExit
		if err := rows.Scan(
			&i.DebugletID,
			&i.DispatcherIncarnation,
			&i.SessionID,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.RecordedAt,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.LastError,
			&i.Rejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebugletExitsForBinding = `-- name: ListDebugletExitsForBinding :many
SELECT debuglet_id, dispatcher_incarnation, session_id, exit_code, error_message, recorded_at, attempts, last_attempt_at, last_error, rejected FROM debuglet_exits
WHERE dispatcher_incarnation = ?1
  AND session_id = ?2
  AND dispatcher_incarnation <> '' AND session_id <> ''
  AND rejected = FALSE
ORDER BY recorded_at, debuglet_id
LIMIT ?3
`

type ListDebugletExitsForBindingParams struct {
	DispatcherIncarnation string
	SessionID             string
	Limit                 int64
}

// Only a session's own deliverable results, so results no session can deliver
// cannot crowd out the ones that can be.
func (q *Queries) ListDebugletExitsForBinding(ctx context.Context, arg ListDebugletExitsForBindingParams) ([]DebugletExit, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletExitsForBinding, arg.DispatcherIncarnation, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletExit
	for rows.Next() {
		var i DebugletExit
		if err := rows.Scan(
			&i.DebugletID,
			&i.DispatcherIncarnation,
			&i.SessionID,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.RecordedAt,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.LastError,
			&i.Rejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteDebugletExitFailure = `-- name: NoteDebugletExitFailure :execrows
UPDATE debuglet_exits
SET attempts = attempts + ?1,
    last_attempt_at = ?2,
    last_error = ?3,
    rejected = ?4
WHERE debuglet_id = ?5
  AND dispatcher_incarnation = ?6
  AND session_id = ?7
  AND dispatcher_incarnation <> '' AND session_id <> ''
`

type NoteDebugletExitFailureParams struct {
	Attempts              int64
	LastAttemptAt         UTCTime
	LastError             string
	Rejected              bool
	DebugletID            string
	DispatcherIncarnation string
	SessionID             string
}

func (q *Queries) NoteDebugletExitFailure(ctx context.Context, arg NoteDebugletExitFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, noteDebugletExitFailure,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.LastError,
		arg.Rejected,
		arg.DebugletID,
		arg.DispatcherIncarnation,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordDebugletExit = `-- name: RecordDebugletExit :exec
INSERT INTO debuglet_exits (
    debuglet_id,
    dispatcher_incarnation,
    session_id,
    exit_code,
    error_message,
    recorded_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (debuglet_id) DO NOTHING
`

type RecordDebugletExitParams struct {
	DebugletID            string
	DispatcherIncarnation string
	SessionID             string
	ExitCode              int64
	ErrorMessage          sql.NullString
	RecordedAt            UTCTime
}

// The first write wins: a duplicate report never rewrites the chosen result.
func (q *Queries) RecordDebugletExit(ctx context.Context, arg RecordDebugletExitParams) error {
	_, err := q.db.ExecContext(ctx, recordDebugletExit,
		arg.DebugletID,
		arg.DispatcherIncarnation,
		arg.SessionID,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.RecordedAt,
	)
	return err
}

const releaseDebugletExit = `-- name: ReleaseDebugletExit :execrows
DELETE FROM debuglet_exits
WHERE debuglet_id = ?1
  AND dispatcher_incarnation = ?2
  AND session_id = ?3
  AND dispatcher_incarnation <> '' AND session_id <> ''
`

type ReleaseDebugletExitParams struct {
	DebugletID            string
	DispatcherIncarnation string
	SessionID             string
}

func (q *Queries) ReleaseDebugletExit(ctx context.Context, arg ReleaseDebugletExitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseDebugletExit, arg.DebugletID, arg.DispatcherIncarnation, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
