// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDebuglet = `-- name: CreateDebuglet :exec
INSERT INTO debuglets (
    uuid,
    start_time,
    args,
    wasm,
    transaction_id,
    floor_bw,
    ceil_bw,
    timeout_ms,
    addresses,
    require_icmp,
    listen_udp,
    listen_tcp,
    listen_icmp,
    listen_scion
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDebugletParams struct {
	Uuid          uuid.UUID
	StartTime     UTCTime
	Args          CommaSeparatedList
	Wasm          []byte
	TransactionID string
	FloorBw       int64
	CeilBw        int64
	TimeoutMs     int64
	Addresses     CommaSeparatedList
	RequireIcmp   bool
	ListenUdp     bool
	ListenTcp     bool
	ListenIcmp    bool
	ListenScion   bool
}

func (q *Queries) CreateDebuglet(ctx context.Context, arg CreateDebugletParams) error {
	_, err := q.db.ExecContext(ctx, createDebuglet,
		arg.Uuid,
		arg.StartTime,
		arg.Args,
		arg.Wasm,
		arg.TransactionID,
		arg.FloorBw,
		arg.CeilBw,
		arg.TimeoutMs,
		arg.Addresses,
		arg.RequireIcmp,
		arg.ListenUdp,
		arg.ListenTcp,
		arg.ListenIcmp,
		arg.ListenScion,
	)
	return err
}

const deleteDebuglet = `-- name: DeleteDebuglet :exec
DELETE FROM debuglets
WHERE uuid = ?
`

func (q *Queries) DeleteDebuglet(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDebuglet, argUuid)
	return err
}

const getDebugletStarted = `-- name: GetDebugletStarted :one
SELECT started_at FROM debuglets
WHERE uuid = ?
`

func (q *Queries) GetDebugletStarted(ctx context.Context, argUuid uuid.UUID) (UTCTime, error) {
	row := q.db.QueryRowContext(ctx, getDebugletStarted, argUuid)
	var started_at UTCTime
	err := row.Scan(&started_at)
	return started_at, err
}

const listDebuglets = `-- name: ListDebuglets :many
SELECT id, uuid, start_time, args, wasm, transaction_id, floor_bw, ceil_bw, timeout_ms, addresses, require_icmp, listen_udp, listen_tcp, listen_icmp, listen_scion, started_at FROM debuglets
LIMIT ?
OFFSET ?
`

type ListDebugletsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDebuglets(ctx context.Context, arg ListDebugletsParams) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebuglets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.StartTime,
			&i.Args,
			&i.Wasm,
			&i.TransactionID,
			&i.FloorBw,
			&i.CeilBw,
			&i.TimeoutMs,
			&i.Addresses,
			&i.RequireIcmp,
			&i.ListenUdp,
			&i.ListenTcp,
			&i.ListenIcmp,
			&i.ListenScion,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebugletStarted = `-- name: UpdateDebugletStarted :one
UPDATE debuglets
SET started_at = ?
WHERE uuid = ?
RETURNING id, uuid, start_time, args, wasm, transaction_id, floor_bw, ceil_bw, timeout_ms, addresses, require_icmp, listen_udp, listen_tcp, listen_icmp, listen_scion, started_at
`

type UpdateDebugletStartedParams struct {
	StartedAt UTCTime
	Uuid      uuid.UUID
}

func (q *Queries) UpdateDebugletStarted(ctx context.Context, arg UpdateDebugletStartedParams) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, updateDebugletStarted, arg.StartedAt, arg.Uuid)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.StartTime,
		&i.Args,
		&i.Wasm,
		&i.TransactionID,
		&i.FloorBw,
		&i.CeilBw,
		&i.TimeoutMs,
		&i.Addresses,
		&i.RequireIcmp,
		&i.ListenUdp,
		&i.ListenTcp,
		&i.ListenIcmp,
		&i.ListenScion,
		&i.StartedAt,
	)
	return i, err
}
