// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ddb

import (
	"debuglet/internal/dispatcher/models"
)

type Debuglet struct {
	ID         string
	StartTime  models.UTCTime
	EndTime    models.UTCTime
	Usage      int64
	ExecutorID string
	Addresses  models.CommaSeparatedList
	State      models.DebugletRunState
}

type DebugletLog struct {
	ID         int64
	DebugletID string
	Timestamp  models.UTCTime
	Output     []byte
}

type DebugletOrder struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
}

type Earning struct {
	ExecutorID     string
	Currency       string
	TotalIncome    int64
	CurrentBalance int64
}

type Transaction struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt models.UTCTime
	Hash      string
	Currency  string
	Status    int64
}

type TransactionState struct {
	Key   string
	Value string
}
