// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ddb

import (
	"database/sql"
	"time"
)

type Debuglet struct {
	ID         string
	StartTime  time.Time
	EndTime    time.Time
	Usage      int64
	ExecutorID string
	Addresses  sql.NullString
}

type Transaction struct {
	TransactionID string
	AuthKey       string
	Price         int64
	Method        string
	ExpiresAt     time.Time
	Paid          bool
	Hash          string
}

type TransactionState struct {
	Key   string
	Value string
}
