// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ddb

import (
	"time"

	"debuglet/internal/dispatcher/models"
)

type Debuglet struct {
	ID         string
	StartTime  time.Time
	EndTime    time.Time
	Usage      int64
	ExecutorID string
	Addresses  models.CommaSeparatedList
	State      models.DebugletRunState
}

type DebugletLog struct {
	ID         int64
	DebugletID string
	Timestamp  time.Time
	Output     []byte
}

type Transaction struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt time.Time
	Paid      bool
	Hash      string
}

type TransactionState struct {
	Key   string
	Value string
}
