// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package ddb

import (
	"context"

	"debuglet/internal/dispatcher/models"
)

const addEarnings = `-- name: AddEarnings :one
UPDATE earnings
SET total_income = total_income + ?1,
    current_balance = current_balance + ?1
WHERE executor_id = ?2 AND currency = ?3
RETURNING executor_id, currency, total_income, current_balance
`

type AddEarningsParams struct {
	Amount     int64
	ExecutorID string
	Currency   string
}

func (q *Queries) AddEarnings(ctx context.Context, arg AddEarningsParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, addEarnings, arg.Amount, arg.ExecutorID, arg.Currency)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
	)
	return i, err
}

const createDebuglet = `-- name: CreateDebuglet :one
INSERT INTO debuglets (id, start_time, end_time, usage, executor_id, addresses, state)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, start_time, end_time, usage, executor_id, addresses, state
`

type CreateDebugletParams struct {
	ID         string
	StartTime  models.UTCTime
	EndTime    models.UTCTime
	Usage      int64
	ExecutorID string
	Addresses  models.CommaSeparatedList
	State      models.DebugletRunState
}

func (q *Queries) CreateDebuglet(ctx context.Context, arg CreateDebugletParams) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, createDebuglet,
		arg.ID,
		arg.StartTime,
		arg.EndTime,
		arg.Usage,
		arg.ExecutorID,
		arg.Addresses,
		arg.State,
	)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.ExecutorID,
		&i.Addresses,
		&i.State,
	)
	return i, err
}

const createDebugletLog = `-- name: CreateDebugletLog :one
INSERT INTO debuglet_logs (debuglet_id, timestamp, output)
VALUES (?, ?, ?)
RETURNING id, debuglet_id, timestamp, output
`

type CreateDebugletLogParams struct {
	DebugletID string
	Timestamp  models.UTCTime
	Output     []byte
}

func (q *Queries) CreateDebugletLog(ctx context.Context, arg CreateDebugletLogParams) (DebugletLog, error) {
	row := q.db.QueryRowContext(ctx, createDebugletLog, arg.DebugletID, arg.Timestamp, arg.Output)
	var i DebugletLog
	err := row.Scan(
		&i.ID,
		&i.DebugletID,
		&i.Timestamp,
		&i.Output,
	)
	return i, err
}

const createDebugletOrder = `-- name: CreateDebugletOrder :one
INSERT INTO debuglet_order (transaction_id, order_id, executor_id, price, currency )
VALUES (?,?,?,?,?)
RETURNING transaction_id, order_id, executor_id, price, currency
`

type CreateDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
}

func (q *Queries) CreateDebugletOrder(ctx context.Context, arg CreateDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, createDebugletOrder,
		arg.TransactionID,
		arg.OrderID,
		arg.ExecutorID,
		arg.Price,
		arg.Currency,
	)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
	)
	return i, err
}

const createEarnings = `-- name: CreateEarnings :one
INSERT INTO earnings (executor_id, currency, total_income, current_balance)
VALUES (?,?,0,0)
RETURNING executor_id, currency, total_income, current_balance
`

type CreateEarningsParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) CreateEarnings(ctx context.Context, arg CreateEarningsParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, createEarnings, arg.ExecutorID, arg.Currency)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, auth_key, price, currency, method, expires_at, status, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, auth_key, price, method, expires_at, hash, currency, status
`

type CreateTransactionParams struct {
	ID        string
	AuthKey   string
	Price     int64
	Currency  string
	Method    string
	ExpiresAt models.UTCTime
	Status    int64
	Hash      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.AuthKey,
		arg.Price,
		arg.Currency,
		arg.Method,
		arg.ExpiresAt,
		arg.Status,
		arg.Hash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
	)
	return i, err
}

const getDebugletByID = `-- name: GetDebugletByID :one
SELECT id, start_time, end_time, usage, executor_id, addresses, state FROM debuglets
WHERE id = ?
`

func (q *Queries) GetDebugletByID(ctx context.Context, id string) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, getDebugletByID, id)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.ExecutorID,
		&i.Addresses,
		&i.State,
	)
	return i, err
}

const getDebugletOrder = `-- name: GetDebugletOrder :one
/*

DEBUGLET_ORDER

*/

SELECT transaction_id, order_id, executor_id, price, currency FROM debuglet_order
WHERE transaction_id = ? AND order_id = ?
`

type GetDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
}

func (q *Queries) GetDebugletOrder(ctx context.Context, arg GetDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, getDebugletOrder, arg.TransactionID, arg.OrderID)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
	)
	return i, err
}

const getEarnings = `-- name: GetEarnings :many
/*

EARNINGS

*/

SELECT executor_id, currency, total_income, current_balance FROM earnings
WHERE executor_id = ?
`

func (q *Queries) GetEarnings(ctx context.Context, executorID string) ([]Earning, error) {
	rows, err := q.db.QueryContext(ctx, getEarnings, executorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Currency,
			&i.TotalIncome,
			&i.CurrentBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsIn = `-- name: GetEarningsIn :one
SELECT executor_id, currency, total_income, current_balance FROM earnings
WHERE executor_id = ? AND currency = ?
`

type GetEarningsInParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) GetEarningsIn(ctx context.Context, arg GetEarningsInParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, getEarningsIn, arg.ExecutorID, arg.Currency)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
/*

TRANSACTION

*/

SELECT id, auth_key, price, method, expires_at, hash, currency, status FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
	)
	return i, err
}

const getTransactionOrders = `-- name: GetTransactionOrders :many
SELECT transaction_id, order_id, executor_id, price, currency FROM debuglet_order
WHERE transaction_id = ?
`

func (q *Queries) GetTransactionOrders(ctx context.Context, transactionID string) ([]DebugletOrder, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionOrders, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletOrder
	for rows.Next() {
		var i DebugletOrder
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.ExecutorID,
			&i.Price,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionState = `-- name: GetTransactionState :one
SELECT "key", value FROM transaction_states
WHERE key = ?
`

func (q *Queries) GetTransactionState(ctx context.Context, key string) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, getTransactionState, key)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const listDebugletLogs = `-- name: ListDebugletLogs :many
SELECT id, debuglet_id, timestamp, output
FROM debuglet_logs
WHERE debuglet_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListDebugletLogsParams struct {
	DebugletID string
	ID         int64
	Limit      int64
}

func (q *Queries) ListDebugletLogs(ctx context.Context, arg ListDebugletLogsParams) ([]DebugletLog, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletLogs, arg.DebugletID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletLog
	for rows.Next() {
		var i DebugletLog
		if err := rows.Scan(
			&i.ID,
			&i.DebugletID,
			&i.Timestamp,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebuglets = `-- name: ListDebuglets :many
/*

DEBUGLET

*/

SELECT id, start_time, end_time, usage, executor_id, addresses, state FROM debuglets
LIMIT ?
OFFSET ?
`

type ListDebugletsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDebuglets(ctx context.Context, arg ListDebugletsParams) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebuglets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.ExecutorID,
			&i.Addresses,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebugletsEndAfter = `-- name: ListDebugletsEndAfter :many
SELECT id, start_time, end_time, usage, executor_id, addresses, state FROM debuglets
WHERE end_time > ?
`

func (q *Queries) ListDebugletsEndAfter(ctx context.Context, endTime models.UTCTime) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletsEndAfter, endTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.ExecutorID,
			&i.Addresses,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebugletState = `-- name: UpdateDebugletState :one
UPDATE debuglets
SET state = ?
WHERE id = ?
RETURNING id, start_time, end_time, usage, executor_id, addresses, state
`

type UpdateDebugletStateParams struct {
	State models.DebugletRunState
	ID    string
}

func (q *Queries) UpdateDebugletState(ctx context.Context, arg UpdateDebugletStateParams) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, updateDebugletState, arg.State, arg.ID)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.ExecutorID,
		&i.Addresses,
		&i.State,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
INSERT OR REPLACE INTO transaction_states (key, value)
VALUES (?, ?)
RETURNING "key", value
`

type UpdateTransactionStateParams struct {
	Key   string
	Value string
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionState, arg.Key, arg.Value)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions 
SET status = ? 
WHERE id = ? 
RETURNING id, auth_key, price, method, expires_at, hash, currency, status
`

type UpdateTransactionStatusParams struct {
	Status int64
	ID     string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionStatus, arg.Status, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
	)
	return i, err
}
