// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package ddb

import (
	"context"
	"database/sql"
	"time"
)

const createDebuglet = `-- name: CreateDebuglet :one
INSERT INTO debuglets (id, start_time, end_time, usage, executor_id, addresses)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, start_time, end_time, usage, executor_id, addresses
`

type CreateDebugletParams struct {
	ID         string
	StartTime  time.Time
	EndTime    time.Time
	Usage      int64
	ExecutorID string
	Addresses  sql.NullString
}

func (q *Queries) CreateDebuglet(ctx context.Context, arg CreateDebugletParams) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, createDebuglet,
		arg.ID,
		arg.StartTime,
		arg.EndTime,
		arg.Usage,
		arg.ExecutorID,
		arg.Addresses,
	)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.ExecutorID,
		&i.Addresses,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, auth_key, price, method, expires_at, paid, hash)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, auth_key, price, method, expires_at, paid, hash
`

type CreateTransactionParams struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt time.Time
	Paid      bool
	Hash      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.AuthKey,
		arg.Price,
		arg.Method,
		arg.ExpiresAt,
		arg.Paid,
		arg.Hash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Paid,
		&i.Hash,
	)
	return i, err
}

const deleteDebugletByID = `-- name: DeleteDebugletByID :exec
DELETE FROM debuglets
WHERE id = ?
`

func (q *Queries) DeleteDebugletByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDebugletByID, id)
	return err
}

const getDebugletByID = `-- name: GetDebugletByID :one
SELECT id, start_time, end_time, usage, executor_id, addresses FROM debuglets
WHERE id = ?
`

func (q *Queries) GetDebugletByID(ctx context.Context, id string) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, getDebugletByID, id)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.ExecutorID,
		&i.Addresses,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
/*

TRANSACTION

*/

SELECT id, auth_key, price, method, expires_at, paid, hash FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Paid,
		&i.Hash,
	)
	return i, err
}

const getTransactionState = `-- name: GetTransactionState :one
SELECT "key", value FROM transaction_state
WHERE key = ?
`

func (q *Queries) GetTransactionState(ctx context.Context, key string) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, getTransactionState, key)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const listDebuglets = `-- name: ListDebuglets :many
/*

DEBUGLET

*/

SELECT id, start_time, end_time, usage, executor_id, addresses FROM debuglets
`

func (q *Queries) ListDebuglets(ctx context.Context) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebuglets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.ExecutorID,
			&i.Addresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebugletsEndAfter = `-- name: ListDebugletsEndAfter :many
SELECT id, start_time, end_time, usage, executor_id, addresses FROM debuglets
WHERE end_time > ?
`

func (q *Queries) ListDebugletsEndAfter(ctx context.Context, endTime time.Time) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletsEndAfter, endTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.ExecutorID,
			&i.Addresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebugletsEndBefore = `-- name: ListDebugletsEndBefore :many
SELECT id, start_time, end_time, usage, executor_id, addresses FROM debuglets
WHERE end_time < ?
`

func (q *Queries) ListDebugletsEndBefore(ctx context.Context, endTime time.Time) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletsEndBefore, endTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.ExecutorID,
			&i.Addresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionPaid = `-- name: UpdateTransactionPaid :one
UPDATE transactions
SET paid = ?
WHERE id = ?
RETURNING id, auth_key, price, method, expires_at, paid, hash
`

type UpdateTransactionPaidParams struct {
	Paid bool
	ID   string
}

func (q *Queries) UpdateTransactionPaid(ctx context.Context, arg UpdateTransactionPaidParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionPaid, arg.Paid, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Paid,
		&i.Hash,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
INSERT OR REPLACE INTO transaction_state (key, value)
VALUES (?, ?)
RETURNING "key", value
`

type UpdateTransactionStateParams struct {
	Key   string
	Value string
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionState, arg.Key, arg.Value)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}
