http_port = 9000
grpc_port = 9001
log_level = "debug"
disable_tls = true

[tls]
cert_file = "local/configs/dispatcher/cert"
key_file = "local/configs/dispatcher/key"
# ca_file = "local/configs/dispatcher/ca"
