executor_id = "executor-1"
version = "1.0.0"
dispatcher_addr = "localhost:9001"
log_level = "debug"
capacity = 1_000_000_000

[credentials]
ca_cert = "local/configs/executor/ca.crt"
client_cert = "local/configs/executor/cert"
client_key = "local/configs/executor/key"
