version: "3.8"

services:
  executor:
    build:
      context: .
      dockerfile: deploy/docker/executor.Dockerfile
    volumes:
      - ./local/configs/executor:/etc/debuglet/executor:ro
    restart: unless-stopped
    privileged: true

  dispatcher:
    build:
      context: .
      dockerfile: deploy/docker/dispatcher.Dockerfile
    volumes:
      - ./local/configs/dispatcher:/etc/debuglet/dispatcher:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
