version: "3.8"

services:
  executor:
    build:
      context: .
      dockerfile: build/package/executor.Dockerfile
    volumes:
      - ./configs/executor:/etc/debuglet/executor
      - /var/log/debuglet:/var/log/debuglet
    restart: unless-stopped
    privileged: true

  dispatcher:
    build:
      context: .
      dockerfile: build/package/dispatcher.Dockerfile
    volumes:
      - ./local/configs/dispatcher:/local/configs/dispatcher:ro
      - ./local/configs/dispatcher.toml:/etc/debuglet/dispatcher/dispatcher.toml:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
