[identity]
executor_id = "local-executor"
version = "unknown"

[dispatcher]
addr = "localhost:9001"
yamux_addr = "localhost:9000"

[tls]
disable = true

[resources]
capacity = 1_000_000_000
max_debuglets = 1000

[tesla]
seed = ""                                  # optional; empty auto-generates
delay = 30

[network]
# interface = "veth-host"
public_host = "203.0.113.10"              # public IP or domain for TCP/UDP listeners (empty disables listening)
public_ports = "2022,2025-3005,56000-62000"  # allowed public listener ports (comma-separated ranges)

[logging]
log_level = "debug"
json_logs = false

[credentials]
ca_cert = "local/configs/executor/ca.crt"
client_cert = "local/configs/executor/cert"
client_key = "local/configs/executor/key"

[database]
path = ".data/executor.db"

[pricing]
price_per_bw_s = 1
currency = "SUI"
sui_wallet = ""
trial_price_limit=100000
trial_time_limit=500
