// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ETH Zurich

// Package tagvectors loads testdata/tag-vectors-v1.json, the known-answer
// vectors of the debuglet-tag-v1 packet tag generated by the independent
// Python reference tools/tag_vectors.py. The Go tests, the kernel test of
// tagger.c and tools/verify_pcap.py read the same file. Only tests import it.
package tagvectors

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Vector is one packet of the fixture.
type Vector struct {
	Name              string `json:"name"`
	Description       string `json:"description"`
	PacketHex         string `json:"packet_hex"`
	Supported         bool   `json:"supported"`
	UnsupportedReason string `json:"unsupported_reason"`
	InputHex          string `json:"input_hex"`
	SipHashHex        string `json:"siphash_hex"`
	Tag               uint16 `json:"tag"`
	TaggedPacketHex   string `json:"tagged_packet_hex"`
	AnchorTag         uint16 `json:"anchor_tag"`
	SameTagAs         string `json:"same_tag_as"`
	TagDiffersFrom    string `json:"tag_differs_from"`
}

// File is the whole fixture.
type File struct {
	Spec             string `json:"spec"`
	SipHashReference struct {
		KeyHex     string   `json:"key_hex"`
		OutputsHex []string `json:"outputs_hex"`
	} `json:"siphash_reference"`
	Chain struct {
		ChainLength  int64    `json:"chain_length"`
		TailHex      string   `json:"tail_hex"`
		KeysHex      []string `json:"keys_hex"`
		AnchorHex    string   `json:"anchor_hex"`
		SigningEpoch int64    `json:"signing_epoch"`
	} `json:"chain"`
	MeasurementID string   `json:"measurement_id"`
	KtHex         string   `json:"k_t_hex"`
	AKHex         string   `json:"ak_hex"`
	AnchorAKHex   string   `json:"anchor_ak_hex"`
	Vectors       []Vector `json:"vectors"`
}

// Path finds the fixture from the test's working directory (its package
// directory) by walking up to the module root.
func Path(t testing.TB) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("tag vectors: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return filepath.Join(dir, "testdata", "tag-vectors-v1.json")
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("tag vectors: no go.mod above the working directory")
		}
		dir = parent
	}
}

// Load reads the fixture or fails the test.
func Load(t testing.TB) *File {
	t.Helper()
	raw, err := os.ReadFile(Path(t))
	if err != nil {
		t.Fatalf("read tag vectors: %v", err)
	}
	var f File
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse tag vectors: %v", err)
	}
	if len(f.Vectors) == 0 {
		t.Fatal("tag vectors: no vectors")
	}
	return &f
}

// Hex decodes a fixture field or fails the test.
func Hex(t testing.TB, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("tag vectors: bad hex %q: %v", s, err)
	}
	return b
}
