http_port = 9000
grpc_port = 9001
yamux_port = 9002
log_level = "debug"
disable_tls = true
executor_timeout = 60

[tls]
cert_file = "local/configs/dispatcher/cert"
key_file = "local/configs/dispatcher/key"
# ca_file = "local/configs/dispatcher/ca"

[database]
path = "/var/lib/debuglet/users.db"

[sui]
rpc_url             = "https://fullnode.testnet.sui.io:443"
grpc_endpoint       = "fullnode.testnet.sui.io:443"
address          = "0x1737d7dc6b63ef10b7edd316524ab1ece70540a8e012dbc9593a157455ceebef"
poll_interval_seconds = 30