http_port = 9000
grpc_port = 9001
log_level = "debug"
disable_tls = true
executor_timeout = 60
scheduler_granularity_ms = 30000

[tls]
cert_file = "local/configs/dispatcher/cert"
key_file = "local/configs/dispatcher/key"
# ca_file = "local/configs/dispatcher/ca"

[database]
path = "/var/lib/debuglet/transaction.db"

[sui]
grpc_endpoint       = "fullnode.testnet.sui.io:443"
graphql_url         = "https://graphql.testnet.sui.io/graphql"
address          = "0x1737d7dc6b63ef10b7edd316524ab1ece70540a8e012dbc9593a157455ceebef"
payment_registry_id = "0x856d588d43b547c0e1866ff26d61af5ce3531f9c8c3ee2fba4b0553e5a3ee830"
payment_kit_package = "0x7e069abe383e80d32f2aec17b3793da82aabc8c2edf84abbf68dd7b719e71497"