//go:build linux

// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 ETH Zurich

// Package ebpf provides an eBPF-based IPv4 IPID tagger for Linux.
//
// The eBPF program (tagger.c) is compiled at build time into a Go byte-slice
// via bpf2go and loaded at runtime via cilium/ebpf. It attaches to the TC
// egress hook on a named network interface.
//
// Key architecture:
//   - The Go side updates a BPF hash map with the current per-measurement
//     authentication key (ak) at each epoch boundary, and reports the epoch
//     whose key the map may still hold to the key schedule, which withholds
//     that key from disclosure.
//   - The eBPF program reads ak from the map, runs SipHash-2-4 over the packet,
//     and writes the 16-bit result into the IPv4 IPID field.
//   - The Linux kernel's BPF_F_RECOMPUTE_CSUM flag causes the checksum to be
//     updated in-place, so no userspace checksum fix is needed.
//
// # Performance comparison
//
// Use the benchmark in bpf_linux_test.go to compare eBPF vs the pure-Go
// tagger at different packet rates.
package ebpf

import (
	"encoding/binary"
	"errors"
	"fmt"
	"hash/fnv"
	"io"
	"net"
	"sync"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"go.uber.org/zap"

	"github.com/netsec-ethz/debuglet/internal/executor/cleanup"
	"github.com/netsec-ethz/debuglet/internal/executor/tagger/tesla"
)

// akEntry mirrors the struct ak_entry in tagger.c.
// The first 16 bytes of the 32-byte derived key ak are the two 64-bit SipHash
// key words.
type akEntry struct {
	K0 uint64
	K1 uint64
}

// akFromKey converts a 32-byte TESLA authentication key to a BPF ak_entry.
func akFromKey(ak []byte) akEntry {
	if len(ak) < 16 {
		panic("ak must be at least 16 bytes")
	}
	return akEntry{
		K0: binary.LittleEndian.Uint64(ak[0:8]),
		K1: binary.LittleEndian.Uint64(ak[8:16]),
	}
}

// BPFTagger loads, attaches, and manages the eBPF packet tagger.
// It implements tagger.TaggerInterface (eBPF side) and exposes a
// KeyManager for periodic key updates.
type BPFTagger struct {
	objs       taggerObjects
	logger     *zap.Logger
	attachment io.Closer
	// Attachment names how the program is attached: "tcx", or "tc" for the
	// legacy clsact filter used where the kernel has no TCX.
	Attachment  string
	iface       *net.Interface
	schedule    *tesla.KeySchedule
	measureID   []byte
	stopCh      chan struct{}
	refreshDone chan struct{}
	closeOnce   sync.Once
	closeErr    error
	// Immutable owned resources; Close attempts every release even after errors.
	closers []io.Closer

	// refreshMu guards the last refresh failure, the last successful install
	// and the hold: the epoch whose key the map slot may still contain. The
	// hold is claimed before a key is written and released only after the slot
	// is confirmed empty or the program detached.
	refreshMu      sync.Mutex
	refreshErr     error
	lastInstall    time.Time
	installedEpoch int64
	holding        bool
}

// NewBPFTagger loads the compiled eBPF object, attaches the TC egress program
// to iface, and starts the key-update goroutine.
//
// The caller must call Close() when done to detach the program and release BPF
// resources.
func NewBPFTagger(logger *zap.Logger, iface *net.Interface, schedule *tesla.KeySchedule, measurementID []byte) (*BPFTagger, error) {
	// Remove memlock limits (required for eBPF map allocation on older kernels).
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("ebpf: remove memlock: %w", err)
	}

	// Load eBPF objects from embedded bytecode (generated by bpf2go).
	var objs taggerObjects
	if err := loadTaggerObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("ebpf: load tagger objects: %w", err)
	}

	// Attach to TC egress using TCX, or as a legacy clsact filter where the
	// kernel has no TCX. Only a missing TCX falls back: a refused attach, such
	// as a missing privilege, would be refused there too.
	attachment := "tcx"
	l, err := attachWithRollback(func() (io.Closer, error) {
		attached, err := link.AttachTCX(link.TCXOptions{
			Interface: iface.Index,
			Program:   objs.DebugletTag,
			Attach:    ebpf.AttachTCXEgress,
		})
		if errors.Is(err, ebpf.ErrNotSupported) {
			attachment = "tc"
			filter, legacyErr := attachLegacyTC(iface, objs.DebugletTag, mapKey(measurementID))
			if legacyErr != nil {
				return nil, fmt.Errorf("TCX unavailable (%v), and legacy tc: %w", err, legacyErr)
			}
			return filter, nil
		}
		if err != nil {
			return nil, err
		}
		return attached, nil
	}, objs.DebugletTag, objs.AkMap)
	if err != nil {
		return nil, fmt.Errorf("ebpf: attach tagger: %w", err)
	}

	mid := make([]byte, len(measurementID))
	copy(mid, measurementID)

	if logger == nil {
		logger = zap.NewNop()
	}
	bt := &BPFTagger{
		objs:       objs,
		logger:     logger,
		attachment: l,
		Attachment: attachment,
		iface:      iface,
		schedule:   schedule,
		measureID:  mid,
		stopCh:     make(chan struct{}),
		closers:    []io.Closer{l, objs.DebugletTag, objs.AkMap},
	}

	if err := bt.initializeRefresh(bt.updateKey, bt.refreshTimer); err != nil {
		return nil, fmt.Errorf("ebpf: initial key update: %w", err)
	}

	return bt, nil
}

// attachWithRollback owns the already-loaded program/maps until successful
// attachment transfers them to BPFTagger. Even a failed link returned alongside
// an error is released, followed by every independently acquired object.
func attachWithRollback(attach func() (io.Closer, error), owned ...io.Closer) (io.Closer, error) {
	attached, err := attach()
	if err == nil {
		return attached, nil
	}
	if attached != nil {
		owned = append([]io.Closer{attached}, owned...)
	}
	return nil, cleanup.Join(err, closeResources(owned...))
}

// akEntryAt returns the map entry for measurementID at time t, and false when
// the schedule has no usable signing key and the slot must stay empty.
func akEntryAt(schedule *tesla.KeySchedule, measurementID []byte, t time.Time) (akEntry, bool, error) {
	k := schedule.CurrentKey(t)
	if k == nil {
		return akEntry{}, false, nil
	}
	ak, err := tesla.DeriveAK(k, measurementID)
	if err != nil {
		return akEntry{}, false, fmt.Errorf("DeriveAK: %w", err)
	}
	return akFromKey(ak), true, nil
}

// errStaleKey marks a failed slot removal after which the previous epoch's key
// may remain installed and the kernel keeps tagging with it.
var errStaleKey = errors.New("stale key remains installed")

// updateKey writes the current ak to the BPF map at the slot identified by the
// measurement ID hash.
func (bt *BPFTagger) updateKey() error {
	key := bt.MapKey()
	return bt.applyKeyAt(time.Now(),
		func(entry akEntry) error { return bt.objs.AkMap.Put(&key, &entry) },
		func() error { return bt.objs.AkMap.Delete(&key) })
}

// applyKeyAt installs the entry for time now through install. Without a usable
// key, or when the install fails, it removes the slot so the TC program passes
// packets untagged instead of tagging with a public or previous epoch's key.
//
// The hold is claimed before install writes the slot and moves to the new
// epoch once the write succeeded; while a write is in flight it keeps the
// older of the previous and the new epoch. It is released only when remove
// confirmed the slot empty, so a failed removal keeps withholding the key the
// kernel may still tag with.
func (bt *BPFTagger) applyKeyAt(now time.Time, install func(akEntry) error, remove func() error) error {
	entry, ok, err := akEntryAt(bt.schedule, bt.measureID, now)
	if err == nil && ok {
		epoch := bt.schedule.EpochOf(now)
		bt.refreshMu.Lock()
		if !bt.holding || epoch < bt.installedEpoch {
			bt.installedEpoch, bt.holding = epoch, true
		}
		bt.refreshMu.Unlock()
		if err = install(entry); err == nil {
			bt.refreshMu.Lock()
			bt.lastInstall = now
			bt.installedEpoch = epoch
			bt.refreshMu.Unlock()
			return nil
		}
	}
	if rmErr := remove(); rmErr != nil && !errors.Is(rmErr, ebpf.ErrKeyNotExist) {
		if err == nil {
			return fmt.Errorf("%w: %w", errStaleKey, rmErr)
		}
		return fmt.Errorf("%w; %w: %w", err, errStaleKey, rmErr)
	}
	bt.releaseHold()
	return err
}

// releaseHold records that the map slot holds no key any more.
func (bt *BPFTagger) releaseHold() {
	bt.refreshMu.Lock()
	bt.holding = false
	bt.refreshMu.Unlock()
}

// InstalledEpoch reports the epoch whose key the map slot may still hold, for
// the key schedule's disclosure cap.
func (bt *BPFTagger) InstalledEpoch() (int64, bool) {
	bt.refreshMu.Lock()
	defer bt.refreshMu.Unlock()
	return bt.installedEpoch, bt.holding
}

func (bt *BPFTagger) MapKey() uint32 {
	return mapKey(bt.measureID)
}

// mapKey is the slot and socket mark of one measurement, and the handle of its
// legacy tc filter.
func mapKey(measurementID []byte) uint32 {
	h := fnv.New32a()
	h.Write(measurementID)
	return h.Sum32()
}

// LastRefresh reports the last successful install and the outcome of the
// latest refresh, for the schedule's attribution report.
func (bt *BPFTagger) LastRefresh() (time.Time, error) {
	bt.refreshMu.Lock()
	defer bt.refreshMu.Unlock()
	return bt.lastInstall, bt.refreshErr
}

// refreshTimer fires when the next update is due after one that returned
// lastErr (see refreshWait). Without a due update the loop idles until stop.
func (bt *BPFTagger) refreshTimer(lastErr error) (<-chan time.Time, func()) {
	_, holding := bt.InstalledEpoch()
	wait, ok := refreshWait(bt.schedule, time.Now(), lastErr != nil, holding)
	if !ok {
		return nil, func() {}
	}
	timer := time.NewTimer(wait)
	return timer.C, func() { timer.Stop() }
}

// refreshWait returns how long after now the next update is due. After a
// successful update it is the next epoch boundary, so the key of a new epoch
// is installed when it begins and the previous one can be disclosed. A failed
// update is retried after Delay/2, or at the boundary if that comes first; from
// Expiry on, retries continue while the slot may still hold a key. Otherwise no
// key is ever installed again and false means no update is due.
func refreshWait(schedule *tesla.KeySchedule, now time.Time, failed, holding bool) (time.Duration, bool) {
	retry := schedule.Config().Delay / 2
	next, ok := nextBoundary(schedule, now)
	switch {
	case ok && failed:
		return min(retry, next.Sub(now)), true
	case ok:
		return next.Sub(now), true
	case failed && holding:
		return retry, true
	default:
		return 0, false
	}
}

// nextBoundary returns the start of the epoch after the one containing now,
// and false once the chain is exhausted.
func nextBoundary(schedule *tesla.KeySchedule, now time.Time) (time.Time, bool) {
	if schedule.Exhausted(now) {
		return time.Time{}, false
	}
	cfg := schedule.Config()
	return cfg.Epoch.Add(time.Duration(schedule.EpochOf(now)+1) * cfg.Delay), true
}

// initializeRefresh runs before the constructor publishes bt. The tagger
// registers with the schedule before the first key is written, so the schedule
// never sees an installed key without its hold. An initial failure has no
// refresh goroutine to join and still releases every resource.
func (bt *BPFTagger) initializeRefresh(update func() error, newTimer func(lastErr error) (<-chan time.Time, func())) error {
	if bt.schedule != nil {
		bt.schedule.RegisterInstalled(bt)
	}
	if err := update(); err != nil {
		return cleanup.Join(err, bt.Close())
	}
	bt.refreshDone = make(chan struct{})
	go bt.keyRefreshLoop(update, newTimer)
	return nil
}

// keyRefreshLoop waits on a fresh timer after every update, chosen from that
// update's result: the boundary that follows it, or a retry after a failure.
func (bt *BPFTagger) keyRefreshLoop(update func() error, newTimer func(lastErr error) (<-chan time.Time, func())) {
	defer close(bt.refreshDone)
	var lastErr error
	for {
		select {
		case <-bt.stopCh:
			return
		default:
		}
		fired, stopTimer := newTimer(lastErr)
		select {
		case <-bt.stopCh:
			stopTimer()
			return
		case <-fired:
			stopTimer()
			lastErr = update()
			bt.noteRefresh(lastErr)
		}
	}
}

// noteRefresh retains the outcome of one refresh and logs a failure when it
// first occurs or its text changes, and the next success after a failure.
func (bt *BPFTagger) noteRefresh(err error) {
	bt.refreshMu.Lock()
	prev, last := bt.refreshErr, bt.lastInstall
	bt.refreshErr = err
	bt.refreshMu.Unlock()
	switch {
	case err != nil && (prev == nil || prev.Error() != err.Error()):
		bt.logger.Warn("eBPF key refresh failed", zap.Error(err), zap.Time("last_install", last))
	case err == nil && prev != nil:
		bt.logger.Info("eBPF key refresh succeeded", zap.Time("last_install", last))
	}
}

// TagPacket is a no-op on the eBPF path because tagging is done in the kernel.
// It satisfies the TaggerInterface so BPFTagger can be used interchangeably
// with the pure-Go Tagger in tests.
func (bt *BPFTagger) TagPacket(pkt []byte) ([]byte, error) {
	// eBPF tagging is transparent — the kernel modifies packets in the egress
	// path before they hit the wire, without involving userspace.
	return pkt, nil
}

// Close detaches the eBPF program and releases all BPF resources.
func (bt *BPFTagger) Close() error {
	return bt.closeWith(bt.deleteSlot)
}

// deleteSlot empties this measurement's map slot.
func (bt *BPFTagger) deleteSlot() error {
	if bt.objs.AkMap == nil {
		return errors.New("no key map")
	}
	key := bt.MapKey()
	return bt.objs.AkMap.Delete(&key)
}

// closeWith joins the refresh loop, removes the slot through remove and then
// releases the resources, attachment first. The hold is released when the slot
// is confirmed empty or the attachment was closed; otherwise the program may
// still tag with the installed key, which then stays withheld from disclosure.
func (bt *BPFTagger) closeWith(remove func() error) error {
	bt.closeOnce.Do(func() {
		if bt.stopCh != nil {
			close(bt.stopCh)
		}
		if bt.refreshDone != nil {
			<-bt.refreshDone
		}
		rmErr := remove()
		removed := rmErr == nil || errors.Is(rmErr, ebpf.ErrKeyNotExist)
		// The attachment is the first closer; closing it detaches the program.
		detached := false
		if len(bt.closers) > 0 {
			detachErr := closeResources(bt.closers[0])
			detached = detachErr == nil
			bt.closeErr = errors.Join(detachErr, closeResources(bt.closers[1:]...))
		}
		if removed || detached {
			bt.releaseHold()
			if bt.schedule != nil {
				bt.schedule.UnregisterInstalled(bt)
			}
		} else if epoch, holding := bt.InstalledEpoch(); holding {
			bt.logger.Warn("eBPF tagger may still tag after Close; its key stays withheld from disclosure",
				zap.Int64("epoch", epoch), zap.NamedError("remove_error", rmErr), zap.Error(bt.closeErr))
		}
	})
	return bt.closeErr
}

func (bt *BPFTagger) Schedule() *tesla.KeySchedule {
	return bt.schedule
}

func (bt *BPFTagger) SetSocketMark(fd int) error {
	mark := bt.MapKey()
	if err := syscall.SetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SO_MARK, int(mark)); err != nil {
		return fmt.Errorf("setsockopt SO_MARK: %w", err)
	}
	bt.logger.Debug("eBPF socket mark set", zap.String("mark", fmt.Sprintf("%x", mark)))
	return nil
}
