// Copyright 2025 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatcherCommandType int32

const (
	DispatcherCommandType_START_EXECUTION    DispatcherCommandType = 0
	DispatcherCommandType_TEARDOWN_EXECUTION DispatcherCommandType = 1
)

// Enum value maps for DispatcherCommandType.
var (
	DispatcherCommandType_name = map[int32]string{
		0: "START_EXECUTION",
		1: "TEARDOWN_EXECUTION",
	}
	DispatcherCommandType_value = map[string]int32{
		"START_EXECUTION":    0,
		"TEARDOWN_EXECUTION": 1,
	}
)

func (x DispatcherCommandType) Enum() *DispatcherCommandType {
	p := new(DispatcherCommandType)
	*p = x
	return p
}

func (x DispatcherCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatcherCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_protocol_proto_enumTypes[0].Descriptor()
}

func (DispatcherCommandType) Type() protoreflect.EnumType {
	return &file_protocol_protocol_proto_enumTypes[0]
}

func (x DispatcherCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatcherCommandType.Descriptor instead.
func (DispatcherCommandType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

type ExecutorHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`     // Unique ID for this executor instance
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                             // Optional: software version or capabilities
	PricePerBw    float64                `protobuf:"fixed64,3,opt,name=price_per_bw,json=pricePerBw,proto3" json:"price_per_bw,omitempty"` // Price per bit/s of bandwidth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorHello) Reset() {
	*x = ExecutorHello{}
	mi := &file_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHello) ProtoMessage() {}

func (x *ExecutorHello) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHello.ProtoReflect.Descriptor instead.
func (*ExecutorHello) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorHello) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecutorHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExecutorHello) GetPricePerBw() float64 {
	if x != nil {
		return x.PricePerBw
	}
	return 0
}

type ExecutorHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorHeartbeat) Reset() {
	*x = ExecutorHeartbeat{}
	mi := &file_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHeartbeat) ProtoMessage() {}

func (x *ExecutorHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHeartbeat.ProtoReflect.Descriptor instead.
func (*ExecutorHeartbeat) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ExecutorResources struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BandwidthCapacity int64                  `protobuf:"varint,1,opt,name=bandwidth_capacity,json=bandwidthCapacity,proto3" json:"bandwidth_capacity,omitempty"` // Bandwidth capacity the executor can handle per second
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutorResources) Reset() {
	*x = ExecutorResources{}
	mi := &file_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorResources) ProtoMessage() {}

func (x *ExecutorResources) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorResources.ProtoReflect.Descriptor instead.
func (*ExecutorResources) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorResources) GetBandwidthCapacity() int64 {
	if x != nil {
		return x.BandwidthCapacity
	}
	return 0
}

type DebugletAssignment struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SessionId     string                     `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MeasurementId string                     `protobuf:"bytes,2,opt,name=measurement_id,json=measurementId,proto3" json:"measurement_id,omitempty"`
	Code          []byte                     `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Addresses     []string                   `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"` // e.g., SCION or network endpoints
	Policy        *DebugletAssignment_Policy `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletAssignment) Reset() {
	*x = DebugletAssignment{}
	mi := &file_protocol_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletAssignment) ProtoMessage() {}

func (x *DebugletAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletAssignment.ProtoReflect.Descriptor instead.
func (*DebugletAssignment) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *DebugletAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugletAssignment) GetMeasurementId() string {
	if x != nil {
		return x.MeasurementId
	}
	return ""
}

func (x *DebugletAssignment) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *DebugletAssignment) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *DebugletAssignment) GetPolicy() *DebugletAssignment_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type NoOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoOp) Reset() {
	*x = NoOp{}
	mi := &file_protocol_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoOp) ProtoMessage() {}

func (x *NoOp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoOp.ProtoReflect.Descriptor instead.
func (*NoOp) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *NoOp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestinationUpdates struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Updates       []*DestinationUpdates_Update `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationUpdates) Reset() {
	*x = DestinationUpdates{}
	mi := &file_protocol_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationUpdates) ProtoMessage() {}

func (x *DestinationUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationUpdates.ProtoReflect.Descriptor instead.
func (*DestinationUpdates) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *DestinationUpdates) GetUpdates() []*DestinationUpdates_Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_Heartbeat
	//	*ControlMessage_Assignment
	//	*ControlMessage_Noop
	//	*ControlMessage_Updates
	//	*ControlMessage_Resources
	Msg           isControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_protocol_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *ControlMessage) GetMsg() isControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlMessage) GetHello() *ExecutorHello {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeat() *ExecutorHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlMessage) GetAssignment() *DebugletAssignment {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *ControlMessage) GetNoop() *NoOp {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

func (x *ControlMessage) GetUpdates() *DestinationUpdates {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Updates); ok {
			return x.Updates
		}
	}
	return nil
}

func (x *ControlMessage) GetResources() *ExecutorResources {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Resources); ok {
			return x.Resources
		}
	}
	return nil
}

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_Hello struct {
	Hello *ExecutorHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControlMessage_Heartbeat struct {
	Heartbeat *ExecutorHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ControlMessage_Assignment struct {
	Assignment *DebugletAssignment `protobuf:"bytes,3,opt,name=assignment,proto3,oneof"`
}

type ControlMessage_Noop struct {
	Noop *NoOp `protobuf:"bytes,4,opt,name=noop,proto3,oneof"` // Optional, for testing or idle pings
}

type ControlMessage_Updates struct {
	Updates *DestinationUpdates `protobuf:"bytes,5,opt,name=updates,proto3,oneof"`
}

type ControlMessage_Resources struct {
	Resources *ExecutorResources `protobuf:"bytes,6,opt,name=resources,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Msg() {}

func (*ControlMessage_Heartbeat) isControlMessage_Msg() {}

func (*ControlMessage_Assignment) isControlMessage_Msg() {}

func (*ControlMessage_Noop) isControlMessage_Msg() {}

func (*ControlMessage_Updates) isControlMessage_Msg() {}

func (*ControlMessage_Resources) isControlMessage_Msg() {}

type DispatcherCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          DispatcherCommandType  `protobuf:"varint,2,opt,name=type,proto3,enum=debuglet.protocol.DispatcherCommandType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatcherCommand) Reset() {
	*x = DispatcherCommand{}
	mi := &file_protocol_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatcherCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherCommand) ProtoMessage() {}

func (x *DispatcherCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherCommand.ProtoReflect.Descriptor instead.
func (*DispatcherCommand) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *DispatcherCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DispatcherCommand) GetType() DispatcherCommandType {
	if x != nil {
		return x.Type
	}
	return DispatcherCommandType_START_EXECUTION
}

type DebugletReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	MeasurementId string                 `protobuf:"bytes,3,opt,name=measurement_id,json=measurementId,proto3" json:"measurement_id,omitempty"`
	ScionAddr     string                 `protobuf:"bytes,4,opt,name=scion_addr,json=scionAddr,proto3" json:"scion_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletReady) Reset() {
	*x = DebugletReady{}
	mi := &file_protocol_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletReady) ProtoMessage() {}

func (x *DebugletReady) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletReady.ProtoReflect.Descriptor instead.
func (*DebugletReady) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *DebugletReady) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugletReady) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DebugletReady) GetMeasurementId() string {
	if x != nil {
		return x.MeasurementId
	}
	return ""
}

func (x *DebugletReady) GetScionAddr() string {
	if x != nil {
		return x.ScionAddr
	}
	return ""
}

type DebugletStdout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletStdout) Reset() {
	*x = DebugletStdout{}
	mi := &file_protocol_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletStdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletStdout) ProtoMessage() {}

func (x *DebugletStdout) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletStdout.ProtoReflect.Descriptor instead.
func (*DebugletStdout) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *DebugletStdout) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugletStdout) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type DebugletExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // Final result bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletExit) Reset() {
	*x = DebugletExit{}
	mi := &file_protocol_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletExit) ProtoMessage() {}

func (x *DebugletExit) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletExit.ProtoReflect.Descriptor instead.
func (*DebugletExit) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *DebugletExit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugletExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *DebugletExit) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type SessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SessionMessage_DispatcherCmd
	//	*SessionMessage_Ready
	//	*SessionMessage_Stdout
	//	*SessionMessage_Exit
	Msg           isSessionMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_protocol_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *SessionMessage) GetMsg() isSessionMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SessionMessage) GetDispatcherCmd() *DispatcherCommand {
	if x != nil {
		if x, ok := x.Msg.(*SessionMessage_DispatcherCmd); ok {
			return x.DispatcherCmd
		}
	}
	return nil
}

func (x *SessionMessage) GetReady() *DebugletReady {
	if x != nil {
		if x, ok := x.Msg.(*SessionMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *SessionMessage) GetStdout() *DebugletStdout {
	if x != nil {
		if x, ok := x.Msg.(*SessionMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *SessionMessage) GetExit() *DebugletExit {
	if x != nil {
		if x, ok := x.Msg.(*SessionMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isSessionMessage_Msg interface {
	isSessionMessage_Msg()
}

type SessionMessage_DispatcherCmd struct {
	DispatcherCmd *DispatcherCommand `protobuf:"bytes,1,opt,name=dispatcher_cmd,json=dispatcherCmd,proto3,oneof"`
}

type SessionMessage_Ready struct {
	Ready *DebugletReady `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type SessionMessage_Stdout struct {
	Stdout *DebugletStdout `protobuf:"bytes,3,opt,name=stdout,proto3,oneof"`
}

type SessionMessage_Exit struct {
	Exit *DebugletExit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

func (*SessionMessage_DispatcherCmd) isSessionMessage_Msg() {}

func (*SessionMessage_Ready) isSessionMessage_Msg() {}

func (*SessionMessage_Stdout) isSessionMessage_Msg() {}

func (*SessionMessage_Exit) isSessionMessage_Msg() {}

type DebugletAssignment_Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FloorBw       int64                  `protobuf:"varint,1,opt,name=floor_bw,json=floorBw,proto3" json:"floor_bw,omitempty"`       // min bits/s required
	CeilBw        int64                  `protobuf:"varint,2,opt,name=ceil_bw,json=ceilBw,proto3" json:"ceil_bw,omitempty"`          // max bits/s it could use
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // timeout in ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletAssignment_Policy) Reset() {
	*x = DebugletAssignment_Policy{}
	mi := &file_protocol_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletAssignment_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletAssignment_Policy) ProtoMessage() {}

func (x *DebugletAssignment_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletAssignment_Policy.ProtoReflect.Descriptor instead.
func (*DebugletAssignment_Policy) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DebugletAssignment_Policy) GetFloorBw() int64 {
	if x != nil {
		return x.FloorBw
	}
	return 0
}

func (x *DebugletAssignment_Policy) GetCeilBw() int64 {
	if x != nil {
		return x.CeilBw
	}
	return 0
}

func (x *DebugletAssignment_Policy) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DestinationUpdates_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	NewCeilBw     int64                  `protobuf:"varint,3,opt,name=new_ceil_bw,json=newCeilBw,proto3" json:"new_ceil_bw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationUpdates_Update) Reset() {
	*x = DestinationUpdates_Update{}
	mi := &file_protocol_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationUpdates_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationUpdates_Update) ProtoMessage() {}

func (x *DestinationUpdates_Update) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationUpdates_Update.ProtoReflect.Descriptor instead.
func (*DestinationUpdates_Update) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DestinationUpdates_Update) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *DestinationUpdates_Update) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DestinationUpdates_Update) GetNewCeilBw() int64 {
	if x != nil {
		return x.NewCeilBw
	}
	return 0
}

var File_protocol_protocol_proto protoreflect.FileDescriptor

const file_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/protocol.proto\x12\x11debuglet.protocol\"l\n" +
	"\rExecutorHello\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\fprice_per_bw\x18\x03 \x01(\x01R\n" +
	"pricePerBw\"1\n" +
	"\x11ExecutorHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"B\n" +
	"\x11ExecutorResources\x12-\n" +
	"\x12bandwidth_capacity\x18\x01 \x01(\x03R\x11bandwidthCapacity\"\xaf\x02\n" +
	"\x12DebugletAssignment\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0emeasurement_id\x18\x02 \x01(\tR\rmeasurementId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\fR\x04code\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12D\n" +
	"\x06policy\x18\x05 \x01(\v2,.debuglet.protocol.DebugletAssignment.PolicyR\x06policy\x1a[\n" +
	"\x06Policy\x12\x19\n" +
	"\bfloor_bw\x18\x01 \x01(\x03R\afloorBw\x12\x17\n" +
	"\aceil_bw\x18\x02 \x01(\x03R\x06ceilBw\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\" \n" +
	"\x04NoOp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xcd\x01\n" +
	"\x12DestinationUpdates\x12F\n" +
	"\aupdates\x18\x01 \x03(\v2,.debuglet.protocol.DestinationUpdates.UpdateR\aupdates\x1ao\n" +
	"\x06Update\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1e\n" +
	"\vnew_ceil_bw\x18\x03 \x01(\x03R\tnewCeilBw\"\x98\x03\n" +
	"\x0eControlMessage\x128\n" +
	"\x05hello\x18\x01 \x01(\v2 .debuglet.protocol.ExecutorHelloH\x00R\x05hello\x12D\n" +
	"\theartbeat\x18\x02 \x01(\v2$.debuglet.protocol.ExecutorHeartbeatH\x00R\theartbeat\x12G\n" +
	"\n" +
	"assignment\x18\x03 \x01(\v2%.debuglet.protocol.DebugletAssignmentH\x00R\n" +
	"assignment\x12-\n" +
	"\x04noop\x18\x04 \x01(\v2\x17.debuglet.protocol.NoOpH\x00R\x04noop\x12A\n" +
	"\aupdates\x18\x05 \x01(\v2%.debuglet.protocol.DestinationUpdatesH\x00R\aupdates\x12D\n" +
	"\tresources\x18\x06 \x01(\v2$.debuglet.protocol.ExecutorResourcesH\x00R\tresourcesB\x05\n" +
	"\x03msg\"p\n" +
	"\x11DispatcherCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12<\n" +
	"\x04type\x18\x02 \x01(\x0e2(.debuglet.protocol.DispatcherCommandTypeR\x04type\"\x95\x01\n" +
	"\rDebugletReady\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x12%\n" +
	"\x0emeasurement_id\x18\x03 \x01(\tR\rmeasurementId\x12\x1d\n" +
	"\n" +
	"scion_addr\x18\x04 \x01(\tR\tscionAddr\"G\n" +
	"\x0eDebugletStdout\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\"b\n" +
	"\fDebugletExit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"\x94\x02\n" +
	"\x0eSessionMessage\x12M\n" +
	"\x0edispatcher_cmd\x18\x01 \x01(\v2$.debuglet.protocol.DispatcherCommandH\x00R\rdispatcherCmd\x128\n" +
	"\x05ready\x18\x02 \x01(\v2 .debuglet.protocol.DebugletReadyH\x00R\x05ready\x12;\n" +
	"\x06stdout\x18\x03 \x01(\v2!.debuglet.protocol.DebugletStdoutH\x00R\x06stdout\x125\n" +
	"\x04exit\x18\x04 \x01(\v2\x1f.debuglet.protocol.DebugletExitH\x00R\x04exitB\x05\n" +
	"\x03msg*D\n" +
	"\x15DispatcherCommandType\x12\x13\n" +
	"\x0fSTART_EXECUTION\x10\x00\x12\x16\n" +
	"\x12TEARDOWN_EXECUTION\x10\x012\xca\x01\n" +
	"\x12DebugletDispatcher\x12Y\n" +
	"\rControlStream\x12!.debuglet.protocol.ControlMessage\x1a!.debuglet.protocol.ControlMessage(\x010\x01\x12Y\n" +
	"\rSessionStream\x12!.debuglet.protocol.SessionMessage\x1a!.debuglet.protocol.SessionMessage(\x010\x01B\vZ\t/protocolb\x06proto3"

var (
	file_protocol_protocol_proto_rawDescOnce sync.Once
	file_protocol_protocol_proto_rawDescData []byte
)

func file_protocol_protocol_proto_rawDescGZIP() []byte {
	file_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)))
	})
	return file_protocol_protocol_proto_rawDescData
}

var file_protocol_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protocol_protocol_proto_goTypes = []any{
	(DispatcherCommandType)(0),        // 0: debuglet.protocol.DispatcherCommandType
	(*ExecutorHello)(nil),             // 1: debuglet.protocol.ExecutorHello
	(*ExecutorHeartbeat)(nil),         // 2: debuglet.protocol.ExecutorHeartbeat
	(*ExecutorResources)(nil),         // 3: debuglet.protocol.ExecutorResources
	(*DebugletAssignment)(nil),        // 4: debuglet.protocol.DebugletAssignment
	(*NoOp)(nil),                      // 5: debuglet.protocol.NoOp
	(*DestinationUpdates)(nil),        // 6: debuglet.protocol.DestinationUpdates
	(*ControlMessage)(nil),            // 7: debuglet.protocol.ControlMessage
	(*DispatcherCommand)(nil),         // 8: debuglet.protocol.DispatcherCommand
	(*DebugletReady)(nil),             // 9: debuglet.protocol.DebugletReady
	(*DebugletStdout)(nil),            // 10: debuglet.protocol.DebugletStdout
	(*DebugletExit)(nil),              // 11: debuglet.protocol.DebugletExit
	(*SessionMessage)(nil),            // 12: debuglet.protocol.SessionMessage
	(*DebugletAssignment_Policy)(nil), // 13: debuglet.protocol.DebugletAssignment.Policy
	(*DestinationUpdates_Update)(nil), // 14: debuglet.protocol.DestinationUpdates.Update
}
var file_protocol_protocol_proto_depIdxs = []int32{
	13, // 0: debuglet.protocol.DebugletAssignment.policy:type_name -> debuglet.protocol.DebugletAssignment.Policy
	14, // 1: debuglet.protocol.DestinationUpdates.updates:type_name -> debuglet.protocol.DestinationUpdates.Update
	1,  // 2: debuglet.protocol.ControlMessage.hello:type_name -> debuglet.protocol.ExecutorHello
	2,  // 3: debuglet.protocol.ControlMessage.heartbeat:type_name -> debuglet.protocol.ExecutorHeartbeat
	4,  // 4: debuglet.protocol.ControlMessage.assignment:type_name -> debuglet.protocol.DebugletAssignment
	5,  // 5: debuglet.protocol.ControlMessage.noop:type_name -> debuglet.protocol.NoOp
	6,  // 6: debuglet.protocol.ControlMessage.updates:type_name -> debuglet.protocol.DestinationUpdates
	3,  // 7: debuglet.protocol.ControlMessage.resources:type_name -> debuglet.protocol.ExecutorResources
	0,  // 8: debuglet.protocol.DispatcherCommand.type:type_name -> debuglet.protocol.DispatcherCommandType
	8,  // 9: debuglet.protocol.SessionMessage.dispatcher_cmd:type_name -> debuglet.protocol.DispatcherCommand
	9,  // 10: debuglet.protocol.SessionMessage.ready:type_name -> debuglet.protocol.DebugletReady
	10, // 11: debuglet.protocol.SessionMessage.stdout:type_name -> debuglet.protocol.DebugletStdout
	11, // 12: debuglet.protocol.SessionMessage.exit:type_name -> debuglet.protocol.DebugletExit
	7,  // 13: debuglet.protocol.DebugletDispatcher.ControlStream:input_type -> debuglet.protocol.ControlMessage
	12, // 14: debuglet.protocol.DebugletDispatcher.SessionStream:input_type -> debuglet.protocol.SessionMessage
	7,  // 15: debuglet.protocol.DebugletDispatcher.ControlStream:output_type -> debuglet.protocol.ControlMessage
	12, // 16: debuglet.protocol.DebugletDispatcher.SessionStream:output_type -> debuglet.protocol.SessionMessage
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protocol_protocol_proto_init() }
func file_protocol_protocol_proto_init() {
	if File_protocol_protocol_proto != nil {
		return
	}
	file_protocol_protocol_proto_msgTypes[6].OneofWrappers = []any{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_Heartbeat)(nil),
		(*ControlMessage_Assignment)(nil),
		(*ControlMessage_Noop)(nil),
		(*ControlMessage_Updates)(nil),
		(*ControlMessage_Resources)(nil),
	}
	file_protocol_protocol_proto_msgTypes[11].OneofWrappers = []any{
		(*SessionMessage_DispatcherCmd)(nil),
		(*SessionMessage_Ready)(nil),
		(*SessionMessage_Stdout)(nil),
		(*SessionMessage_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_protocol_proto_msgTypes,
	}.Build()
	File_protocol_protocol_proto = out.File
	file_protocol_protocol_proto_goTypes = nil
	file_protocol_protocol_proto_depIdxs = nil
}
