// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 ETH Zurich

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The states of a debuglet from when a debuglet is set to start until before it exits
type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED  RunState = 0
	RunState_RUN_STATE_INITIALIZING RunState = 1
	RunState_RUN_STATE_STARTED      RunState = 2
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_INITIALIZING",
		2: "RUN_STATE_STARTED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED":  0,
		"RUN_STATE_INITIALIZING": 1,
		"RUN_STATE_STARTED":      2,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_protocol_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_protocol_protocol_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

// Why a retained-run lookup produced no metadata. A filtered miss means the
// executor holds a row it deliberately excluded; it is not proof that the
// requested work never existed.
type RetainedRunStatus int32

const (
	RetainedRunStatus_RETAINED_RUN_STATUS_UNSPECIFIED RetainedRunStatus = 0
	RetainedRunStatus_RETAINED_RUN_STATUS_FOUND       RetainedRunStatus = 1
	RetainedRunStatus_RETAINED_RUN_STATUS_FILTERED    RetainedRunStatus = 2
	RetainedRunStatus_RETAINED_RUN_STATUS_ABSENT      RetainedRunStatus = 3
)

// Enum value maps for RetainedRunStatus.
var (
	RetainedRunStatus_name = map[int32]string{
		0: "RETAINED_RUN_STATUS_UNSPECIFIED",
		1: "RETAINED_RUN_STATUS_FOUND",
		2: "RETAINED_RUN_STATUS_FILTERED",
		3: "RETAINED_RUN_STATUS_ABSENT",
	}
	RetainedRunStatus_value = map[string]int32{
		"RETAINED_RUN_STATUS_UNSPECIFIED": 0,
		"RETAINED_RUN_STATUS_FOUND":       1,
		"RETAINED_RUN_STATUS_FILTERED":    2,
		"RETAINED_RUN_STATUS_ABSENT":      3,
	}
)

func (x RetainedRunStatus) Enum() *RetainedRunStatus {
	p := new(RetainedRunStatus)
	*p = x
	return p
}

func (x RetainedRunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetainedRunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_protocol_proto_enumTypes[1].Descriptor()
}

func (RetainedRunStatus) Type() protoreflect.EnumType {
	return &file_protocol_protocol_proto_enumTypes[1]
}

func (x RetainedRunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetainedRunStatus.Descriptor instead.
func (RetainedRunStatus) EnumDescriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

type HelloRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ControlVersion        uint32                 `protobuf:"varint,1,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`
	DispatcherIncarnation string                 `protobuf:"bytes,2,opt,name=dispatcher_incarnation,json=dispatcherIncarnation,proto3" json:"dispatcher_incarnation,omitempty"`
	SessionId             string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken          []byte                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`             // Private offer token; never persist or log.
	LeaseDurationMs       int64                  `protobuf:"varint,5,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"` // Strict v3 control lease; receiver clocks only.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetControlVersion() uint32 {
	if x != nil {
		return x.ControlVersion
	}
	return 0
}

func (x *HelloRequest) GetDispatcherIncarnation() string {
	if x != nil {
		return x.DispatcherIncarnation
	}
	return ""
}

func (x *HelloRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloRequest) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *HelloRequest) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

type HelloResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId             string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`                                          // Unique ID for this executor instance
	Version                string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                  // Optional: software version or capabilities
	SourceIp               string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                                                // Source IP for packet attribution
	TeslaDelaySec          int64                  `protobuf:"varint,4,opt,name=tesla_delay_sec,json=teslaDelaySec,proto3" json:"tesla_delay_sec,omitempty"`                              // TESLA epoch delay in seconds
	TeslaAnchorTimestampNs int64                  `protobuf:"varint,5,opt,name=tesla_anchor_timestamp_ns,json=teslaAnchorTimestampNs,proto3" json:"tesla_anchor_timestamp_ns,omitempty"` // Reference wall-clock time for epoch 0
	TeslaAnchorKey         []byte                 `protobuf:"bytes,6,opt,name=tesla_anchor_key,json=teslaAnchorKey,proto3" json:"tesla_anchor_key,omitempty"`                            // Public anchor k_0 = H^L(seed); used to verify disclosed keys
	IcmpEnabled            bool                   `protobuf:"varint,7,opt,name=icmp_enabled,json=icmpEnabled,proto3" json:"icmp_enabled,omitempty"`                                      // Whether the executor can handle ICMP packets
	PricePerBwS            int64                  `protobuf:"varint,8,opt,name=price_per_bw_s,json=pricePerBwS,proto3" json:"price_per_bw_s,omitempty"`                                  // Price per bit/s of bandwidth
	Currency               string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	PublicHost             *string                `protobuf:"bytes,10,opt,name=public_host,json=publicHost,proto3,oneof" json:"public_host,omitempty"` // Optional: public host for the executor at which debuglet listeners can be contacted
	SuiWallet              *string                `protobuf:"bytes,11,opt,name=sui_wallet,json=suiWallet,proto3,oneof" json:"sui_wallet,omitempty"`
	ControlVersion         uint32                 `protobuf:"varint,12,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`                     // Selected control protocol version
	DispatcherIncarnation  string                 `protobuf:"bytes,13,opt,name=dispatcher_incarnation,json=dispatcherIncarnation,proto3" json:"dispatcher_incarnation,omitempty"` // Echoed dispatcher identity
	SessionId              string                 `protobuf:"bytes,14,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                     // Echoed session identity
	LeaseDurationMs        int64                  `protobuf:"varint,15,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`                // Exact echo of the offered duration.
	// Single-use enrollment credential, presented only until this node's
	// certificate is bound to its executor ID. Never persist or log it.
	EnrollmentToken *string `protobuf:"bytes,16,opt,name=enrollment_token,json=enrollmentToken,proto3,oneof" json:"enrollment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *HelloResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloResponse) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *HelloResponse) GetTeslaDelaySec() int64 {
	if x != nil {
		return x.TeslaDelaySec
	}
	return 0
}

func (x *HelloResponse) GetTeslaAnchorTimestampNs() int64 {
	if x != nil {
		return x.TeslaAnchorTimestampNs
	}
	return 0
}

func (x *HelloResponse) GetTeslaAnchorKey() []byte {
	if x != nil {
		return x.TeslaAnchorKey
	}
	return nil
}

func (x *HelloResponse) GetIcmpEnabled() bool {
	if x != nil {
		return x.IcmpEnabled
	}
	return false
}

func (x *HelloResponse) GetPricePerBwS() int64 {
	if x != nil {
		return x.PricePerBwS
	}
	return 0
}

func (x *HelloResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HelloResponse) GetPublicHost() string {
	if x != nil && x.PublicHost != nil {
		return *x.PublicHost
	}
	return ""
}

func (x *HelloResponse) GetSuiWallet() string {
	if x != nil && x.SuiWallet != nil {
		return *x.SuiWallet
	}
	return ""
}

func (x *HelloResponse) GetControlVersion() uint32 {
	if x != nil {
		return x.ControlVersion
	}
	return 0
}

func (x *HelloResponse) GetDispatcherIncarnation() string {
	if x != nil {
		return x.DispatcherIncarnation
	}
	return ""
}

func (x *HelloResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloResponse) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

func (x *HelloResponse) GetEnrollmentToken() string {
	if x != nil && x.EnrollmentToken != nil {
		return *x.EnrollmentToken
	}
	return ""
}

type DebugletPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FloorBw       int64                  `protobuf:"varint,1,opt,name=floor_bw,json=floorBw,proto3" json:"floor_bw,omitempty"`             // min bits/s required
	CeilBw        int64                  `protobuf:"varint,2,opt,name=ceil_bw,json=ceilBw,proto3" json:"ceil_bw,omitempty"`                // max bits/s it could use
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`       // timeout in ms
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`                         // e.g., SCION or network endpoints
	RequireIcmp   bool                   `protobuf:"varint,5,opt,name=require_icmp,json=requireIcmp,proto3" json:"require_icmp,omitempty"` // whether ICMP is required
	ListenUdp     bool                   `protobuf:"varint,6,opt,name=listen_udp,json=listenUdp,proto3" json:"listen_udp,omitempty"`       // whether the debuglet should setup a UDP listening server
	ListenTcp     bool                   `protobuf:"varint,7,opt,name=listen_tcp,json=listenTcp,proto3" json:"listen_tcp,omitempty"`       // whether the debuglet should setup a TCP listening server
	ListenScion   bool                   `protobuf:"varint,8,opt,name=listen_scion,json=listenScion,proto3" json:"listen_scion,omitempty"` // whether the debuglet should setup a SCION listening server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletPolicy) Reset() {
	*x = DebugletPolicy{}
	mi := &file_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletPolicy) ProtoMessage() {}

func (x *DebugletPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletPolicy.ProtoReflect.Descriptor instead.
func (*DebugletPolicy) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DebugletPolicy) GetFloorBw() int64 {
	if x != nil {
		return x.FloorBw
	}
	return 0
}

func (x *DebugletPolicy) GetCeilBw() int64 {
	if x != nil {
		return x.CeilBw
	}
	return 0
}

func (x *DebugletPolicy) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DebugletPolicy) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *DebugletPolicy) GetRequireIcmp() bool {
	if x != nil {
		return x.RequireIcmp
	}
	return false
}

func (x *DebugletPolicy) GetListenUdp() bool {
	if x != nil {
		return x.ListenUdp
	}
	return false
}

func (x *DebugletPolicy) GetListenTcp() bool {
	if x != nil {
		return x.ListenTcp
	}
	return false
}

func (x *DebugletPolicy) GetListenScion() bool {
	if x != nil {
		return x.ListenScion
	}
	return false
}

type UploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	Wasm           []byte                 `protobuf:"bytes,3,opt,name=wasm,proto3" json:"wasm,omitempty"`
	Args           []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Policy         *DebugletPolicy        `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	TransactionId  string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ControlBinding *ControlBinding        `protobuf:"bytes,7,opt,name=control_binding,json=controlBinding,proto3" json:"control_binding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *UploadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UploadRequest) GetWasm() []byte {
	if x != nil {
		return x.Wasm
	}
	return nil
}

func (x *UploadRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *UploadRequest) GetPolicy() *DebugletPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UploadRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UploadRequest) GetControlBinding() *ControlBinding {
	if x != nil {
		return x.ControlBinding
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{4}
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugletId    string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *AbortRequest) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *AbortRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{6}
}

type DestinationLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BitsLimit     int64                  `protobuf:"varint,2,opt,name=bits_limit,json=bitsLimit,proto3" json:"bits_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationLimit) Reset() {
	*x = DestinationLimit{}
	mi := &file_protocol_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationLimit) ProtoMessage() {}

func (x *DestinationLimit) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationLimit.ProtoReflect.Descriptor instead.
func (*DestinationLimit) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *DestinationLimit) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DestinationLimit) GetBitsLimit() int64 {
	if x != nil {
		return x.BitsLimit
	}
	return 0
}

type BandwidthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limits        []*DestinationLimit    `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthRequest) Reset() {
	*x = BandwidthRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthRequest) ProtoMessage() {}

func (x *BandwidthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthRequest.ProtoReflect.Descriptor instead.
func (*BandwidthRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *BandwidthRequest) GetLimits() []*DestinationLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

type BandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthResponse) Reset() {
	*x = BandwidthResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthResponse) ProtoMessage() {}

func (x *BandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthResponse.ProtoReflect.Descriptor instead.
func (*BandwidthResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{9}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	TeslaKeyEpoch int64                  `protobuf:"varint,3,opt,name=tesla_key_epoch,json=teslaKeyEpoch,proto3" json:"tesla_key_epoch,omitempty"`
	TeslaKey      []byte                 `protobuf:"bytes,4,opt,name=tesla_key,json=teslaKey,proto3" json:"tesla_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *HeartbeatRequest) GetTeslaKeyEpoch() int64 {
	if x != nil {
		return x.TeslaKeyEpoch
	}
	return 0
}

func (x *HeartbeatRequest) GetTeslaKey() []byte {
	if x != nil {
		return x.TeslaKey
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{11}
}

type ResourcesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId        string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	BandwidthCapacity int64                  `protobuf:"varint,2,opt,name=bandwidth_capacity,json=bandwidthCapacity,proto3" json:"bandwidth_capacity,omitempty"` // Bandwidth capacity (bits/s) the executor can handle
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourcesRequest) Reset() {
	*x = ResourcesRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesRequest) ProtoMessage() {}

func (x *ResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesRequest.ProtoReflect.Descriptor instead.
func (*ResourcesRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *ResourcesRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ResourcesRequest) GetBandwidthCapacity() int64 {
	if x != nil {
		return x.BandwidthCapacity
	}
	return 0
}

type ResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesResponse) Reset() {
	*x = ResourcesResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesResponse) ProtoMessage() {}

func (x *ResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesResponse.ProtoReflect.Descriptor instead.
func (*ResourcesResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{13}
}

type DebugletStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugletId    string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	State         RunState               `protobuf:"varint,3,opt,name=state,proto3,enum=debuglet.protocol.RunState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletStateRequest) Reset() {
	*x = DebugletStateRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletStateRequest) ProtoMessage() {}

func (x *DebugletStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletStateRequest.ProtoReflect.Descriptor instead.
func (*DebugletStateRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *DebugletStateRequest) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *DebugletStateRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DebugletStateRequest) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

type DebugletStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletStateResponse) Reset() {
	*x = DebugletStateResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletStateResponse) ProtoMessage() {}

func (x *DebugletStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletStateResponse.ProtoReflect.Descriptor instead.
func (*DebugletStateResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{15}
}

type DebugletAllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugletId    string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Policy        *DebugletPolicy        `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletAllocateRequest) Reset() {
	*x = DebugletAllocateRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletAllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletAllocateRequest) ProtoMessage() {}

func (x *DebugletAllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletAllocateRequest.ProtoReflect.Descriptor instead.
func (*DebugletAllocateRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *DebugletAllocateRequest) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *DebugletAllocateRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DebugletAllocateRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DebugletAllocateRequest) GetPolicy() *DebugletPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// The dispatcher may directly respond with updated limits
type DebugletAllocateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllocatedLimits []*DestinationLimit    `protobuf:"bytes,1,rep,name=allocated_limits,json=allocatedLimits,proto3" json:"allocated_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DebugletAllocateResponse) Reset() {
	*x = DebugletAllocateResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletAllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletAllocateResponse) ProtoMessage() {}

func (x *DebugletAllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletAllocateResponse.ProtoReflect.Descriptor instead.
func (*DebugletAllocateResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *DebugletAllocateResponse) GetAllocatedLimits() []*DestinationLimit {
	if x != nil {
		return x.AllocatedLimits
	}
	return nil
}

type DebugletExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugletId    string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletExitRequest) Reset() {
	*x = DebugletExitRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletExitRequest) ProtoMessage() {}

func (x *DebugletExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletExitRequest.ProtoReflect.Descriptor instead.
func (*DebugletExitRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *DebugletExitRequest) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *DebugletExitRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *DebugletExitRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type DebugletExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletExitResponse) Reset() {
	*x = DebugletExitResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletExitResponse) ProtoMessage() {}

func (x *DebugletExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletExitResponse.ProtoReflect.Descriptor instead.
func (*DebugletExitResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{19}
}

// Initially sent through a debuglet stream to identify the debuglet and executor. After that, the debuglet can send output messages through the same stream.
type DebugletIdent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugletId    string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletIdent) Reset() {
	*x = DebugletIdent{}
	mi := &file_protocol_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletIdent) ProtoMessage() {}

func (x *DebugletIdent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletIdent.ProtoReflect.Descriptor instead.
func (*DebugletIdent) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *DebugletIdent) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *DebugletIdent) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type DebugletOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletOutput) Reset() {
	*x = DebugletOutput{}
	mi := &file_protocol_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletOutput) ProtoMessage() {}

func (x *DebugletOutput) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletOutput.ProtoReflect.Descriptor instead.
func (*DebugletOutput) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *DebugletOutput) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *DebugletOutput) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DebugletStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DebugletStreamRequest_Ident
	//	*DebugletStreamRequest_Output
	Msg           isDebugletStreamRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletStreamRequest) Reset() {
	*x = DebugletStreamRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletStreamRequest) ProtoMessage() {}

func (x *DebugletStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletStreamRequest.ProtoReflect.Descriptor instead.
func (*DebugletStreamRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *DebugletStreamRequest) GetMsg() isDebugletStreamRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DebugletStreamRequest) GetIdent() *DebugletIdent {
	if x != nil {
		if x, ok := x.Msg.(*DebugletStreamRequest_Ident); ok {
			return x.Ident
		}
	}
	return nil
}

func (x *DebugletStreamRequest) GetOutput() *DebugletOutput {
	if x != nil {
		if x, ok := x.Msg.(*DebugletStreamRequest_Output); ok {
			return x.Output
		}
	}
	return nil
}

type isDebugletStreamRequest_Msg interface {
	isDebugletStreamRequest_Msg()
}

type DebugletStreamRequest_Ident struct {
	Ident *DebugletIdent `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

type DebugletStreamRequest_Output struct {
	Output *DebugletOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

func (*DebugletStreamRequest_Ident) isDebugletStreamRequest_Msg() {}

func (*DebugletStreamRequest_Output) isDebugletStreamRequest_Msg() {}

type DebugletStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletStreamResponse) Reset() {
	*x = DebugletStreamResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletStreamResponse) ProtoMessage() {}

func (x *DebugletStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletStreamResponse.ProtoReflect.Descriptor instead.
func (*DebugletStreamResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{23}
}

// Nonsecret immutable run ownership. The bearer token stays in transport state.
type ControlBinding struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DispatcherIncarnation string                 `protobuf:"bytes,1,opt,name=dispatcher_incarnation,json=dispatcherIncarnation,proto3" json:"dispatcher_incarnation,omitempty"`
	SessionId             string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ControlBinding) Reset() {
	*x = ControlBinding{}
	mi := &file_protocol_protocol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlBinding) ProtoMessage() {}

func (x *ControlBinding) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlBinding.ProtoReflect.Descriptor instead.
func (*ControlBinding) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{24}
}

func (x *ControlBinding) GetDispatcherIncarnation() string {
	if x != nil {
		return x.DispatcherIncarnation
	}
	return ""
}

func (x *ControlBinding) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Confirmation uses binding metadata on the separate direct channel.
type BindSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindSessionRequest) Reset() {
	*x = BindSessionRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindSessionRequest) ProtoMessage() {}

func (x *BindSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindSessionRequest.ProtoReflect.Descriptor instead.
func (*BindSessionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{25}
}

func (x *BindSessionRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type BindSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaseDurationMs int64                  `protobuf:"varint,1,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"` // Original initial lease; repeats never rearm it.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BindSessionResponse) Reset() {
	*x = BindSessionResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindSessionResponse) ProtoMessage() {}

func (x *BindSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindSessionResponse.ProtoReflect.Descriptor instead.
func (*BindSessionResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{26}
}

func (x *BindSessionResponse) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

// Binding metadata selects the executor/session. Zero is reserved for Bind;
// ordinary renewal sequences strictly increase within that session.
type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{27}
}

func (x *RenewLeaseRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RenewLeaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sequence        uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LeaseDurationMs int64                  `protobuf:"varint,2,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{28}
}

func (x *RenewLeaseResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RenewLeaseResponse) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

type ProbeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeSessionRequest) Reset() {
	*x = ProbeSessionRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSessionRequest) ProtoMessage() {}

func (x *ProbeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSessionRequest.ProtoReflect.Descriptor instead.
func (*ProbeSessionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{29}
}

func (x *ProbeSessionRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ProbeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeSessionResponse) Reset() {
	*x = ProbeSessionResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSessionResponse) ProtoMessage() {}

func (x *ProbeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSessionResponse.ProtoReflect.Descriptor instead.
func (*ProbeSessionResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{30}
}

func (x *ProbeSessionResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Identity, original ownership and start marker of one stored run. Inspection
// never reads the stored program or its arguments.
type RetainedRun struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DebugletId      string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	OriginalBinding *ControlBinding        `protobuf:"bytes,2,opt,name=original_binding,json=originalBinding,proto3" json:"original_binding,omitempty"` // Empty fields for rows stored before run bindings existed.
	TransactionId   string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Started         bool                   `protobuf:"varint,4,opt,name=started,proto3" json:"started,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetainedRun) Reset() {
	*x = RetainedRun{}
	mi := &file_protocol_protocol_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainedRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedRun) ProtoMessage() {}

func (x *RetainedRun) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedRun.ProtoReflect.Descriptor instead.
func (*RetainedRun) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{31}
}

func (x *RetainedRun) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *RetainedRun) GetOriginalBinding() *ControlBinding {
	if x != nil {
		return x.OriginalBinding
	}
	return nil
}

func (x *RetainedRun) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RetainedRun) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *RetainedRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RetainedRun) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type InspectRetainedRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DebugletId     string                 `protobuf:"bytes,1,opt,name=debuglet_id,json=debugletId,proto3" json:"debuglet_id,omitempty"`
	ControlBinding *ControlBinding        `protobuf:"bytes,2,opt,name=control_binding,json=controlBinding,proto3" json:"control_binding,omitempty"` // The caller's own current session.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InspectRetainedRunRequest) Reset() {
	*x = InspectRetainedRunRequest{}
	mi := &file_protocol_protocol_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRetainedRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRetainedRunRequest) ProtoMessage() {}

func (x *InspectRetainedRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRetainedRunRequest.ProtoReflect.Descriptor instead.
func (*InspectRetainedRunRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{32}
}

func (x *InspectRetainedRunRequest) GetDebugletId() string {
	if x != nil {
		return x.DebugletId
	}
	return ""
}

func (x *InspectRetainedRunRequest) GetControlBinding() *ControlBinding {
	if x != nil {
		return x.ControlBinding
	}
	return nil
}

type InspectRetainedRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RetainedRunStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=debuglet.protocol.RetainedRunStatus" json:"status,omitempty"`
	Run           *RetainedRun           `protobuf:"bytes,2,opt,name=run,proto3,oneof" json:"run,omitempty"` // Present exactly when status is FOUND.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRetainedRunResponse) Reset() {
	*x = InspectRetainedRunResponse{}
	mi := &file_protocol_protocol_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRetainedRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRetainedRunResponse) ProtoMessage() {}

func (x *InspectRetainedRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRetainedRunResponse.ProtoReflect.Descriptor instead.
func (*InspectRetainedRunResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{33}
}

func (x *InspectRetainedRunResponse) GetStatus() RetainedRunStatus {
	if x != nil {
		return x.Status
	}
	return RetainedRunStatus_RETAINED_RUN_STATUS_UNSPECIFIED
}

func (x *InspectRetainedRunResponse) GetRun() *RetainedRun {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_protocol_protocol_proto protoreflect.FileDescriptor

const file_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/protocol.proto\x12\x11debuglet.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\fHelloRequest\x12'\n" +
	"\x0fcontrol_version\x18\x01 \x01(\rR\x0econtrolVersion\x125\n" +
	"\x16dispatcher_incarnation\x18\x02 \x01(\tR\x15dispatcherIncarnation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x04 \x01(\fR\fsessionToken\x12*\n" +
	"\x11lease_duration_ms\x18\x05 \x01(\x03R\x0fleaseDurationMs\"\xb1\x05\n" +
	"\rHelloResponse\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12&\n" +
	"\x0ftesla_delay_sec\x18\x04 \x01(\x03R\rteslaDelaySec\x129\n" +
	"\x19tesla_anchor_timestamp_ns\x18\x05 \x01(\x03R\x16teslaAnchorTimestampNs\x12(\n" +
	"\x10tesla_anchor_key\x18\x06 \x01(\fR\x0eteslaAnchorKey\x12!\n" +
	"\ficmp_enabled\x18\a \x01(\bR\vicmpEnabled\x12#\n" +
	"\x0eprice_per_bw_s\x18\b \x01(\x03R\vpricePerBwS\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12$\n" +
	"\vpublic_host\x18\n" +
	" \x01(\tH\x00R\n" +
	"publicHost\x88\x01\x01\x12\"\n" +
	"\n" +
	"sui_wallet\x18\v \x01(\tH\x01R\tsuiWallet\x88\x01\x01\x12'\n" +
	"\x0fcontrol_version\x18\f \x01(\rR\x0econtrolVersion\x125\n" +
	"\x16dispatcher_incarnation\x18\r \x01(\tR\x15dispatcherIncarnation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x0e \x01(\tR\tsessionId\x12*\n" +
	"\x11lease_duration_ms\x18\x0f \x01(\x03R\x0fleaseDurationMs\x12.\n" +
	"\x10enrollment_token\x18\x10 \x01(\tH\x02R\x0fenrollmentToken\x88\x01\x01B\x0e\n" +
	"\f_public_hostB\r\n" +
	"\v_sui_walletB\x13\n" +
	"\x11_enrollment_token\"\x85\x02\n" +
	"\x0eDebugletPolicy\x12\x19\n" +
	"\bfloor_bw\x18\x01 \x01(\x03R\afloorBw\x12\x17\n" +
	"\aceil_bw\x18\x02 \x01(\x03R\x06ceilBw\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12!\n" +
	"\frequire_icmp\x18\x05 \x01(\bR\vrequireIcmp\x12\x1d\n" +
	"\n" +
	"listen_udp\x18\x06 \x01(\bR\tlistenUdp\x12\x1d\n" +
	"\n" +
	"listen_tcp\x18\a \x01(\bR\tlistenTcp\x12!\n" +
	"\flisten_scion\x18\b \x01(\bR\vlistenScion\"\xc4\x02\n" +
	"\rUploadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12\x12\n" +
	"\x04wasm\x18\x03 \x01(\fR\x04wasm\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x129\n" +
	"\x06policy\x18\x05 \x01(\v2!.debuglet.protocol.DebugletPolicyR\x06policy\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12J\n" +
	"\x0fcontrol_binding\x18\a \x01(\v2!.debuglet.protocol.ControlBindingR\x0econtrolBindingB\r\n" +
	"\v_start_time\"\x10\n" +
	"\x0eUploadResponse\"G\n" +
	"\fAbortRequest\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0f\n" +
	"\rAbortResponse\"K\n" +
	"\x10DestinationLimit\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"bits_limit\x18\x02 \x01(\x03R\tbitsLimit\"O\n" +
	"\x10BandwidthRequest\x12;\n" +
	"\x06limits\x18\x01 \x03(\v2#.debuglet.protocol.DestinationLimitR\x06limits\"\x13\n" +
	"\x11BandwidthResponse\"\x9b\x01\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12&\n" +
	"\x0ftesla_key_epoch\x18\x03 \x01(\x03R\rteslaKeyEpoch\x12\x1b\n" +
	"\ttesla_key\x18\x04 \x01(\fR\bteslaKey\"\x13\n" +
	"\x11HeartbeatResponse\"b\n" +
	"\x10ResourcesRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12-\n" +
	"\x12bandwidth_capacity\x18\x02 \x01(\x03R\x11bandwidthCapacity\"\x13\n" +
	"\x11ResourcesResponse\"\x8b\x01\n" +
	"\x14DebugletStateRequest\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.debuglet.protocol.RunStateR\x05state\"\x17\n" +
	"\x15DebugletStateResponse\"\xbd\x01\n" +
	"\x17DebugletAllocateRequest\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x129\n" +
	"\x06policy\x18\x04 \x01(\v2!.debuglet.protocol.DebugletPolicyR\x06policy\"j\n" +
	"\x18DebugletAllocateResponse\x12N\n" +
	"\x10allocated_limits\x18\x01 \x03(\v2#.debuglet.protocol.DestinationLimitR\x0fallocatedLimits\"\x8f\x01\n" +
	"\x13DebugletExitRequest\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\x16\n" +
	"\x14DebugletExitResponse\"Q\n" +
	"\rDebugletIdent\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\"b\n" +
	"\x0eDebugletOutput\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x95\x01\n" +
	"\x15DebugletStreamRequest\x128\n" +
	"\x05ident\x18\x01 \x01(\v2 .debuglet.protocol.DebugletIdentH\x00R\x05ident\x12;\n" +
	"\x06output\x18\x02 \x01(\v2!.debuglet.protocol.DebugletOutputH\x00R\x06outputB\x05\n" +
	"\x03msg\"\x18\n" +
	"\x16DebugletStreamResponse\"f\n" +
	"\x0eControlBinding\x125\n" +
	"\x16dispatcher_incarnation\x18\x01 \x01(\tR\x15dispatcherIncarnation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"5\n" +
	"\x12BindSessionRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\"A\n" +
	"\x13BindSessionResponse\x12*\n" +
	"\x11lease_duration_ms\x18\x01 \x01(\x03R\x0fleaseDurationMs\"/\n" +
	"\x11RenewLeaseRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\\\n" +
	"\x12RenewLeaseResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12*\n" +
	"\x11lease_duration_ms\x18\x02 \x01(\x03R\x0fleaseDurationMs\"1\n" +
	"\x13ProbeSessionRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"2\n" +
	"\x14ProbeSessionResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\xdb\x02\n" +
	"\vRetainedRun\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12L\n" +
	"\x10original_binding\x18\x02 \x01(\v2!.debuglet.protocol.ControlBindingR\x0foriginalBinding\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x18\n" +
	"\astarted\x18\x04 \x01(\bR\astarted\x12>\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartTime\x88\x01\x01B\r\n" +
	"\v_started_atB\r\n" +
	"\v_start_time\"\x88\x01\n" +
	"\x19InspectRetainedRunRequest\x12\x1f\n" +
	"\vdebuglet_id\x18\x01 \x01(\tR\n" +
	"debugletId\x12J\n" +
	"\x0fcontrol_binding\x18\x02 \x01(\v2!.debuglet.protocol.ControlBindingR\x0econtrolBinding\"\x99\x01\n" +
	"\x1aInspectRetainedRunResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.debuglet.protocol.RetainedRunStatusR\x06status\x125\n" +
	"\x03run\x18\x02 \x01(\v2\x1e.debuglet.protocol.RetainedRunH\x00R\x03run\x88\x01\x01B\x06\n" +
	"\x04_run*X\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RUN_STATE_INITIALIZING\x10\x01\x12\x15\n" +
	"\x11RUN_STATE_STARTED\x10\x02*\x99\x01\n" +
	"\x11RetainedRunStatus\x12#\n" +
	"\x1fRETAINED_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RETAINED_RUN_STATUS_FOUND\x10\x01\x12 \n" +
	"\x1cRETAINED_RUN_STATUS_FILTERED\x10\x02\x12\x1e\n" +
	"\x1aRETAINED_RUN_STATUS_ABSENT\x10\x032\x99\x06\n" +
	"\x11DispatcherService\x12V\n" +
	"\tHeartbeat\x12#.debuglet.protocol.HeartbeatRequest\x1a$.debuglet.protocol.HeartbeatResponse\x12V\n" +
	"\tResources\x12#.debuglet.protocol.ResourcesRequest\x1a$.debuglet.protocol.ResourcesResponse\x12b\n" +
	"\rDebugletState\x12'.debuglet.protocol.DebugletStateRequest\x1a(.debuglet.protocol.DebugletStateResponse\x12k\n" +
	"\x10DebugletAllocate\x12*.debuglet.protocol.DebugletAllocateRequest\x1a+.debuglet.protocol.DebugletAllocateResponse\x12_\n" +
	"\fDebugletExit\x12&.debuglet.protocol.DebugletExitRequest\x1a'.debuglet.protocol.DebugletExitResponse\x12i\n" +
	"\x0eDebugletStream\x12(.debuglet.protocol.DebugletStreamRequest\x1a).debuglet.protocol.DebugletStreamResponse(\x010\x01\x12\\\n" +
	"\vBindSession\x12%.debuglet.protocol.BindSessionRequest\x1a&.debuglet.protocol.BindSessionResponse\x12Y\n" +
	"\n" +
	"RenewLease\x12$.debuglet.protocol.RenewLeaseRequest\x1a%.debuglet.protocol.RenewLeaseResponse2\xa4\x04\n" +
	"\x0fExecutorService\x12J\n" +
	"\x05Hello\x12\x1f.debuglet.protocol.HelloRequest\x1a .debuglet.protocol.HelloResponse\x12M\n" +
	"\x06Upload\x12 .debuglet.protocol.UploadRequest\x1a!.debuglet.protocol.UploadResponse\x12J\n" +
	"\x05Abort\x12\x1f.debuglet.protocol.AbortRequest\x1a .debuglet.protocol.AbortResponse\x12V\n" +
	"\tBandwidth\x12#.debuglet.protocol.BandwidthRequest\x1a$.debuglet.protocol.BandwidthResponse\x12_\n" +
	"\fProbeSession\x12&.debuglet.protocol.ProbeSessionRequest\x1a'.debuglet.protocol.ProbeSessionResponse\x12q\n" +
	"\x12InspectRetainedRun\x12,.debuglet.protocol.InspectRetainedRunRequest\x1a-.debuglet.protocol.InspectRetainedRunResponseB\vZ\t/protocolb\x06proto3"

var (
	file_protocol_protocol_proto_rawDescOnce sync.Once
	file_protocol_protocol_proto_rawDescData []byte
)

func file_protocol_protocol_proto_rawDescGZIP() []byte {
	file_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)))
	})
	return file_protocol_protocol_proto_rawDescData
}

var file_protocol_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_protocol_protocol_proto_goTypes = []any{
	(RunState)(0),                      // 0: debuglet.protocol.RunState
	(RetainedRunStatus)(0),             // 1: debuglet.protocol.RetainedRunStatus
	(*HelloRequest)(nil),               // 2: debuglet.protocol.HelloRequest
	(*HelloResponse)(nil),              // 3: debuglet.protocol.HelloResponse
	(*DebugletPolicy)(nil),             // 4: debuglet.protocol.DebugletPolicy
	(*UploadRequest)(nil),              // 5: debuglet.protocol.UploadRequest
	(*UploadResponse)(nil),             // 6: debuglet.protocol.UploadResponse
	(*AbortRequest)(nil),               // 7: debuglet.protocol.AbortRequest
	(*AbortResponse)(nil),              // 8: debuglet.protocol.AbortResponse
	(*DestinationLimit)(nil),           // 9: debuglet.protocol.DestinationLimit
	(*BandwidthRequest)(nil),           // 10: debuglet.protocol.BandwidthRequest
	(*BandwidthResponse)(nil),          // 11: debuglet.protocol.BandwidthResponse
	(*HeartbeatRequest)(nil),           // 12: debuglet.protocol.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 13: debuglet.protocol.HeartbeatResponse
	(*ResourcesRequest)(nil),           // 14: debuglet.protocol.ResourcesRequest
	(*ResourcesResponse)(nil),          // 15: debuglet.protocol.ResourcesResponse
	(*DebugletStateRequest)(nil),       // 16: debuglet.protocol.DebugletStateRequest
	(*DebugletStateResponse)(nil),      // 17: debuglet.protocol.DebugletStateResponse
	(*DebugletAllocateRequest)(nil),    // 18: debuglet.protocol.DebugletAllocateRequest
	(*DebugletAllocateResponse)(nil),   // 19: debuglet.protocol.DebugletAllocateResponse
	(*DebugletExitRequest)(nil),        // 20: debuglet.protocol.DebugletExitRequest
	(*DebugletExitResponse)(nil),       // 21: debuglet.protocol.DebugletExitResponse
	(*DebugletIdent)(nil),              // 22: debuglet.protocol.DebugletIdent
	(*DebugletOutput)(nil),             // 23: debuglet.protocol.DebugletOutput
	(*DebugletStreamRequest)(nil),      // 24: debuglet.protocol.DebugletStreamRequest
	(*DebugletStreamResponse)(nil),     // 25: debuglet.protocol.DebugletStreamResponse
	(*ControlBinding)(nil),             // 26: debuglet.protocol.ControlBinding
	(*BindSessionRequest)(nil),         // 27: debuglet.protocol.BindSessionRequest
	(*BindSessionResponse)(nil),        // 28: debuglet.protocol.BindSessionResponse
	(*RenewLeaseRequest)(nil),          // 29: debuglet.protocol.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),         // 30: debuglet.protocol.RenewLeaseResponse
	(*ProbeSessionRequest)(nil),        // 31: debuglet.protocol.ProbeSessionRequest
	(*ProbeSessionResponse)(nil),       // 32: debuglet.protocol.ProbeSessionResponse
	(*RetainedRun)(nil),                // 33: debuglet.protocol.RetainedRun
	(*InspectRetainedRunRequest)(nil),  // 34: debuglet.protocol.InspectRetainedRunRequest
	(*InspectRetainedRunResponse)(nil), // 35: debuglet.protocol.InspectRetainedRunResponse
	(*timestamppb.Timestamp)(nil),      // 36: google.protobuf.Timestamp
}
var file_protocol_protocol_proto_depIdxs = []int32{
	36, // 0: debuglet.protocol.UploadRequest.start_time:type_name -> google.protobuf.Timestamp
	4,  // 1: debuglet.protocol.UploadRequest.policy:type_name -> debuglet.protocol.DebugletPolicy
	26, // 2: debuglet.protocol.UploadRequest.control_binding:type_name -> debuglet.protocol.ControlBinding
	9,  // 3: debuglet.protocol.BandwidthRequest.limits:type_name -> debuglet.protocol.DestinationLimit
	0,  // 4: debuglet.protocol.DebugletStateRequest.state:type_name -> debuglet.protocol.RunState
	4,  // 5: debuglet.protocol.DebugletAllocateRequest.policy:type_name -> debuglet.protocol.DebugletPolicy
	9,  // 6: debuglet.protocol.DebugletAllocateResponse.allocated_limits:type_name -> debuglet.protocol.DestinationLimit
	36, // 7: debuglet.protocol.DebugletOutput.timestamp:type_name -> google.protobuf.Timestamp
	22, // 8: debuglet.protocol.DebugletStreamRequest.ident:type_name -> debuglet.protocol.DebugletIdent
	23, // 9: debuglet.protocol.DebugletStreamRequest.output:type_name -> debuglet.protocol.DebugletOutput
	26, // 10: debuglet.protocol.RetainedRun.original_binding:type_name -> debuglet.protocol.ControlBinding
	36, // 11: debuglet.protocol.RetainedRun.started_at:type_name -> google.protobuf.Timestamp
	36, // 12: debuglet.protocol.RetainedRun.start_time:type_name -> google.protobuf.Timestamp
	26, // 13: debuglet.protocol.InspectRetainedRunRequest.control_binding:type_name -> debuglet.protocol.ControlBinding
	1,  // 14: debuglet.protocol.InspectRetainedRunResponse.status:type_name -> debuglet.protocol.RetainedRunStatus
	33, // 15: debuglet.protocol.InspectRetainedRunResponse.run:type_name -> debuglet.protocol.RetainedRun
	12, // 16: debuglet.protocol.DispatcherService.Heartbeat:input_type -> debuglet.protocol.HeartbeatRequest
	14, // 17: debuglet.protocol.DispatcherService.Resources:input_type -> debuglet.protocol.ResourcesRequest
	16, // 18: debuglet.protocol.DispatcherService.DebugletState:input_type -> debuglet.protocol.DebugletStateRequest
	18, // 19: debuglet.protocol.DispatcherService.DebugletAllocate:input_type -> debuglet.protocol.DebugletAllocateRequest
	20, // 20: debuglet.protocol.DispatcherService.DebugletExit:input_type -> debuglet.protocol.DebugletExitRequest
	24, // 21: debuglet.protocol.DispatcherService.DebugletStream:input_type -> debuglet.protocol.DebugletStreamRequest
	27, // 22: debuglet.protocol.DispatcherService.BindSession:input_type -> debuglet.protocol.BindSessionRequest
	29, // 23: debuglet.protocol.DispatcherService.RenewLease:input_type -> debuglet.protocol.RenewLeaseRequest
	2,  // 24: debuglet.protocol.ExecutorService.Hello:input_type -> debuglet.protocol.HelloRequest
	5,  // 25: debuglet.protocol.ExecutorService.Upload:input_type -> debuglet.protocol.UploadRequest
	7,  // 26: debuglet.protocol.ExecutorService.Abort:input_type -> debuglet.protocol.AbortRequest
	10, // 27: debuglet.protocol.ExecutorService.Bandwidth:input_type -> debuglet.protocol.BandwidthRequest
	31, // 28: debuglet.protocol.ExecutorService.ProbeSession:input_type -> debuglet.protocol.ProbeSessionRequest
	34, // 29: debuglet.protocol.ExecutorService.InspectRetainedRun:input_type -> debuglet.protocol.InspectRetainedRunRequest
	13, // 30: debuglet.protocol.DispatcherService.Heartbeat:output_type -> debuglet.protocol.HeartbeatResponse
	15, // 31: debuglet.protocol.DispatcherService.Resources:output_type -> debuglet.protocol.ResourcesResponse
	17, // 32: debuglet.protocol.DispatcherService.DebugletState:output_type -> debuglet.protocol.DebugletStateResponse
	19, // 33: debuglet.protocol.DispatcherService.DebugletAllocate:output_type -> debuglet.protocol.DebugletAllocateResponse
	21, // 34: debuglet.protocol.DispatcherService.DebugletExit:output_type -> debuglet.protocol.DebugletExitResponse
	25, // 35: debuglet.protocol.DispatcherService.DebugletStream:output_type -> debuglet.protocol.DebugletStreamResponse
	28, // 36: debuglet.protocol.DispatcherService.BindSession:output_type -> debuglet.protocol.BindSessionResponse
	30, // 37: debuglet.protocol.DispatcherService.RenewLease:output_type -> debuglet.protocol.RenewLeaseResponse
	3,  // 38: debuglet.protocol.ExecutorService.Hello:output_type -> debuglet.protocol.HelloResponse
	6,  // 39: debuglet.protocol.ExecutorService.Upload:output_type -> debuglet.protocol.UploadResponse
	8,  // 40: debuglet.protocol.ExecutorService.Abort:output_type -> debuglet.protocol.AbortResponse
	11, // 41: debuglet.protocol.ExecutorService.Bandwidth:output_type -> debuglet.protocol.BandwidthResponse
	32, // 42: debuglet.protocol.ExecutorService.ProbeSession:output_type -> debuglet.protocol.ProbeSessionResponse
	35, // 43: debuglet.protocol.ExecutorService.InspectRetainedRun:output_type -> debuglet.protocol.InspectRetainedRunResponse
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protocol_protocol_proto_init() }
func file_protocol_protocol_proto_init() {
	if File_protocol_protocol_proto != nil {
		return
	}
	file_protocol_protocol_proto_msgTypes[1].OneofWrappers = []any{}
	file_protocol_protocol_proto_msgTypes[3].OneofWrappers = []any{}
	file_protocol_protocol_proto_msgTypes[18].OneofWrappers = []any{}
	file_protocol_protocol_proto_msgTypes[22].OneofWrappers = []any{
		(*DebugletStreamRequest_Ident)(nil),
		(*DebugletStreamRequest_Output)(nil),
	}
	file_protocol_protocol_proto_msgTypes[31].OneofWrappers = []any{}
	file_protocol_protocol_proto_msgTypes[33].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_protocol_proto_msgTypes,
	}.Build()
	File_protocol_protocol_proto = out.File
	file_protocol_protocol_proto_goTypes = nil
	file_protocol_protocol_proto_depIdxs = nil
}
