// Copyright 2025 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: protocol/protocol.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DebugletDispatcher_ControlStream_FullMethodName = "/debuglet.protocol.DebugletDispatcher/ControlStream"
	DebugletDispatcher_SessionStream_FullMethodName = "/debuglet.protocol.DebugletDispatcher/SessionStream"
)

// DebugletDispatcherClient is the client API for DebugletDispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DebugletDispatcherClient interface {
	// Persistent control channel for executor registration, heartbeat, and task assignment
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
	// Per-session bidirectional stream for debuglet execution
	SessionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error)
}

type debugletDispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugletDispatcherClient(cc grpc.ClientConnInterface) DebugletDispatcherClient {
	return &debugletDispatcherClient{cc}
}

func (c *debugletDispatcherClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DebugletDispatcher_ServiceDesc.Streams[0], DebugletDispatcher_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugletDispatcher_ControlStreamClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

func (c *debugletDispatcherClient) SessionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DebugletDispatcher_ServiceDesc.Streams[1], DebugletDispatcher_SessionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMessage, SessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugletDispatcher_SessionStreamClient = grpc.BidiStreamingClient[SessionMessage, SessionMessage]

// DebugletDispatcherServer is the server API for DebugletDispatcher service.
// All implementations must embed UnimplementedDebugletDispatcherServer
// for forward compatibility.
type DebugletDispatcherServer interface {
	// Persistent control channel for executor registration, heartbeat, and task assignment
	ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	// Per-session bidirectional stream for debuglet execution
	SessionStream(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error
	mustEmbedUnimplementedDebugletDispatcherServer()
}

// UnimplementedDebugletDispatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDebugletDispatcherServer struct{}

func (UnimplementedDebugletDispatcherServer) ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedDebugletDispatcherServer) SessionStream(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error {
	return status.Error(codes.Unimplemented, "method SessionStream not implemented")
}
func (UnimplementedDebugletDispatcherServer) mustEmbedUnimplementedDebugletDispatcherServer() {}
func (UnimplementedDebugletDispatcherServer) testEmbeddedByValue()                            {}

// UnsafeDebugletDispatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebugletDispatcherServer will
// result in compilation errors.
type UnsafeDebugletDispatcherServer interface {
	mustEmbedUnimplementedDebugletDispatcherServer()
}

func RegisterDebugletDispatcherServer(s grpc.ServiceRegistrar, srv DebugletDispatcherServer) {
	// If the following call panics, it indicates UnimplementedDebugletDispatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DebugletDispatcher_ServiceDesc, srv)
}

func _DebugletDispatcher_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DebugletDispatcherServer).ControlStream(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugletDispatcher_ControlStreamServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

func _DebugletDispatcher_SessionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DebugletDispatcherServer).SessionStream(&grpc.GenericServerStream[SessionMessage, SessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DebugletDispatcher_SessionStreamServer = grpc.BidiStreamingServer[SessionMessage, SessionMessage]

// DebugletDispatcher_ServiceDesc is the grpc.ServiceDesc for DebugletDispatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DebugletDispatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "debuglet.protocol.DebugletDispatcher",
	HandlerType: (*DebugletDispatcherServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _DebugletDispatcher_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SessionStream",
			Handler:       _DebugletDispatcher_SessionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protocol/protocol.proto",
}
