// Copyright 2025 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutorHello struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId             string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`                                          // Unique ID for this executor instance
	Version                string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                  // Optional: software version or capabilities
	SourceIp               string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                                                // Source IP for packet attribution
	TeslaDelaySec          int64                  `protobuf:"varint,4,opt,name=tesla_delay_sec,json=teslaDelaySec,proto3" json:"tesla_delay_sec,omitempty"`                              // TESLA epoch delay in seconds
	TeslaAnchorTimestampNs int64                  `protobuf:"varint,5,opt,name=tesla_anchor_timestamp_ns,json=teslaAnchorTimestampNs,proto3" json:"tesla_anchor_timestamp_ns,omitempty"` // Reference wall-clock time for epoch 0
	TeslaAnchorKey         []byte                 `protobuf:"bytes,6,opt,name=tesla_anchor_key,json=teslaAnchorKey,proto3" json:"tesla_anchor_key,omitempty"`                            // Public anchor k_0 = H^L(seed); used to verify disclosed keys
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecutorHello) Reset() {
	*x = ExecutorHello{}
	mi := &file_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHello) ProtoMessage() {}

func (x *ExecutorHello) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHello.ProtoReflect.Descriptor instead.
func (*ExecutorHello) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorHello) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *ExecutorHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExecutorHello) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ExecutorHello) GetTeslaDelaySec() int64 {
	if x != nil {
		return x.TeslaDelaySec
	}
	return 0
}

func (x *ExecutorHello) GetTeslaAnchorTimestampNs() int64 {
	if x != nil {
		return x.TeslaAnchorTimestampNs
	}
	return 0
}

func (x *ExecutorHello) GetTeslaAnchorKey() []byte {
	if x != nil {
		return x.TeslaAnchorKey
	}
	return nil
}

type ExecutorHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	TeslaKeyEpoch int64                  `protobuf:"varint,3,opt,name=tesla_key_epoch,json=teslaKeyEpoch,proto3" json:"tesla_key_epoch,omitempty"`
	TeslaKey      []byte                 `protobuf:"bytes,4,opt,name=tesla_key,json=teslaKey,proto3" json:"tesla_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorHeartbeat) Reset() {
	*x = ExecutorHeartbeat{}
	mi := &file_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorHeartbeat) ProtoMessage() {}

func (x *ExecutorHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorHeartbeat.ProtoReflect.Descriptor instead.
func (*ExecutorHeartbeat) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorHeartbeat) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ExecutorHeartbeat) GetTeslaKeyEpoch() int64 {
	if x != nil {
		return x.TeslaKeyEpoch
	}
	return 0
}

func (x *ExecutorHeartbeat) GetTeslaKey() []byte {
	if x != nil {
		return x.TeslaKey
	}
	return nil
}

type ExecutorResources struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BandwidthCapacity int64                  `protobuf:"varint,1,opt,name=bandwidth_capacity,json=bandwidthCapacity,proto3" json:"bandwidth_capacity,omitempty"` // Bandwidth capacity the executor can handle per second
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutorResources) Reset() {
	*x = ExecutorResources{}
	mi := &file_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorResources) ProtoMessage() {}

func (x *ExecutorResources) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorResources.ProtoReflect.Descriptor instead.
func (*ExecutorResources) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorResources) GetBandwidthCapacity() int64 {
	if x != nil {
		return x.BandwidthCapacity
	}
	return 0
}

type DebugletSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	Wasm          []byte                 `protobuf:"bytes,3,opt,name=wasm,proto3" json:"wasm,omitempty"`
	Policy        *DebugletSpec_Policy   `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletSpec) Reset() {
	*x = DebugletSpec{}
	mi := &file_protocol_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletSpec) ProtoMessage() {}

func (x *DebugletSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletSpec.ProtoReflect.Descriptor instead.
func (*DebugletSpec) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *DebugletSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DebugletSpec) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DebugletSpec) GetWasm() []byte {
	if x != nil {
		return x.Wasm
	}
	return nil
}

func (x *DebugletSpec) GetPolicy() *DebugletSpec_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// Executor -> Dispatcher
type ExecutorControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecutorControlMessage_Hello
	//	*ExecutorControlMessage_Heartbeat
	Msg           isExecutorControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorControlMessage) Reset() {
	*x = ExecutorControlMessage{}
	mi := &file_protocol_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorControlMessage) ProtoMessage() {}

func (x *ExecutorControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorControlMessage.ProtoReflect.Descriptor instead.
func (*ExecutorControlMessage) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutorControlMessage) GetMsg() isExecutorControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecutorControlMessage) GetHello() *ExecutorHello {
	if x != nil {
		if x, ok := x.Msg.(*ExecutorControlMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ExecutorControlMessage) GetHeartbeat() *ExecutorHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ExecutorControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isExecutorControlMessage_Msg interface {
	isExecutorControlMessage_Msg()
}

type ExecutorControlMessage_Hello struct {
	Hello *ExecutorHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ExecutorControlMessage_Heartbeat struct {
	Heartbeat *ExecutorHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*ExecutorControlMessage_Hello) isExecutorControlMessage_Msg() {}

func (*ExecutorControlMessage_Heartbeat) isExecutorControlMessage_Msg() {}

// Dispatcher -> Executor
type DispatcherControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DispatcherControlMessage_Upload
	Msg           isDispatcherControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatcherControlMessage) Reset() {
	*x = DispatcherControlMessage{}
	mi := &file_protocol_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatcherControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherControlMessage) ProtoMessage() {}

func (x *DispatcherControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherControlMessage.ProtoReflect.Descriptor instead.
func (*DispatcherControlMessage) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *DispatcherControlMessage) GetMsg() isDispatcherControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DispatcherControlMessage) GetUpload() *DebugletSpec {
	if x != nil {
		if x, ok := x.Msg.(*DispatcherControlMessage_Upload); ok {
			return x.Upload
		}
	}
	return nil
}

type isDispatcherControlMessage_Msg interface {
	isDispatcherControlMessage_Msg()
}

type DispatcherControlMessage_Upload struct {
	Upload *DebugletSpec `protobuf:"bytes,1,opt,name=upload,proto3,oneof"`
}

func (*DispatcherControlMessage_Upload) isDispatcherControlMessage_Msg() {}

type DebugletSpec_Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FloorBw       int64                  `protobuf:"varint,1,opt,name=floor_bw,json=floorBw,proto3" json:"floor_bw,omitempty"`       // min bits/s required
	CeilBw        int64                  `protobuf:"varint,2,opt,name=ceil_bw,json=ceilBw,proto3" json:"ceil_bw,omitempty"`          // max bits/s it could use
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // timeout in ms
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`                   // e.g., SCION or network endpoints
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugletSpec_Policy) Reset() {
	*x = DebugletSpec_Policy{}
	mi := &file_protocol_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugletSpec_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugletSpec_Policy) ProtoMessage() {}

func (x *DebugletSpec_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugletSpec_Policy.ProtoReflect.Descriptor instead.
func (*DebugletSpec_Policy) Descriptor() ([]byte, []int) {
	return file_protocol_protocol_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DebugletSpec_Policy) GetFloorBw() int64 {
	if x != nil {
		return x.FloorBw
	}
	return 0
}

func (x *DebugletSpec_Policy) GetCeilBw() int64 {
	if x != nil {
		return x.CeilBw
	}
	return 0
}

func (x *DebugletSpec_Policy) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DebugletSpec_Policy) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_protocol_protocol_proto protoreflect.FileDescriptor

const file_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/protocol.proto\x12\x11debuglet.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n" +
	"\rExecutorHello\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12&\n" +
	"\x0ftesla_delay_sec\x18\x04 \x01(\x03R\rteslaDelaySec\x129\n" +
	"\x19tesla_anchor_timestamp_ns\x18\x05 \x01(\x03R\x16teslaAnchorTimestampNs\x12(\n" +
	"\x10tesla_anchor_key\x18\x06 \x01(\fR\x0eteslaAnchorKey\"{\n" +
	"\x11ExecutorHeartbeat\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12&\n" +
	"\x0ftesla_key_epoch\x18\x03 \x01(\x03R\rteslaKeyEpoch\x12\x1b\n" +
	"\ttesla_key\x18\x04 \x01(\fR\bteslaKey\"B\n" +
	"\x11ExecutorResources\x12-\n" +
	"\x12bandwidth_capacity\x18\x01 \x01(\x03R\x11bandwidthCapacity\"\xbc\x02\n" +
	"\fDebugletSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12\x12\n" +
	"\x04wasm\x18\x03 \x01(\fR\x04wasm\x12>\n" +
	"\x06policy\x18\x05 \x01(\v2&.debuglet.protocol.DebugletSpec.PolicyR\x06policy\x1ay\n" +
	"\x06Policy\x12\x19\n" +
	"\bfloor_bw\x18\x01 \x01(\x03R\afloorBw\x12\x17\n" +
	"\aceil_bw\x18\x02 \x01(\x03R\x06ceilBw\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddressesB\r\n" +
	"\v_start_time\"\x9f\x01\n" +
	"\x16ExecutorControlMessage\x128\n" +
	"\x05hello\x18\x01 \x01(\v2 .debuglet.protocol.ExecutorHelloH\x00R\x05hello\x12D\n" +
	"\theartbeat\x18\x02 \x01(\v2$.debuglet.protocol.ExecutorHeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"\\\n" +
	"\x18DispatcherControlMessage\x129\n" +
	"\x06upload\x18\x01 \x01(\v2\x1f.debuglet.protocol.DebugletSpecH\x00R\x06uploadB\x05\n" +
	"\x03msg2\x80\x01\n" +
	"\x11DispatcherService\x12k\n" +
	"\rControlStream\x12).debuglet.protocol.ExecutorControlMessage\x1a+.debuglet.protocol.DispatcherControlMessage(\x010\x01B\vZ\t/protocolb\x06proto3"

var (
	file_protocol_protocol_proto_rawDescOnce sync.Once
	file_protocol_protocol_proto_rawDescData []byte
)

func file_protocol_protocol_proto_rawDescGZIP() []byte {
	file_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)))
	})
	return file_protocol_protocol_proto_rawDescData
}

var file_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocol_protocol_proto_goTypes = []any{
	(*ExecutorHello)(nil),            // 0: debuglet.protocol.ExecutorHello
	(*ExecutorHeartbeat)(nil),        // 1: debuglet.protocol.ExecutorHeartbeat
	(*ExecutorResources)(nil),        // 2: debuglet.protocol.ExecutorResources
	(*DebugletSpec)(nil),             // 3: debuglet.protocol.DebugletSpec
	(*ExecutorControlMessage)(nil),   // 4: debuglet.protocol.ExecutorControlMessage
	(*DispatcherControlMessage)(nil), // 5: debuglet.protocol.DispatcherControlMessage
	(*DebugletSpec_Policy)(nil),      // 6: debuglet.protocol.DebugletSpec.Policy
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_protocol_protocol_proto_depIdxs = []int32{
	7, // 0: debuglet.protocol.DebugletSpec.start_time:type_name -> google.protobuf.Timestamp
	6, // 1: debuglet.protocol.DebugletSpec.policy:type_name -> debuglet.protocol.DebugletSpec.Policy
	0, // 2: debuglet.protocol.ExecutorControlMessage.hello:type_name -> debuglet.protocol.ExecutorHello
	1, // 3: debuglet.protocol.ExecutorControlMessage.heartbeat:type_name -> debuglet.protocol.ExecutorHeartbeat
	3, // 4: debuglet.protocol.DispatcherControlMessage.upload:type_name -> debuglet.protocol.DebugletSpec
	4, // 5: debuglet.protocol.DispatcherService.ControlStream:input_type -> debuglet.protocol.ExecutorControlMessage
	5, // 6: debuglet.protocol.DispatcherService.ControlStream:output_type -> debuglet.protocol.DispatcherControlMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_protocol_proto_init() }
func file_protocol_protocol_proto_init() {
	if File_protocol_protocol_proto != nil {
		return
	}
	file_protocol_protocol_proto_msgTypes[3].OneofWrappers = []any{}
	file_protocol_protocol_proto_msgTypes[4].OneofWrappers = []any{
		(*ExecutorControlMessage_Hello)(nil),
		(*ExecutorControlMessage_Heartbeat)(nil),
	}
	file_protocol_protocol_proto_msgTypes[5].OneofWrappers = []any{
		(*DispatcherControlMessage_Upload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protocol_proto_rawDesc), len(file_protocol_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_protocol_proto_msgTypes,
	}.Build()
	File_protocol_protocol_proto = out.File
	file_protocol_protocol_proto_goTypes = nil
	file_protocol_protocol_proto_depIdxs = nil
}
