// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package edb

import (
	"time"

	"debuglet/internal/executor/scheduler/sqlite/models"
)

type Debuglet struct {
	ID            string
	StartTime     models.UTCTime
	Args          models.CommaSeparatedList
	Wasm          []byte
	TransactionID string
	FloorBw       int64
	CeilBw        int64
	TimeoutMs     int64
	Addresses     models.CommaSeparatedList
	RequireIcmp   bool
	ListenUdp     bool
	ListenTcp     bool
	ListenIcmp    bool
	ListenScion   bool
	StartedAt     models.UTCTime
}

type DebugletLog struct {
	ID         int64
	DebugletID string
	Timestamp  time.Time
	Output     []byte
}
