// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_recovery.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const consumeAdminAccountRecovery = `-- name: ConsumeAdminAccountRecovery :exec
UPDATE account_recovery_audit SET consumed_at = unixepoch() WHERE selector = ?
`

func (q *Queries) ConsumeAdminAccountRecovery(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, consumeAdminAccountRecovery, selector)
	return err
}

const deleteAdminRecoveryCredential = `-- name: DeleteAdminRecoveryCredential :exec
DELETE FROM user_credentials WHERE kind = 'recovery' AND selector = ?
`

func (q *Queries) DeleteAdminRecoveryCredential(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminRecoveryCredential, selector)
	return err
}

const getUnmappedAccountForRecovery = `-- name: GetUnmappedAccountForRecovery :one
SELECT users.id, users.uuid, users.name, users.role FROM users WHERE uuid = ?
  AND NOT EXISTS (SELECT 1 FROM user_credentials WHERE user_id = users.id)
  AND NOT EXISTS (SELECT 1 FROM oauth_identities WHERE user_id = users.id)
  AND NOT EXISTS (SELECT 1 FROM account_recovery_audit WHERE user_id = users.id
                  AND consumed_at = 0 AND revoked_at = 0)
`

func (q *Queries) GetUnmappedAccountForRecovery(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUnmappedAccountForRecovery, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const lockAccountForRecovery = `-- name: LockAccountForRecovery :execrows
UPDATE users SET name = name WHERE uuid = ?
`

func (q *Queries) LockAccountForRecovery(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockAccountForRecovery, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordAdminAccountRecovery = `-- name: RecordAdminAccountRecovery :exec
INSERT INTO account_recovery_audit (selector, user_id, case_reference, issued_by_uid, issued_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordAdminAccountRecoveryParams struct {
	Selector      string
	UserID        int64
	CaseReference string
	IssuedByUid   int64
	IssuedAt      int64
	ExpiresAt     int64
}

func (q *Queries) RecordAdminAccountRecovery(ctx context.Context, arg RecordAdminAccountRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, recordAdminAccountRecovery,
		arg.Selector,
		arg.UserID,
		arg.CaseReference,
		arg.IssuedByUid,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const revokeAdminAccountRecovery = `-- name: RevokeAdminAccountRecovery :one
UPDATE account_recovery_audit SET revoked_at = unixepoch(), revoked_by_uid = ?, revocation_reference = ?
WHERE user_id = (SELECT id FROM users WHERE uuid = ?) AND consumed_at = 0 AND revoked_at = 0
RETURNING selector
`

type RevokeAdminAccountRecoveryParams struct {
	RevokedByUid        sql.NullInt64
	RevocationReference string
	Uuid                uuid.UUID
}

func (q *Queries) RevokeAdminAccountRecovery(ctx context.Context, arg RevokeAdminAccountRecoveryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, revokeAdminAccountRecovery, arg.RevokedByUid, arg.RevocationReference, arg.Uuid)
	var selector string
	err := row.Scan(&selector)
	return selector, err
}
