// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_limits.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const createPayloadTombstone = `-- name: CreatePayloadTombstone :exec
INSERT INTO payload_tombstones(debuglet_id, deleted_at, reason, workload_sha256, certificate_sha256)
SELECT d.id, ?1, ?2,
       json_extract(p.document, '$.workload_sha256'), json_extract(p.document, '$.certificate_sha256')
FROM debuglets d LEFT JOIN debuglet_provenance p ON p.debuglet_id = d.id
WHERE d.id = ?3
`

type CreatePayloadTombstoneParams struct {
	DeletedAt  int64
	Reason     string
	DebugletID int64
}

func (q *Queries) CreatePayloadTombstone(ctx context.Context, arg CreatePayloadTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, createPayloadTombstone, arg.DeletedAt, arg.Reason, arg.DebugletID)
	return err
}

const deleteMeasurementLogs = `-- name: DeleteMeasurementLogs :exec
DELETE FROM debuglet_logs WHERE debuglet_id = ?
`

func (q *Queries) DeleteMeasurementLogs(ctx context.Context, debugletID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeasurementLogs, debugletID)
	return err
}

const deleteMeasurementProvenance = `-- name: DeleteMeasurementProvenance :exec
DELETE FROM debuglet_provenance WHERE debuglet_id = ?
`

func (q *Queries) DeleteMeasurementProvenance(ctx context.Context, debugletID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeasurementProvenance, debugletID)
	return err
}

const deleteMeasurementTargets = `-- name: DeleteMeasurementTargets :exec
UPDATE debuglets SET addresses = NULL, error = ?1 WHERE id = ?2
`

type DeleteMeasurementTargetsParams struct {
	PublicError sql.NullString
	DebugletID  int64
}

func (q *Queries) DeleteMeasurementTargets(ctx context.Context, arg DeleteMeasurementTargetsParams) error {
	_, err := q.db.ExecContext(ctx, deleteMeasurementTargets, arg.PublicError, arg.DebugletID)
	return err
}

const getAccountRunReservation = `-- name: GetAccountRunReservation :one
SELECT debuglet_id, account_id, queued_bytes, retired_at, last_retirement_check FROM account_run_reservations WHERE debuglet_id = ?
`

func (q *Queries) GetAccountRunReservation(ctx context.Context, debugletID int64) (AccountRunReservation, error) {
	row := q.db.QueryRowContext(ctx, getAccountRunReservation, debugletID)
	var i AccountRunReservation
	err := row.Scan(
		&i.DebugletID,
		&i.AccountID,
		&i.QueuedBytes,
		&i.RetiredAt,
		&i.LastRetirementCheck,
	)
	return i, err
}

const getPayloadTombstone = `-- name: GetPayloadTombstone :one
SELECT t.debuglet_id, t.deleted_at, t.reason, t.workload_sha256, t.certificate_sha256 FROM payload_tombstones t JOIN debuglets d ON d.id = t.debuglet_id
WHERE d.uuid = ?
`

func (q *Queries) GetPayloadTombstone(ctx context.Context, argUuid uuid.UUID) (PayloadTombstone, error) {
	row := q.db.QueryRowContext(ctx, getPayloadTombstone, argUuid)
	var i PayloadTombstone
	err := row.Scan(
		&i.DebugletID,
		&i.DeletedAt,
		&i.Reason,
		&i.WorkloadSha256,
		&i.CertificateSha256,
	)
	return i, err
}

const listAccountReservations = `-- name: ListAccountReservations :many
SELECT r.debuglet_id, r.queued_bytes, d.start_time, d.end_time
FROM account_run_reservations r JOIN debuglets d ON d.id = r.debuglet_id
WHERE r.account_id = ? AND r.retired_at IS NULL LIMIT 100001
`

type ListAccountReservationsRow struct {
	DebugletID  int64
	QueuedBytes int64
	StartTime   models.UTCTime
	EndTime     models.UTCTime
}

func (q *Queries) ListAccountReservations(ctx context.Context, accountID int64) ([]ListAccountReservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountReservations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountReservationsRow
	for rows.Next() {
		var i ListAccountReservationsRow
		if err := rows.Scan(
			&i.DebugletID,
			&i.QueuedBytes,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPayloads = `-- name: ListExpiredPayloads :many
SELECT d.uuid FROM debuglets d
JOIN account_run_reservations r ON r.debuglet_id = d.id
JOIN debuglet_output o ON o.debuglet_id = d.id
LEFT JOIN payload_tombstones t ON t.debuglet_id = d.id
WHERE r.retired_at < ?1 AND d.state = 5
  AND o.final_sequence IS NOT NULL AND t.debuglet_id IS NULL
ORDER BY r.retired_at LIMIT 100
`

func (q *Queries) ListExpiredPayloads(ctx context.Context, before sql.NullInt64) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPayloads, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetirementCandidates = `-- name: ListRetirementCandidates :many
SELECT d.uuid FROM account_run_reservations r JOIN debuglets d ON d.id = r.debuglet_id
WHERE r.retired_at IS NULL AND d.state = 5
ORDER BY r.last_retirement_check, d.id LIMIT 4
`

func (q *Queries) ListRetirementCandidates(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listRetirementCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRetirementCheck = `-- name: MarkRetirementCheck :exec
UPDATE account_run_reservations SET last_retirement_check = ? WHERE debuglet_id = ?
`

type MarkRetirementCheckParams struct {
	LastRetirementCheck int64
	DebugletID          int64
}

func (q *Queries) MarkRetirementCheck(ctx context.Context, arg MarkRetirementCheckParams) error {
	_, err := q.db.ExecContext(ctx, markRetirementCheck, arg.LastRetirementCheck, arg.DebugletID)
	return err
}

const reserveAccountRun = `-- name: ReserveAccountRun :exec
INSERT INTO account_run_reservations(debuglet_id, account_id, queued_bytes)
VALUES (?, ?, ?)
`

type ReserveAccountRunParams struct {
	DebugletID  int64
	AccountID   int64
	QueuedBytes int64
}

func (q *Queries) ReserveAccountRun(ctx context.Context, arg ReserveAccountRunParams) error {
	_, err := q.db.ExecContext(ctx, reserveAccountRun, arg.DebugletID, arg.AccountID, arg.QueuedBytes)
	return err
}

const retireAccountRun = `-- name: RetireAccountRun :execrows
UPDATE account_run_reservations SET retired_at = ?
WHERE debuglet_id = ? AND retired_at IS NULL
`

type RetireAccountRunParams struct {
	RetiredAt  sql.NullInt64
	DebugletID int64
}

func (q *Queries) RetireAccountRun(ctx context.Context, arg RetireAccountRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireAccountRun, arg.RetiredAt, arg.DebugletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
