// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocation_reclamations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const getAllocationReclamation = `-- name: GetAllocationReclamation :one
SELECT r.reclaimed_at FROM allocation_reclamations r JOIN debuglets d ON d.id = r.debuglet_id
WHERE d.uuid = ?
`

func (q *Queries) GetAllocationReclamation(ctx context.Context, argUuid uuid.UUID) (models.UTCTime, error) {
	row := q.db.QueryRowContext(ctx, getAllocationReclamation, argUuid)
	var reclaimed_at models.UTCTime
	err := row.Scan(&reclaimed_at)
	return reclaimed_at, err
}

const getReclaimedDebuglet = `-- name: GetReclaimedDebuglet :one
SELECT d.id, d.uuid, d.start_time, d.end_time, d.usage, d.ceil_bw, d.executor_id, d.addresses, d.state, d.error, d.transaction_id, d.order_id, d.dispatcher_incarnation, d.session_id FROM debuglets d JOIN allocation_reclamations r ON r.debuglet_id = d.id
WHERE d.uuid = ?
`

func (q *Queries) GetReclaimedDebuglet(ctx context.Context, argUuid uuid.UUID) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, getReclaimedDebuglet, argUuid)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.CeilBw,
		&i.ExecutorID,
		&i.Addresses,
		&i.State,
		&i.Error,
		&i.TransactionID,
		&i.OrderID,
		&i.DispatcherIncarnation,
		&i.SessionID,
	)
	return i, err
}

const listUnreclaimedAllocations = `-- name: ListUnreclaimedAllocations :many
SELECT d.id, d.uuid, d.start_time, d.end_time, d.usage, d.ceil_bw, d.executor_id, d.addresses, d.state, d.error, d.transaction_id, d.order_id, d.dispatcher_incarnation, d.session_id FROM debuglets d
WHERE d.state <> ?1 AND d.end_time < ?2
  AND d.dispatcher_incarnation <> '' AND d.session_id <> ''
  AND NOT EXISTS (SELECT 1 FROM allocation_reclamations r WHERE r.debuglet_id = d.id)
ORDER BY d.end_time, d.id LIMIT 100
`

type ListUnreclaimedAllocationsParams struct {
	ExitedState models.DebugletRunState
	EndTime     models.UTCTime
}

func (q *Queries) ListUnreclaimedAllocations(ctx context.Context, arg ListUnreclaimedAllocationsParams) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listUnreclaimedAllocations, arg.ExitedState, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.CeilBw,
			&i.ExecutorID,
			&i.Addresses,
			&i.State,
			&i.Error,
			&i.TransactionID,
			&i.OrderID,
			&i.DispatcherIncarnation,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimAllocation = `-- name: ReclaimAllocation :exec
INSERT INTO allocation_reclamations (debuglet_id, reclaimed_at)
SELECT id, ?1 FROM debuglets
WHERE uuid = ?2 AND state <> ?3
  AND executor_id = ?4
  AND dispatcher_incarnation = ?5
  AND session_id = ?6
  AND dispatcher_incarnation <> '' AND session_id <> ''
ON CONFLICT (debuglet_id) DO NOTHING
`

type ReclaimAllocationParams struct {
	ReclaimedAt           models.UTCTime
	Uuid                  uuid.UUID
	ExitedState           models.DebugletRunState
	ExecutorID            string
	DispatcherIncarnation string
	SessionID             string
}

func (q *Queries) ReclaimAllocation(ctx context.Context, arg ReclaimAllocationParams) error {
	_, err := q.db.ExecContext(ctx, reclaimAllocation,
		arg.ReclaimedAt,
		arg.Uuid,
		arg.ExitedState,
		arg.ExecutorID,
		arg.DispatcherIncarnation,
		arg.SessionID,
	)
	return err
}
