// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allowances.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const getAllowance = `-- name: GetAllowance :one
SELECT
  CAST(COALESCE((SELECT SUM(g.amount) FROM allowance_grants g WHERE g.user_id = u.id), 0) AS INTEGER) AS granted,
  CAST(COALESCE((SELECT SUM(o.price) FROM debuglet_order o
    JOIN transaction_users tu ON tu.transaction_id = o.transaction_id
    JOIN transactions t ON t.id = o.transaction_id
    WHERE tu.user_id = u.id AND t.method = 'TEST'
      AND EXISTS (SELECT 1 FROM order_settlements s
        WHERE s.transaction_id = o.transaction_id AND s.order_id = o.order_id)), 0) AS INTEGER) AS consumed,
  CAST(COALESCE((SELECT SUM(o.price) FROM debuglet_order o
    JOIN transaction_users tu ON tu.transaction_id = o.transaction_id
    JOIN transactions t ON t.id = o.transaction_id
    WHERE tu.user_id = u.id AND t.method = 'TEST' AND t.status = ?1
      AND NOT EXISTS (SELECT 1 FROM order_settlements s
        WHERE s.transaction_id = o.transaction_id AND s.order_id = o.order_id)), 0) AS INTEGER) AS reserved
FROM users u
WHERE u.uuid = ?2
`

type GetAllowanceParams struct {
	PaidStatus int64
	UserUuid   uuid.UUID
}

type GetAllowanceRow struct {
	Granted  int64
	Consumed int64
	Reserved int64
}

// The allowance of an account in TEST units: the sum of its grants; consumed,
// the price of its TEST orders that have a settlement, whichever way it went;
// and reserved, the price of the other orders of its paid TEST intents.
func (q *Queries) GetAllowance(ctx context.Context, arg GetAllowanceParams) (GetAllowanceRow, error) {
	row := q.db.QueryRowContext(ctx, getAllowance, arg.PaidStatus, arg.UserUuid)
	var i GetAllowanceRow
	err := row.Scan(&i.Granted, &i.Consumed, &i.Reserved)
	return i, err
}

const getAllowanceGrant = `-- name: GetAllowanceGrant :one
SELECT g.id, g.amount, g.currency, g.reason, g.idempotency_key, g.granted_at, o.uuid AS granted_by
FROM allowance_grants g
JOIN users u ON u.id = g.user_id
JOIN users o ON o.id = g.granted_by
WHERE u.uuid = ?1 AND g.idempotency_key = ?2
`

type GetAllowanceGrantParams struct {
	UserUuid       uuid.UUID
	IdempotencyKey string
}

type GetAllowanceGrantRow struct {
	ID             int64
	Amount         int64
	Currency       string
	Reason         string
	IdempotencyKey string
	GrantedAt      models.UTCTime
	GrantedBy      uuid.UUID
}

func (q *Queries) GetAllowanceGrant(ctx context.Context, arg GetAllowanceGrantParams) (GetAllowanceGrantRow, error) {
	row := q.db.QueryRowContext(ctx, getAllowanceGrant, arg.UserUuid, arg.IdempotencyKey)
	var i GetAllowanceGrantRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.IdempotencyKey,
		&i.GrantedAt,
		&i.GrantedBy,
	)
	return i, err
}

const insertAllowanceGrant = `-- name: InsertAllowanceGrant :execrows
INSERT INTO allowance_grants (user_id, amount, currency, granted_by, reason, idempotency_key, granted_at)
SELECT u.id, ?1, 'TEST', o.id, ?2, ?3, ?4
FROM users u
JOIN users o ON o.uuid = ?5
WHERE u.uuid = ?6
`

type InsertAllowanceGrantParams struct {
	Amount         int64
	Reason         string
	IdempotencyKey string
	GrantedAt      models.UTCTime
	GrantedBy      uuid.UUID
	UserUuid       uuid.UUID
}

func (q *Queries) InsertAllowanceGrant(ctx context.Context, arg InsertAllowanceGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAllowanceGrant,
		arg.Amount,
		arg.Reason,
		arg.IdempotencyKey,
		arg.GrantedAt,
		arg.GrantedBy,
		arg.UserUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExecutorTransfers = `-- name: ListExecutorTransfers :many
SELECT id, kind, amount, currency, receiver, state, digest, created_at, updated_at
FROM chain_transfers
WHERE executor_id = ?1
ORDER BY id DESC
LIMIT ?2
`

type ListExecutorTransfersParams struct {
	ExecutorID string
	RowLimit   int64
}

type ListExecutorTransfersRow struct {
	ID        int64
	Kind      string
	Amount    int64
	Currency  string
	Receiver  string
	State     string
	Digest    string
	CreatedAt models.UTCTime
	UpdatedAt models.UTCTime
}

// The newest outbound chain transfers that name an executor.
func (q *Queries) ListExecutorTransfers(ctx context.Context, arg ListExecutorTransfersParams) ([]ListExecutorTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, listExecutorTransfers, arg.ExecutorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutorTransfersRow
	for rows.Next() {
		var i ListExecutorTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Amount,
			&i.Currency,
			&i.Receiver,
			&i.State,
			&i.Digest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExpiredAllowanceIntents = `-- name: ReleaseExpiredAllowanceIntents :execrows
UPDATE transactions
SET status = ?1
WHERE status = ?2 AND method = 'TEST' AND expires_at < ?3
  AND id IN (SELECT tu.transaction_id FROM transaction_users tu
    JOIN users u ON u.id = tu.user_id WHERE u.uuid = ?4)
  AND NOT EXISTS (
    SELECT 1 FROM debuglet_order
    WHERE debuglet_order.transaction_id = transactions.id AND debuglet_id IS NOT NULL
  )
`

type ReleaseExpiredAllowanceIntentsParams struct {
	ExpiredStatus int64
	PaidStatus    int64
	Now           models.UTCTime
	UserUuid      uuid.UUID
}

// Expires the account's paid TEST intents past their expiry that admitted no
// run. Admission claims an order only while its transaction is paid, so an
// intent is either released here or admitted, never both.
func (q *Queries) ReleaseExpiredAllowanceIntents(ctx context.Context, arg ReleaseExpiredAllowanceIntentsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseExpiredAllowanceIntents,
		arg.ExpiredStatus,
		arg.PaidStatus,
		arg.Now,
		arg.UserUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveAllowanceIntent = `-- name: ReserveAllowanceIntent :execrows
INSERT INTO transactions (id, auth_key, price, currency, method, expires_at, status, hash)
SELECT ?1, '', ?2, 'TEST', 'TEST', ?3, ?4, ?5
FROM users u
WHERE u.uuid = ?6
  AND COALESCE((SELECT SUM(g.amount) FROM allowance_grants g WHERE g.user_id = u.id), 0)
    - COALESCE((SELECT SUM(o.price) FROM debuglet_order o
      JOIN transaction_users tu ON tu.transaction_id = o.transaction_id
      JOIN transactions t ON t.id = o.transaction_id
      WHERE tu.user_id = u.id AND t.method = 'TEST'
        AND (t.status = ?4 OR EXISTS (SELECT 1 FROM order_settlements s
          WHERE s.transaction_id = o.transaction_id AND s.order_id = o.order_id))), 0)
    >= ?2
`

type ReserveAllowanceIntentParams struct {
	ID         string
	Price      int64
	ExpiresAt  models.UTCTime
	PaidStatus int64
	Hash       string
	UserUuid   uuid.UUID
}

// Creates a paid TEST transaction for the account only if its remaining
// allowance, computed as GetAllowance does, covers price. The check and the
// insert are one statement, so two intents cannot both spend the same rest.
func (q *Queries) ReserveAllowanceIntent(ctx context.Context, arg ReserveAllowanceIntentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveAllowanceIntent,
		arg.ID,
		arg.Price,
		arg.ExpiresAt,
		arg.PaidStatus,
		arg.Hash,
		arg.UserUuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
