// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const advanceAttributionRetention = `-- name: AdvanceAttributionRetention :exec
UPDATE attribution_retention SET retained_from_ns = MAX(retained_from_ns, CAST(?1 AS INTEGER))
WHERE singleton = 1
`

func (q *Queries) AdvanceAttributionRetention(ctx context.Context, cutoffNs int64) error {
	_, err := q.db.ExecContext(ctx, advanceAttributionRetention, cutoffNs)
	return err
}

const endAttributionRun = `-- name: EndAttributionRun :exec
UPDATE attribution_runs
SET active_to_ns = MAX(active_from_ns, MIN(active_to_ns, CAST(?1 AS INTEGER)))
WHERE debuglet_id = (SELECT id FROM debuglets WHERE uuid = ?2)
`

type EndAttributionRunParams struct {
	EndedNs int64
	Uuid    uuid.UUID
}

func (q *Queries) EndAttributionRun(ctx context.Context, arg EndAttributionRunParams) error {
	_, err := q.db.ExecContext(ctx, endAttributionRun, arg.EndedNs, arg.Uuid)
	return err
}

const getAttributionChain = `-- name: GetAttributionChain :one
SELECT executor_id, chain_id, anchor, t0_ns, interval_ns, delay_epochs, chain_length, tag_spec, first_seen_ns, last_seen_ns FROM attribution_chains WHERE executor_id = ? AND chain_id = ?
`

type GetAttributionChainParams struct {
	ExecutorID string
	ChainID    string
}

func (q *Queries) GetAttributionChain(ctx context.Context, arg GetAttributionChainParams) (AttributionChain, error) {
	row := q.db.QueryRowContext(ctx, getAttributionChain, arg.ExecutorID, arg.ChainID)
	var i AttributionChain
	err := row.Scan(
		&i.ExecutorID,
		&i.ChainID,
		&i.Anchor,
		&i.T0Ns,
		&i.IntervalNs,
		&i.DelayEpochs,
		&i.ChainLength,
		&i.TagSpec,
		&i.FirstSeenNs,
		&i.LastSeenNs,
	)
	return i, err
}

const getAttributionKey = `-- name: GetAttributionKey :one
SELECT key FROM attribution_keys WHERE executor_id = ? AND chain_id = ? AND epoch = ?
`

type GetAttributionKeyParams struct {
	ExecutorID string
	ChainID    string
	Epoch      int64
}

func (q *Queries) GetAttributionKey(ctx context.Context, arg GetAttributionKeyParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getAttributionKey, arg.ExecutorID, arg.ChainID, arg.Epoch)
	var key []byte
	err := row.Scan(&key)
	return key, err
}

const getAttributionRetention = `-- name: GetAttributionRetention :one
SELECT retained_from_ns FROM attribution_retention WHERE singleton = 1
`

func (q *Queries) GetAttributionRetention(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAttributionRetention)
	var retained_from_ns int64
	err := row.Scan(&retained_from_ns)
	return retained_from_ns, err
}

const insertAttributionKey = `-- name: InsertAttributionKey :exec
INSERT INTO attribution_keys (executor_id, chain_id, epoch, key, disclosed_at_ns)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (executor_id, chain_id, epoch) DO NOTHING
`

type InsertAttributionKeyParams struct {
	ExecutorID    string
	ChainID       string
	Epoch         int64
	Key           []byte
	DisclosedAtNs int64
}

func (q *Queries) InsertAttributionKey(ctx context.Context, arg InsertAttributionKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAttributionKey,
		arg.ExecutorID,
		arg.ChainID,
		arg.Epoch,
		arg.Key,
		arg.DisclosedAtNs,
	)
	return err
}

const latestAttributionKey = `-- name: LatestAttributionKey :one
SELECT epoch, key FROM attribution_keys
WHERE executor_id = ? AND chain_id = ?
ORDER BY epoch DESC LIMIT 1
`

type LatestAttributionKeyParams struct {
	ExecutorID string
	ChainID    string
}

type LatestAttributionKeyRow struct {
	Epoch int64
	Key   []byte
}

func (q *Queries) LatestAttributionKey(ctx context.Context, arg LatestAttributionKeyParams) (LatestAttributionKeyRow, error) {
	row := q.db.QueryRowContext(ctx, latestAttributionKey, arg.ExecutorID, arg.ChainID)
	var i LatestAttributionKeyRow
	err := row.Scan(&i.Epoch, &i.Key)
	return i, err
}

const listAttributionCandidates = `-- name: ListAttributionCandidates :many
SELECT d.uuid, d.executor_id, r.source_ip_observed, r.active_from_ns, r.active_to_ns,
       c.chain_id, c.anchor, c.t0_ns, c.interval_ns, c.delay_epochs, c.chain_length, c.tag_spec,
       CAST(COALESCE((SELECT MAX(k.epoch) FROM attribution_keys k
                      WHERE k.executor_id = c.executor_id AND k.chain_id = c.chain_id), 0) AS INTEGER) AS disclosed_through
FROM attribution_runs r
JOIN debuglets d ON d.id = r.debuglet_id
JOIN attribution_chains c ON c.executor_id = d.executor_id AND c.chain_id = r.chain_id
WHERE r.source_ip = ?1
  AND r.active_from_ns <= ?2 + c.interval_ns
  AND r.active_to_ns >= ?2 - c.interval_ns
ORDER BY r.active_from_ns, d.uuid
LIMIT ?3
`

type ListAttributionCandidatesParams struct {
	SourceIp string
	AtNs     int64
	MaxRows  int64
}

type ListAttributionCandidatesRow struct {
	Uuid             uuid.UUID
	ExecutorID       string
	SourceIpObserved int64
	ActiveFromNs     int64
	ActiveToNs       int64
	ChainID          string
	Anchor           []byte
	T0Ns             int64
	IntervalNs       int64
	DelayEpochs      int64
	ChainLength      int64
	TagSpec          int64
	DisclosedThrough int64
}

func (q *Queries) ListAttributionCandidates(ctx context.Context, arg ListAttributionCandidatesParams) ([]ListAttributionCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributionCandidates, arg.SourceIp, arg.AtNs, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributionCandidatesRow
	for rows.Next() {
		var i ListAttributionCandidatesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ExecutorID,
			&i.SourceIpObserved,
			&i.ActiveFromNs,
			&i.ActiveToNs,
			&i.ChainID,
			&i.Anchor,
			&i.T0Ns,
			&i.IntervalNs,
			&i.DelayEpochs,
			&i.ChainLength,
			&i.TagSpec,
			&i.DisclosedThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributionKeys = `-- name: ListAttributionKeys :many
SELECT epoch, key FROM attribution_keys
WHERE executor_id = ?1 AND chain_id = ?2
  AND epoch >= ?3 AND epoch <= ?4
ORDER BY epoch
`

type ListAttributionKeysParams struct {
	ExecutorID string
	ChainID    string
	FromEpoch  int64
	ToEpoch    int64
}

type ListAttributionKeysRow struct {
	Epoch int64
	Key   []byte
}

func (q *Queries) ListAttributionKeys(ctx context.Context, arg ListAttributionKeysParams) ([]ListAttributionKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributionKeys,
		arg.ExecutorID,
		arg.ChainID,
		arg.FromEpoch,
		arg.ToEpoch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributionKeysRow
	for rows.Next() {
		var i ListAttributionKeysRow
		if err := rows.Scan(&i.Epoch, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAttributionChains = `-- name: PruneAttributionChains :execrows
DELETE FROM attribution_chains
WHERE last_seen_ns < ?1
  AND NOT EXISTS (SELECT 1 FROM attribution_keys k
                  WHERE k.executor_id = attribution_chains.executor_id AND k.chain_id = attribution_chains.chain_id)
  AND NOT EXISTS (SELECT 1 FROM attribution_runs r JOIN debuglets d ON d.id = r.debuglet_id
                  WHERE d.executor_id = attribution_chains.executor_id AND r.chain_id = attribution_chains.chain_id)
`

func (q *Queries) PruneAttributionChains(ctx context.Context, cutoffNs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAttributionChains, cutoffNs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneAttributionKeys = `-- name: PruneAttributionKeys :execrows
DELETE FROM attribution_keys
WHERE EXISTS (
    SELECT 1 FROM attribution_chains c
    WHERE c.executor_id = attribution_keys.executor_id AND c.chain_id = attribution_keys.chain_id
      AND c.interval_ns > 0 AND c.t0_ns + (attribution_keys.epoch + 1) * c.interval_ns < ?1
)
`

func (q *Queries) PruneAttributionKeys(ctx context.Context, cutoffNs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAttributionKeys, cutoffNs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneAttributionRuns = `-- name: PruneAttributionRuns :execrows
DELETE FROM attribution_runs WHERE active_to_ns < ?1
`

func (q *Queries) PruneAttributionRuns(ctx context.Context, cutoffNs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAttributionRuns, cutoffNs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordAttributionChain = `-- name: RecordAttributionChain :exec
INSERT INTO attribution_chains (executor_id, chain_id, anchor, t0_ns, interval_ns, delay_epochs, chain_length, tag_spec, first_seen_ns, last_seen_ns)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?9)
ON CONFLICT (executor_id, chain_id) DO UPDATE SET last_seen_ns = MAX(last_seen_ns, excluded.last_seen_ns)
`

type RecordAttributionChainParams struct {
	ExecutorID  string
	ChainID     string
	Anchor      []byte
	T0Ns        int64
	IntervalNs  int64
	DelayEpochs int64
	ChainLength int64
	TagSpec     int64
	SeenNs      int64
}

func (q *Queries) RecordAttributionChain(ctx context.Context, arg RecordAttributionChainParams) error {
	_, err := q.db.ExecContext(ctx, recordAttributionChain,
		arg.ExecutorID,
		arg.ChainID,
		arg.Anchor,
		arg.T0Ns,
		arg.IntervalNs,
		arg.DelayEpochs,
		arg.ChainLength,
		arg.TagSpec,
		arg.SeenNs,
	)
	return err
}

const recordAttributionRun = `-- name: RecordAttributionRun :exec
INSERT INTO attribution_runs (debuglet_id, chain_id, source_ip, source_ip_observed, active_from_ns, active_to_ns)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordAttributionRunParams struct {
	DebugletID       int64
	ChainID          string
	SourceIp         string
	SourceIpObserved int64
	ActiveFromNs     int64
	ActiveToNs       int64
}

func (q *Queries) RecordAttributionRun(ctx context.Context, arg RecordAttributionRunParams) error {
	_, err := q.db.ExecContext(ctx, recordAttributionRun,
		arg.DebugletID,
		arg.ChainID,
		arg.SourceIp,
		arg.SourceIpObserved,
		arg.ActiveFromNs,
		arg.ActiveToNs,
	)
	return err
}

const touchAttributionChain = `-- name: TouchAttributionChain :exec
UPDATE attribution_chains SET last_seen_ns = MAX(last_seen_ns, CAST(?1 AS INTEGER))
WHERE executor_id = ?2 AND chain_id = ?3
`

type TouchAttributionChainParams struct {
	SeenNs     int64
	ExecutorID string
	ChainID    string
}

func (q *Queries) TouchAttributionChain(ctx context.Context, arg TouchAttributionChainParams) error {
	_, err := q.db.ExecContext(ctx, touchAttributionChain, arg.SeenNs, arg.ExecutorID, arg.ChainID)
	return err
}
