// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution_verify.sql

package database

import (
	"context"
)

const getAttributionVerifyBudget = `-- name: GetAttributionVerifyBudget :one
SELECT used FROM attribution_verify_budget WHERE executor_id = ? AND chain_id = ? AND epoch = ?
`

type GetAttributionVerifyBudgetParams struct {
	ExecutorID string
	ChainID    string
	Epoch      int64
}

func (q *Queries) GetAttributionVerifyBudget(ctx context.Context, arg GetAttributionVerifyBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAttributionVerifyBudget, arg.ExecutorID, arg.ChainID, arg.Epoch)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const insertAttributionReceiptKey = `-- name: InsertAttributionReceiptKey :exec
INSERT INTO attribution_receipt_keys (key_id, public_key, valid_from_ns) VALUES (?, ?, ?)
ON CONFLICT (key_id) DO UPDATE SET valid_to_ns = NULL
`

type InsertAttributionReceiptKeyParams struct {
	KeyID       string
	PublicKey   []byte
	ValidFromNs int64
}

func (q *Queries) InsertAttributionReceiptKey(ctx context.Context, arg InsertAttributionReceiptKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAttributionReceiptKey, arg.KeyID, arg.PublicKey, arg.ValidFromNs)
	return err
}

const listAttributionReceiptKeys = `-- name: ListAttributionReceiptKeys :many
SELECT key_id, public_key, valid_from_ns, valid_to_ns FROM attribution_receipt_keys ORDER BY valid_from_ns, key_id
`

func (q *Queries) ListAttributionReceiptKeys(ctx context.Context) ([]AttributionReceiptKey, error) {
	rows, err := q.db.QueryContext(ctx, listAttributionReceiptKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributionReceiptKey
	for rows.Next() {
		var i AttributionReceiptKey
		if err := rows.Scan(
			&i.KeyID,
			&i.PublicKey,
			&i.ValidFromNs,
			&i.ValidToNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAttributionKey = `-- name: NextAttributionKey :one
SELECT epoch, key FROM attribution_keys
WHERE executor_id = ? AND chain_id = ? AND epoch >= ?
ORDER BY epoch LIMIT 1
`

type NextAttributionKeyParams struct {
	ExecutorID string
	ChainID    string
	Epoch      int64
}

type NextAttributionKeyRow struct {
	Epoch int64
	Key   []byte
}

// The smallest disclosed key of a chain at or above an epoch: every lower
// key of the chain is derived from it by hashing.
func (q *Queries) NextAttributionKey(ctx context.Context, arg NextAttributionKeyParams) (NextAttributionKeyRow, error) {
	row := q.db.QueryRowContext(ctx, nextAttributionKey, arg.ExecutorID, arg.ChainID, arg.Epoch)
	var i NextAttributionKeyRow
	err := row.Scan(&i.Epoch, &i.Key)
	return i, err
}

const pruneAttributionVerifyBudget = `-- name: PruneAttributionVerifyBudget :execrows
DELETE FROM attribution_verify_budget
WHERE NOT EXISTS (
    SELECT 1 FROM attribution_chains c
    WHERE c.executor_id = attribution_verify_budget.executor_id AND c.chain_id = attribution_verify_budget.chain_id
      AND c.interval_ns > 0
      AND c.t0_ns + (attribution_verify_budget.epoch + c.delay_epochs) * c.interval_ns > ?1
)
`

// Deletes the counts of epochs whose key is due for disclosure, and those of
// chains no longer on record.
func (q *Queries) PruneAttributionVerifyBudget(ctx context.Context, nowNs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAttributionVerifyBudget, nowNs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireAttributionReceiptKeys = `-- name: RetireAttributionReceiptKeys :exec
UPDATE attribution_receipt_keys SET valid_to_ns = CAST(?1 AS INTEGER)
WHERE key_id <> ?2 AND valid_to_ns IS NULL
`

type RetireAttributionReceiptKeysParams struct {
	NowNs int64
	KeyID string
}

func (q *Queries) RetireAttributionReceiptKeys(ctx context.Context, arg RetireAttributionReceiptKeysParams) error {
	_, err := q.db.ExecContext(ctx, retireAttributionReceiptKeys, arg.NowNs, arg.KeyID)
	return err
}

const spendAttributionVerifyBudget = `-- name: SpendAttributionVerifyBudget :one
INSERT INTO attribution_verify_budget (executor_id, chain_id, epoch, used)
VALUES (?1, ?2, ?3, 1)
ON CONFLICT (executor_id, chain_id, epoch) DO UPDATE SET used = used + 1
WHERE attribution_verify_budget.used < 16
RETURNING used
`

type SpendAttributionVerifyBudgetParams struct {
	ExecutorID string
	ChainID    string
	Epoch      int64
}

// Counts one executor query of a chain epoch, unless the limit R = 16 is
// reached (dispatcher.VerifyBudget): then no row is returned. One statement,
// so concurrent requests never both take the last query.
func (q *Queries) SpendAttributionVerifyBudget(ctx context.Context, arg SpendAttributionVerifyBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, spendAttributionVerifyBudget, arg.ExecutorID, arg.ChainID, arg.Epoch)
	var used int64
	err := row.Scan(&used)
	return used, err
}
