// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cancellation.sql

package database

import (
	"context"
	"database/sql"
)

const acknowledgeCancellation = `-- name: AcknowledgeCancellation :exec
UPDATE debuglet_cancellations SET acknowledged_at = COALESCE(acknowledged_at, ?), failure = ''
WHERE debuglet_id = ?
`

type AcknowledgeCancellationParams struct {
	AcknowledgedAt sql.NullInt64
	DebugletID     int64
}

func (q *Queries) AcknowledgeCancellation(ctx context.Context, arg AcknowledgeCancellationParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeCancellation, arg.AcknowledgedAt, arg.DebugletID)
	return err
}

const attemptCancellation = `-- name: AttemptCancellation :exec
UPDATE debuglet_cancellations SET attempted_at = COALESCE(attempted_at, ?), failure = ''
WHERE debuglet_id = ? AND acknowledged_at IS NULL
`

type AttemptCancellationParams struct {
	AttemptedAt sql.NullInt64
	DebugletID  int64
}

func (q *Queries) AttemptCancellation(ctx context.Context, arg AttemptCancellationParams) error {
	_, err := q.db.ExecContext(ctx, attemptCancellation, arg.AttemptedAt, arg.DebugletID)
	return err
}

const createCancellation = `-- name: CreateCancellation :exec
INSERT INTO debuglet_cancellations (debuglet_id, request_id, reason, requested_at)
VALUES (?, ?, ?, ?) ON CONFLICT(debuglet_id) DO NOTHING
`

type CreateCancellationParams struct {
	DebugletID  int64
	RequestID   string
	Reason      string
	RequestedAt int64
}

func (q *Queries) CreateCancellation(ctx context.Context, arg CreateCancellationParams) error {
	_, err := q.db.ExecContext(ctx, createCancellation,
		arg.DebugletID,
		arg.RequestID,
		arg.Reason,
		arg.RequestedAt,
	)
	return err
}

const failCancellation = `-- name: FailCancellation :exec
UPDATE debuglet_cancellations SET failure = ?
WHERE debuglet_id = ? AND acknowledged_at IS NULL
`

type FailCancellationParams struct {
	Failure    string
	DebugletID int64
}

func (q *Queries) FailCancellation(ctx context.Context, arg FailCancellationParams) error {
	_, err := q.db.ExecContext(ctx, failCancellation, arg.Failure, arg.DebugletID)
	return err
}

const getCancellation = `-- name: GetCancellation :one
SELECT debuglet_id, request_id, reason, requested_at, attempted_at, acknowledged_at, failure, terminal_recorded_at FROM debuglet_cancellations WHERE debuglet_id = ?
`

func (q *Queries) GetCancellation(ctx context.Context, debugletID int64) (DebugletCancellation, error) {
	row := q.db.QueryRowContext(ctx, getCancellation, debugletID)
	var i DebugletCancellation
	err := row.Scan(
		&i.DebugletID,
		&i.RequestID,
		&i.Reason,
		&i.RequestedAt,
		&i.AttemptedAt,
		&i.AcknowledgedAt,
		&i.Failure,
		&i.TerminalRecordedAt,
	)
	return i, err
}

const recordCancellationTerminal = `-- name: RecordCancellationTerminal :execrows
UPDATE debuglet_cancellations SET terminal_recorded_at = COALESCE(terminal_recorded_at, ?)
WHERE debuglet_id = ?
`

type RecordCancellationTerminalParams struct {
	TerminalRecordedAt sql.NullInt64
	DebugletID         int64
}

func (q *Queries) RecordCancellationTerminal(ctx context.Context, arg RecordCancellationTerminalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordCancellationTerminal, arg.TerminalRecordedAt, arg.DebugletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
