// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_credentials.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const approveDeviceLogin = `-- name: ApproveDeviceLogin :execrows
UPDATE device_logins SET state = 'approved', user_id = ?1, approver_session = ?2
WHERE selector = ?3 AND state = 'pending' AND expires_at > ?4
`

type ApproveDeviceLoginParams struct {
	UserID          sql.NullInt64
	ApproverSession string
	Selector        string
	Now             int64
}

func (q *Queries) ApproveDeviceLogin(ctx context.Context, arg ApproveDeviceLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveDeviceLogin,
		arg.UserID,
		arg.ApproverSession,
		arg.Selector,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelDeviceLogin = `-- name: CancelDeviceLogin :exec
UPDATE device_logins SET state = 'cancelled' WHERE selector = ? AND state IN ('pending', 'approved')
`

func (q *Queries) CancelDeviceLogin(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, cancelDeviceLogin, selector)
	return err
}

const consumeDeviceLogin = `-- name: ConsumeDeviceLogin :execrows
UPDATE device_logins SET state = 'consumed'
WHERE selector = ?1 AND state = 'approved' AND expires_at > ?2
`

type ConsumeDeviceLoginParams struct {
	Selector string
	Now      int64
}

func (q *Queries) ConsumeDeviceLogin(ctx context.Context, arg ConsumeDeviceLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeDeviceLogin, arg.Selector, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAccountCredentials = `-- name: CountAccountCredentials :one
SELECT COUNT(*) FROM sessions WHERE user_id = ?1
  AND revoked = 0 AND expires_at > ?2
`

type CountAccountCredentialsParams struct {
	UserID int64
	Now    models.UTCTime
}

func (q *Queries) CountAccountCredentials(ctx context.Context, arg CountAccountCredentialsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountCredentials, arg.UserID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeviceLogins = `-- name: CountDeviceLogins :one
SELECT COUNT(*) FROM device_logins
`

func (q *Queries) CountDeviceLogins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceLogins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPICredential = `-- name: CreateAPICredential :exec
INSERT INTO sessions (selector, verifier_hash, csrf_hash, user_id, created_at, expires_at, revoked, kind, audience, scopes, label)
VALUES (?, ?, X'', ?, ?, ?, 0, 'api', ?, ?, ?)
`

type CreateAPICredentialParams struct {
	Selector     string
	VerifierHash []byte
	UserID       int64
	CreatedAt    models.UTCTime
	ExpiresAt    models.UTCTime
	Audience     string
	Scopes       string
	Label        string
}

func (q *Queries) CreateAPICredential(ctx context.Context, arg CreateAPICredentialParams) error {
	_, err := q.db.ExecContext(ctx, createAPICredential,
		arg.Selector,
		arg.VerifierHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Audience,
		arg.Scopes,
		arg.Label,
	)
	return err
}

const createDeviceLogin = `-- name: CreateDeviceLogin :exec
INSERT INTO device_logins (selector, verifier_hash, user_code_hash, audience, scopes, label, expires_at, next_poll_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDeviceLoginParams struct {
	Selector     string
	VerifierHash []byte
	UserCodeHash []byte
	Audience     string
	Scopes       string
	Label        string
	ExpiresAt    int64
	NextPollAt   int64
}

func (q *Queries) CreateDeviceLogin(ctx context.Context, arg CreateDeviceLoginParams) error {
	_, err := q.db.ExecContext(ctx, createDeviceLogin,
		arg.Selector,
		arg.VerifierHash,
		arg.UserCodeHash,
		arg.Audience,
		arg.Scopes,
		arg.Label,
		arg.ExpiresAt,
		arg.NextPollAt,
	)
	return err
}

const deleteExpiredDeviceLogins = `-- name: DeleteExpiredDeviceLogins :exec
DELETE FROM device_logins WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredDeviceLogins(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDeviceLogins, expiresAt)
	return err
}

const denyDeviceLogin = `-- name: DenyDeviceLogin :execrows
UPDATE device_logins SET state = 'denied'
WHERE selector = ?1 AND state = 'pending' AND expires_at > ?2
`

type DenyDeviceLoginParams struct {
	Selector string
	Now      int64
}

func (q *Queries) DenyDeviceLogin(ctx context.Context, arg DenyDeviceLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, denyDeviceLogin, arg.Selector, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCredentialUser = `-- name: GetCredentialUser :one
SELECT id, uuid, name, role FROM users WHERE id = ?
`

func (q *Queries) GetCredentialUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getCredentialUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getDeviceLogin = `-- name: GetDeviceLogin :one
SELECT selector, verifier_hash, user_code_hash, audience, scopes, label, expires_at, next_poll_at, poll_interval, state, approver_session, user_id FROM device_logins WHERE selector = ?
`

func (q *Queries) GetDeviceLogin(ctx context.Context, selector string) (DeviceLogin, error) {
	row := q.db.QueryRowContext(ctx, getDeviceLogin, selector)
	var i DeviceLogin
	err := row.Scan(
		&i.Selector,
		&i.VerifierHash,
		&i.UserCodeHash,
		&i.Audience,
		&i.Scopes,
		&i.Label,
		&i.ExpiresAt,
		&i.NextPollAt,
		&i.PollInterval,
		&i.State,
		&i.ApproverSession,
		&i.UserID,
	)
	return i, err
}

const getDeviceLoginByUserCode = `-- name: GetDeviceLoginByUserCode :one
SELECT selector, verifier_hash, user_code_hash, audience, scopes, label, expires_at, next_poll_at, poll_interval, state, approver_session, user_id FROM device_logins WHERE user_code_hash = ?
`

func (q *Queries) GetDeviceLoginByUserCode(ctx context.Context, userCodeHash []byte) (DeviceLogin, error) {
	row := q.db.QueryRowContext(ctx, getDeviceLoginByUserCode, userCodeHash)
	var i DeviceLogin
	err := row.Scan(
		&i.Selector,
		&i.VerifierHash,
		&i.UserCodeHash,
		&i.Audience,
		&i.Scopes,
		&i.Label,
		&i.ExpiresAt,
		&i.NextPollAt,
		&i.PollInterval,
		&i.State,
		&i.ApproverSession,
		&i.UserID,
	)
	return i, err
}

const listAccountCredentials = `-- name: ListAccountCredentials :many
SELECT selector, kind, audience, scopes, label, created_at, expires_at
FROM sessions WHERE user_id = (SELECT id FROM users WHERE uuid = ?1)
  AND revoked = 0 AND expires_at > ?2
ORDER BY created_at DESC LIMIT 100
`

type ListAccountCredentialsParams struct {
	Uuid uuid.UUID
	Now  models.UTCTime
}

type ListAccountCredentialsRow struct {
	Selector  string
	Kind      string
	Audience  string
	Scopes    string
	Label     string
	CreatedAt models.UTCTime
	ExpiresAt models.UTCTime
}

func (q *Queries) ListAccountCredentials(ctx context.Context, arg ListAccountCredentialsParams) ([]ListAccountCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountCredentials, arg.Uuid, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountCredentialsRow
	for rows.Next() {
		var i ListAccountCredentialsRow
		if err := rows.Scan(
			&i.Selector,
			&i.Kind,
			&i.Audience,
			&i.Scopes,
			&i.Label,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCredentialSession = `-- name: LockCredentialSession :exec
UPDATE sessions SET revoked = revoked WHERE selector = ?
`

func (q *Queries) LockCredentialSession(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, lockCredentialSession, selector)
	return err
}

const lockDeviceLogin = `-- name: LockDeviceLogin :exec
UPDATE device_logins SET state = state WHERE selector = ?
`

func (q *Queries) LockDeviceLogin(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, lockDeviceLogin, selector)
	return err
}

const revokeAccountCredential = `-- name: RevokeAccountCredential :execrows
UPDATE sessions SET revoked = 1
WHERE selector = ?1 AND user_id = (SELECT id FROM users WHERE uuid = ?2)
`

type RevokeAccountCredentialParams struct {
	Selector string
	Uuid     uuid.UUID
}

func (q *Queries) RevokeAccountCredential(ctx context.Context, arg RevokeAccountCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccountCredential, arg.Selector, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceLoginPoll = `-- name: UpdateDeviceLoginPoll :execrows
UPDATE device_logins SET next_poll_at = ?1, poll_interval = ?2
WHERE selector = ?3 AND state IN ('pending', 'approved')
`

type UpdateDeviceLoginPollParams struct {
	NextPollAt   int64
	PollInterval int64
	Selector     string
}

func (q *Queries) UpdateDeviceLoginPoll(ctx context.Context, arg UpdateDeviceLoginPollParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeviceLoginPoll, arg.NextPollAt, arg.PollInterval, arg.Selector)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
