// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destination_policy.sql

package database

import (
	"context"
	"database/sql"
)

const latestDestinationPolicyRevision = `-- name: LatestDestinationPolicyRevision :one
SELECT CAST(COALESCE(MAX(revision), 0) AS INTEGER) FROM destination_policy_events
WHERE destination = ?
`

func (q *Queries) LatestDestinationPolicyRevision(ctx context.Context, destination string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestDestinationPolicyRevision, destination)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listCurrentDestinationPolicies = `-- name: ListCurrentDestinationPolicies :many
SELECT e.id, e.destination, e.kind, e.limit_bps, e.reason, e.actor, e.requested_at_ns, e.expires_at_ns, e.revision FROM destination_policy_events e
WHERE e.revision = (SELECT MAX(l.revision) FROM destination_policy_events l WHERE l.destination = e.destination)
ORDER BY e.destination
`

func (q *Queries) ListCurrentDestinationPolicies(ctx context.Context) ([]DestinationPolicyEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentDestinationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DestinationPolicyEvent
	for rows.Next() {
		var i DestinationPolicyEvent
		if err := rows.Scan(
			&i.ID,
			&i.Destination,
			&i.Kind,
			&i.LimitBps,
			&i.Reason,
			&i.Actor,
			&i.RequestedAtNs,
			&i.ExpiresAtNs,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDestinationPolicy = `-- name: RecordDestinationPolicy :one
INSERT INTO destination_policy_events (destination, kind, limit_bps, reason, actor, requested_at_ns, expires_at_ns, revision)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, destination, kind, limit_bps, reason, actor, requested_at_ns, expires_at_ns, revision
`

type RecordDestinationPolicyParams struct {
	Destination   string
	Kind          string
	LimitBps      sql.NullInt64
	Reason        string
	Actor         string
	RequestedAtNs int64
	ExpiresAtNs   sql.NullInt64
	Revision      int64
}

func (q *Queries) RecordDestinationPolicy(ctx context.Context, arg RecordDestinationPolicyParams) (DestinationPolicyEvent, error) {
	row := q.db.QueryRowContext(ctx, recordDestinationPolicy,
		arg.Destination,
		arg.Kind,
		arg.LimitBps,
		arg.Reason,
		arg.Actor,
		arg.RequestedAtNs,
		arg.ExpiresAtNs,
		arg.Revision,
	)
	var i DestinationPolicyEvent
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.Kind,
		&i.LimitBps,
		&i.Reason,
		&i.Actor,
		&i.RequestedAtNs,
		&i.ExpiresAtNs,
		&i.Revision,
	)
	return i, err
}
