// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: economics.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const listAccountIntents = `-- name: ListAccountIntents :many
SELECT t.id, t.method, t.status, t.price, t.currency, t.expires_at, t.pricing_rule
FROM transactions t
JOIN transaction_users tu ON tu.transaction_id = t.id
JOIN users u ON u.id = tu.user_id
WHERE u.uuid = ?1
  AND (CAST(?2 AS TEXT) = '' OR EXISTS (
    SELECT 1 FROM transactions c
    JOIN transaction_users cu ON cu.transaction_id = c.id
    WHERE c.id = ?2 AND cu.user_id = tu.user_id
      AND (t.expires_at < c.expires_at OR (t.expires_at = c.expires_at AND t.id < c.id))))
ORDER BY t.expires_at DESC, t.id DESC
LIMIT ?3
`

type ListAccountIntentsParams struct {
	UserUuid  uuid.UUID
	Before    string
	PageLimit int64
}

type ListAccountIntentsRow struct {
	ID          string
	Method      string
	Status      int64
	Price       int64
	Currency    string
	ExpiresAt   models.UTCTime
	PricingRule string
}

// One page of an account's payment intents, newest expiry first. A cursor
// names the last intent of the previous page; one that is not the account's
// own intent selects nothing.
func (q *Queries) ListAccountIntents(ctx context.Context, arg ListAccountIntentsParams) ([]ListAccountIntentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountIntents, arg.UserUuid, arg.Before, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountIntentsRow
	for rows.Next() {
		var i ListAccountIntentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Status,
			&i.Price,
			&i.Currency,
			&i.ExpiresAt,
			&i.PricingRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntentOrders = `-- name: ListIntentOrders :many
SELECT o.order_id, o.executor_id, o.price, o.currency, o.state, d.uuid AS run_id
FROM debuglet_order o
LEFT JOIN debuglets d ON d.id = o.debuglet_id
WHERE o.transaction_id = ?
ORDER BY o.order_id
`

type ListIntentOrdersRow struct {
	OrderID    int64
	ExecutorID string
	Price      int64
	Currency   string
	State      int64
	RunID      uuid.UUID
}

// The orders of one payment intent with the run each one admitted, if any.
func (q *Queries) ListIntentOrders(ctx context.Context, transactionID string) ([]ListIntentOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listIntentOrders, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntentOrdersRow
	for rows.Next() {
		var i ListIntentOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.ExecutorID,
			&i.Price,
			&i.Currency,
			&i.State,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
