// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package database

import (
	"context"

	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const consumeExecutorEnrollmentToken = `-- name: ConsumeExecutorEnrollmentToken :execrows
DELETE FROM executor_enrollment_tokens WHERE selector = ?
`

func (q *Queries) ConsumeExecutorEnrollmentToken(ctx context.Context, selector string) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeExecutorEnrollmentToken, selector)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createExecutorEnrollmentToken = `-- name: CreateExecutorEnrollmentToken :exec
INSERT INTO executor_enrollment_tokens (selector, executor_id, secret_hash, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateExecutorEnrollmentTokenParams struct {
	Selector   string
	ExecutorID string
	SecretHash []byte
	CreatedAt  models.UTCTime
	ExpiresAt  models.UTCTime
}

func (q *Queries) CreateExecutorEnrollmentToken(ctx context.Context, arg CreateExecutorEnrollmentTokenParams) error {
	_, err := q.db.ExecContext(ctx, createExecutorEnrollmentToken,
		arg.Selector,
		arg.ExecutorID,
		arg.SecretHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExecutorEnrollment = `-- name: DeleteExecutorEnrollment :execrows
DELETE FROM executor_enrollments WHERE executor_id = ?
`

func (q *Queries) DeleteExecutorEnrollment(ctx context.Context, executorID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExecutorEnrollment, executorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExecutorEnrollmentTokens = `-- name: DeleteExecutorEnrollmentTokens :execrows
DELETE FROM executor_enrollment_tokens WHERE executor_id = ?
`

func (q *Queries) DeleteExecutorEnrollmentTokens(ctx context.Context, executorID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExecutorEnrollmentTokens, executorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getExecutorEnrollment = `-- name: GetExecutorEnrollment :one
SELECT fingerprint FROM executor_enrollments WHERE executor_id = ?
`

func (q *Queries) GetExecutorEnrollment(ctx context.Context, executorID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getExecutorEnrollment, executorID)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const getExecutorEnrollmentToken = `-- name: GetExecutorEnrollmentToken :one
SELECT executor_id, secret_hash, expires_at FROM executor_enrollment_tokens WHERE selector = ?
`

type GetExecutorEnrollmentTokenRow struct {
	ExecutorID string
	SecretHash []byte
	ExpiresAt  models.UTCTime
}

func (q *Queries) GetExecutorEnrollmentToken(ctx context.Context, selector string) (GetExecutorEnrollmentTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutorEnrollmentToken, selector)
	var i GetExecutorEnrollmentTokenRow
	err := row.Scan(&i.ExecutorID, &i.SecretHash, &i.ExpiresAt)
	return i, err
}

const setExecutorEnrollment = `-- name: SetExecutorEnrollment :exec
/*

EXECUTOR ENROLLMENT

*/

INSERT OR REPLACE INTO executor_enrollments (executor_id, fingerprint, enrolled_at)
VALUES (?, ?, ?)
`

type SetExecutorEnrollmentParams struct {
	ExecutorID  string
	Fingerprint string
	EnrolledAt  models.UTCTime
}

func (q *Queries) SetExecutorEnrollment(ctx context.Context, arg SetExecutorEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, setExecutorEnrollment, arg.ExecutorID, arg.Fingerprint, arg.EnrolledAt)
	return err
}
