// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurement_execution.sql

package database

import (
	"context"
	"database/sql"
)

const getMeasurementExecution = `-- name: GetMeasurementExecution :one
SELECT debuglet_id, started_observed_ns, terminal_observed_ns, exit_code, tcp_endpoint FROM measurement_execution WHERE debuglet_id = ?
`

func (q *Queries) GetMeasurementExecution(ctx context.Context, debugletID int64) (MeasurementExecution, error) {
	row := q.db.QueryRowContext(ctx, getMeasurementExecution, debugletID)
	var i MeasurementExecution
	err := row.Scan(
		&i.DebugletID,
		&i.StartedObservedNs,
		&i.TerminalObservedNs,
		&i.ExitCode,
		&i.TcpEndpoint,
	)
	return i, err
}

const recordMeasurementStarted = `-- name: RecordMeasurementStarted :exec
INSERT INTO measurement_execution (debuglet_id, started_observed_ns, tcp_endpoint)
VALUES (?, ?, ?)
ON CONFLICT(debuglet_id) DO UPDATE SET
    started_observed_ns = COALESCE(measurement_execution.started_observed_ns, excluded.started_observed_ns),
    tcp_endpoint = CASE WHEN measurement_execution.started_observed_ns IS NULL THEN excluded.tcp_endpoint ELSE measurement_execution.tcp_endpoint END
`

type RecordMeasurementStartedParams struct {
	DebugletID        int64
	StartedObservedNs sql.NullInt64
	TcpEndpoint       string
}

func (q *Queries) RecordMeasurementStarted(ctx context.Context, arg RecordMeasurementStartedParams) error {
	_, err := q.db.ExecContext(ctx, recordMeasurementStarted, arg.DebugletID, arg.StartedObservedNs, arg.TcpEndpoint)
	return err
}

const recordMeasurementTerminal = `-- name: RecordMeasurementTerminal :exec
INSERT INTO measurement_execution (debuglet_id, terminal_observed_ns, exit_code)
VALUES (?, ?, ?)
ON CONFLICT(debuglet_id) DO UPDATE SET
    terminal_observed_ns = COALESCE(measurement_execution.terminal_observed_ns, excluded.terminal_observed_ns),
    exit_code = COALESCE(measurement_execution.exit_code, excluded.exit_code)
`

type RecordMeasurementTerminalParams struct {
	DebugletID         int64
	TerminalObservedNs sql.NullInt64
	ExitCode           sql.NullInt64
}

func (q *Queries) RecordMeasurementTerminal(ctx context.Context, arg RecordMeasurementTerminalParams) error {
	_, err := q.db.ExecContext(ctx, recordMeasurementTerminal, arg.DebugletID, arg.TerminalObservedNs, arg.ExitCode)
	return err
}
