// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurements.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const listMeasurements = `-- name: ListMeasurements :many
SELECT s.id, CAST(s.label AS TEXT) AS label, CAST(s.state AS TEXT) AS state,
    CAST(s.children AS INTEGER) AS children, first_run.start_time AS scheduled_start
FROM measurement_summaries s JOIN debuglets first_run ON first_run.id =
    (SELECT first.id FROM debuglets first WHERE first.transaction_id=s.id ORDER BY first.start_time, first.id LIMIT 1)
WHERE EXISTS (SELECT 1 FROM debuglets d JOIN debuglet_users du ON du.debuglet_id = d.id
    JOIN users u ON u.id = du.user_id WHERE d.transaction_id = s.id AND u.uuid = ?1)
AND (?2 = '' OR s.state = ?2)
AND instr(lower(s.id || ' ' || s.label), lower(?3)) > 0
ORDER BY s.sequence DESC LIMIT ?5 OFFSET ?4
`

type ListMeasurementsParams struct {
	UserUuid   uuid.UUID
	State      interface{}
	Search     string
	PageOffset int64
	PageLimit  int64
}

type ListMeasurementsRow struct {
	ID             string
	Label          string
	State          string
	Children       int64
	ScheduledStart models.UTCTime
}

func (q *Queries) ListMeasurements(ctx context.Context, arg ListMeasurementsParams) ([]ListMeasurementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeasurements,
		arg.UserUuid,
		arg.State,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasurementsRow
	for rows.Next() {
		var i ListMeasurementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.State,
			&i.Children,
			&i.ScheduledStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const measurementCounts = `-- name: MeasurementCounts :many
SELECT CAST(s.state AS TEXT) AS state, COUNT(*) AS count
FROM measurement_summaries s
WHERE EXISTS (SELECT 1 FROM debuglets d JOIN debuglet_users du ON du.debuglet_id = d.id
    JOIN users u ON u.id = du.user_id WHERE d.transaction_id = s.id AND u.uuid = ?1)
AND instr(lower(s.id || ' ' || s.label), lower(?2)) > 0
GROUP BY s.state
`

type MeasurementCountsParams struct {
	UserUuid uuid.UUID
	Search   string
}

type MeasurementCountsRow struct {
	State string
	Count int64
}

func (q *Queries) MeasurementCounts(ctx context.Context, arg MeasurementCountsParams) ([]MeasurementCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, measurementCounts, arg.UserUuid, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeasurementCountsRow
	for rows.Next() {
		var i MeasurementCountsRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const measurementRunCount = `-- name: MeasurementRunCount :one
SELECT COUNT(*) FROM debuglets d JOIN debuglet_users du ON du.debuglet_id = d.id
JOIN users u ON u.id = du.user_id
WHERE d.transaction_id = ?1 AND u.uuid = ?2
`

type MeasurementRunCountParams struct {
	BatchID  string
	UserUuid uuid.UUID
}

func (q *Queries) MeasurementRunCount(ctx context.Context, arg MeasurementRunCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, measurementRunCount, arg.BatchID, arg.UserUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const measurementRuns = `-- name: MeasurementRuns :many
SELECT d.uuid, d.executor_id, d.order_id, d.state,
    CAST(COALESCE(json_extract(m.document, '$.label'), '') AS TEXT) AS label,
    CAST(COALESCE(json_extract(m.document, '$.program_name'), '') AS TEXT) AS program_name
FROM debuglets d JOIN debuglet_users du ON du.debuglet_id = d.id
JOIN users u ON u.id = du.user_id
LEFT JOIN measurement_requests m ON m.debuglet_id = d.id
WHERE d.transaction_id = ?1 AND u.uuid = ?2
ORDER BY d.order_id, d.id LIMIT ?4 OFFSET ?3
`

type MeasurementRunsParams struct {
	BatchID    string
	UserUuid   uuid.UUID
	PageOffset int64
	PageLimit  int64
}

type MeasurementRunsRow struct {
	Uuid        uuid.UUID
	ExecutorID  string
	OrderID     int64
	State       models.DebugletRunState
	Label       string
	ProgramName string
}

func (q *Queries) MeasurementRuns(ctx context.Context, arg MeasurementRunsParams) ([]MeasurementRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, measurementRuns,
		arg.BatchID,
		arg.UserUuid,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeasurementRunsRow
	for rows.Next() {
		var i MeasurementRunsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ExecutorID,
			&i.OrderID,
			&i.State,
			&i.Label,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
