// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurement_profiles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMeasurementProfile = `-- name: CreateMeasurementProfile :execrows
INSERT INTO measurement_profiles (id, user_id, document)
SELECT ?1, users.id, ?2 FROM users
WHERE users.uuid = ?3
AND (SELECT count(*) FROM measurement_profiles WHERE user_id = users.id) < 32
`

type CreateMeasurementProfileParams struct {
	ID       string
	Document string
	Uuid     uuid.UUID
}

func (q *Queries) CreateMeasurementProfile(ctx context.Context, arg CreateMeasurementProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMeasurementProfile, arg.ID, arg.Document, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMeasurementProfile = `-- name: DeleteMeasurementProfile :execrows
DELETE FROM measurement_profiles
WHERE measurement_profiles.id = ?1 AND user_id = (SELECT users.id FROM users WHERE users.uuid = ?2)
`

type DeleteMeasurementProfileParams struct {
	ID   string
	Uuid uuid.UUID
}

func (q *Queries) DeleteMeasurementProfile(ctx context.Context, arg DeleteMeasurementProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMeasurementProfile, arg.ID, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMeasurementProfile = `-- name: GetMeasurementProfile :one
SELECT document FROM measurement_profiles JOIN users ON users.id = measurement_profiles.user_id
WHERE measurement_profiles.id = ?1 AND users.uuid = ?2
`

type GetMeasurementProfileParams struct {
	ID   string
	Uuid uuid.UUID
}

func (q *Queries) GetMeasurementProfile(ctx context.Context, arg GetMeasurementProfileParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeasurementProfile, arg.ID, arg.Uuid)
	var document string
	err := row.Scan(&document)
	return document, err
}

const getMeasurementRequest = `-- name: GetMeasurementRequest :one
SELECT document FROM measurement_requests WHERE debuglet_id = ?
`

func (q *Queries) GetMeasurementRequest(ctx context.Context, debugletID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeasurementRequest, debugletID)
	var document string
	err := row.Scan(&document)
	return document, err
}

const insertMeasurementRequest = `-- name: InsertMeasurementRequest :exec
INSERT INTO measurement_requests (debuglet_id, document) VALUES (?, ?)
`

type InsertMeasurementRequestParams struct {
	DebugletID int64
	Document   string
}

func (q *Queries) InsertMeasurementRequest(ctx context.Context, arg InsertMeasurementRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertMeasurementRequest, arg.DebugletID, arg.Document)
	return err
}

const listMeasurementProfiles = `-- name: ListMeasurementProfiles :many
SELECT measurement_profiles.id, CAST(json_extract(document, '$.name') AS TEXT) AS name,
    CAST(json_extract(document, '$.program.sha256') AS TEXT) AS program_sha256
FROM measurement_profiles JOIN users ON users.id = measurement_profiles.user_id
WHERE users.uuid = ? ORDER BY name, measurement_profiles.id
`

type ListMeasurementProfilesRow struct {
	ID            string
	Name          string
	ProgramSha256 string
}

func (q *Queries) ListMeasurementProfiles(ctx context.Context, argUuid uuid.UUID) ([]ListMeasurementProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeasurementProfiles, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasurementProfilesRow
	for rows.Next() {
		var i ListMeasurementProfilesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ProgramSha256); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeasurementProfile = `-- name: UpdateMeasurementProfile :execrows
UPDATE measurement_profiles SET document = ?1
WHERE measurement_profiles.id = ?2 AND user_id = (SELECT users.id FROM users WHERE users.uuid = ?3)
`

type UpdateMeasurementProfileParams struct {
	Document string
	ID       string
	Uuid     uuid.UUID
}

func (q *Queries) UpdateMeasurementProfile(ctx context.Context, arg UpdateMeasurementProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMeasurementProfile, arg.Document, arg.ID, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
