// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"debuglet/internal/dispatcher/models"
	"github.com/google/uuid"
)

type Debuglet struct {
	ID         int64
	Uuid       uuid.UUID
	StartTime  models.UTCTime
	EndTime    models.UTCTime
	Usage      int64
	CeilBw     int64
	ExecutorID string
	Addresses  models.CommaSeparatedList
	State      models.DebugletRunState
	Error      sql.NullString
}

type DebugletLog struct {
	ID         int64
	DebugletID int64
	Timestamp  models.UTCTime
	Output     []byte
}

type DebugletOrder struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
}

type DebugletUser struct {
	DebugletID int64
	UserID     int64
}

type Earning struct {
	ExecutorID     string
	Currency       string
	TotalIncome    int64
	CurrentBalance int64
}

type Transaction struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt models.UTCTime
	Hash      string
	Currency  string
	Status    int64
}

type TransactionState struct {
	Key   string
	Value string
}

type User struct {
	ID   int64
	Uuid uuid.UUID
	Name string
}
