// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

type AccountRunReservation struct {
	DebugletID          int64
	AccountID           int64
	QueuedBytes         int64
	RetiredAt           sql.NullInt64
	LastRetirementCheck int64
}

type AllocationReclamation struct {
	DebugletID  int64
	ReclaimedAt models.UTCTime
}

type AttributionChain struct {
	ExecutorID  string
	ChainID     string
	Anchor      []byte
	T0Ns        int64
	IntervalNs  int64
	DelayEpochs int64
	ChainLength int64
	TagSpec     int64
	FirstSeenNs int64
	LastSeenNs  int64
}

type AttributionKey struct {
	ExecutorID    string
	ChainID       string
	Epoch         int64
	Key           []byte
	DisclosedAtNs int64
}

type AttributionRetention struct {
	Singleton      int64
	RetainedFromNs int64
}

type AttributionRun struct {
	DebugletID       int64
	ChainID          string
	SourceIp         string
	SourceIpObserved int64
	ActiveFromNs     int64
	ActiveToNs       int64
}

type Debuglet struct {
	ID                    int64
	Uuid                  uuid.UUID
	StartTime             models.UTCTime
	EndTime               models.UTCTime
	Usage                 int64
	CeilBw                int64
	ExecutorID            string
	Addresses             models.CommaSeparatedList
	State                 models.DebugletRunState
	Error                 sql.NullString
	TransactionID         string
	OrderID               int64
	DispatcherIncarnation string
	SessionID             string
}

type DebugletCancellation struct {
	DebugletID     int64
	RequestID      string
	Reason         string
	RequestedAt    int64
	AttemptedAt    sql.NullInt64
	AcknowledgedAt sql.NullInt64
	Failure        string
}

type DebugletLog struct {
	ID             int64
	DebugletID     int64
	Timestamp      models.UTCTime
	Output         []byte
	SourceSequence sql.NullInt64
}

type DebugletOrder struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
	State         int64
	RefundAddress string
	DebugletID    sql.NullInt64
}

type DebugletOutput struct {
	DebugletID        int64
	OutputVersion     int64
	OwnerFingerprint  string
	AccountID         int64
	CommittedSequence int64
	ByteCount         int64
	FrameCount        int64
	LastLogID         int64
	FinalSequence     sql.NullInt64
	FinalCursor       sql.NullInt64
	Status            string
	Reason            string
}

type DebugletProvenance struct {
	DebugletID int64
	Document   string
}

type DebugletUser struct {
	DebugletID int64
	UserID     int64
}

type DestinationPolicyEvent struct {
	ID            int64
	Destination   string
	Kind          string
	LimitBps      sql.NullInt64
	Reason        string
	Actor         string
	RequestedAtNs int64
	ExpiresAtNs   sql.NullInt64
	Revision      int64
}

type DeviceLogin struct {
	Selector        string
	VerifierHash    []byte
	UserCodeHash    []byte
	Audience        string
	Scopes          string
	Label           string
	ExpiresAt       int64
	NextPollAt      int64
	PollInterval    int64
	State           string
	ApproverSession string
	UserID          sql.NullInt64
}

type Earning struct {
	ExecutorID       string
	Currency         string
	TotalIncome      int64
	CurrentBalance   int64
	SuiWalletAddress string
}

type ExecutorEnrollment struct {
	ExecutorID  string
	Fingerprint string
	EnrolledAt  models.UTCTime
}

type ExecutorEnrollmentToken struct {
	Selector   string
	ExecutorID string
	SecretHash []byte
	CreatedAt  models.UTCTime
	ExpiresAt  models.UTCTime
}

type MeasurementExecution struct {
	DebugletID         int64
	StartedObservedNs  sql.NullInt64
	TerminalObservedNs sql.NullInt64
	ExitCode           sql.NullInt64
	TcpEndpoint        string
}

type MeasurementProfile struct {
	ID       string
	UserID   int64
	Document string
}

type MeasurementRequest struct {
	DebugletID int64
	Document   string
}

type MeasurementSummary struct {
	ID       string
	Sequence interface{}
	Label    interface{}
	Children int64
	State    string
}

type OauthIdentity struct {
	Provider  string
	Issuer    string
	Subject   string
	UserID    int64
	Login     string
	CreatedAt models.UTCTime
	UpdatedAt models.UTCTime
}

type OauthLoginAttempt struct {
	StateHash       []byte
	Provider        string
	Verifier        string
	Nonce           string
	Purpose         string
	SessionSelector string
	ExpiresAt       models.UTCTime
}

type OutputAccountUsage struct {
	AccountID    int64
	ChargedBytes int64
	FrameCount   int64
}

type OutputNodeUsage struct {
	Singleton    int64
	ChargedBytes int64
	FrameCount   int64
}

type OwnedExecutor struct {
	ExecutorID string
	UserID     int64
	Name       string
	CreatedAt  models.UTCTime
}

type PayloadTombstone struct {
	DebugletID        int64
	DeletedAt         int64
	Reason            string
	WorkloadSha256    sql.NullString
	CertificateSha256 sql.NullString
}

type PendingIdentityLink struct {
	UserID          int64
	Provider        string
	Issuer          string
	Subject         string
	Login           string
	SessionSelector string
	ExpiresAt       models.UTCTime
}

type RetryRequest struct {
	CallerScope    string
	RequestID      string
	ParentRunID    string
	TransactionID  string
	RequestHash    string
	IntentMetadata string
}

type Session struct {
	ID              int64
	Selector        string
	VerifierHash    []byte
	CsrfHash        []byte
	UserID          int64
	CreatedAt       models.UTCTime
	ExpiresAt       models.UTCTime
	Revoked         int64
	Kind            string
	Audience        string
	Scopes          string
	Label           string
	AuthenticatedAt models.UTCTime
}

type Transaction struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt models.UTCTime
	Hash      string
	Currency  string
	Status    int64
}

type TransactionState struct {
	Key   string
	Value string
}

type TransactionUser struct {
	TransactionID string
	UserID        int64
}

type User struct {
	ID   int64
	Uuid uuid.UUID
	Name string
	Role string
}

type UserCredential struct {
	UserID     int64
	Kind       string
	Selector   string
	SecretHash []byte
	CreatedAt  models.UTCTime
}
