// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

type Debuglet struct {
	ID                    int64
	Uuid                  uuid.UUID
	StartTime             models.UTCTime
	EndTime               models.UTCTime
	Usage                 int64
	CeilBw                int64
	ExecutorID            string
	Addresses             models.CommaSeparatedList
	State                 models.DebugletRunState
	Error                 sql.NullString
	TransactionID         string
	OrderID               int64
	DispatcherIncarnation string
	SessionID             string
}

type DebugletLog struct {
	ID             int64
	DebugletID     int64
	Timestamp      models.UTCTime
	Output         []byte
	SourceSequence sql.NullInt64
}

type DebugletOrder struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
	State         int64
	RefundAddress string
	DebugletID    sql.NullInt64
}

type DebugletOutput struct {
	DebugletID        int64
	OutputVersion     int64
	OwnerFingerprint  string
	AccountID         int64
	CommittedSequence int64
	ByteCount         int64
	FrameCount        int64
	LastLogID         int64
	FinalSequence     sql.NullInt64
	FinalCursor       sql.NullInt64
	Status            string
	Reason            string
}

type DebugletProvenance struct {
	DebugletID int64
	Document   string
}

type DebugletTerminalCleanup struct {
	DebugletID int64
}

type DebugletUser struct {
	DebugletID int64
	UserID     int64
}

type Earning struct {
	ExecutorID       string
	Currency         string
	TotalIncome      int64
	CurrentBalance   int64
	SuiWalletAddress string
}

type ExecutorEnrollment struct {
	ExecutorID  string
	Fingerprint string
	EnrolledAt  models.UTCTime
}

type ExecutorEnrollmentToken struct {
	Selector   string
	ExecutorID string
	SecretHash []byte
	CreatedAt  models.UTCTime
	ExpiresAt  models.UTCTime
}

type OauthIdentity struct {
	Provider  string
	Subject   string
	UserID    int64
	Login     string
	CreatedAt models.UTCTime
	UpdatedAt models.UTCTime
}

type OutputAccountUsage struct {
	AccountID    int64
	ChargedBytes int64
	FrameCount   int64
}

type OutputNodeUsage struct {
	Singleton    int64
	ChargedBytes int64
	FrameCount   int64
}

type Session struct {
	ID           int64
	Selector     string
	VerifierHash []byte
	CsrfHash     []byte
	UserID       int64
	CreatedAt    models.UTCTime
	ExpiresAt    models.UTCTime
	Revoked      int64
}

type Transaction struct {
	ID        string
	AuthKey   string
	Price     int64
	Method    string
	ExpiresAt models.UTCTime
	Hash      string
	Currency  string
	Status    int64
}

type TransactionState struct {
	Key   string
	Value string
}

type TransactionUser struct {
	TransactionID string
	UserID        int64
}

type User struct {
	ID   int64
	Uuid uuid.UUID
	Name string
	Role string
}

type UserCredential struct {
	UserID     int64
	Kind       string
	Selector   string
	SecretHash []byte
	CreatedAt  models.UTCTime
}
