// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: output.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const addOutputAccountUsage = `-- name: AddOutputAccountUsage :exec
UPDATE output_account_usage SET charged_bytes = charged_bytes + ?1,
    frame_count = frame_count + ?2 WHERE account_id = ?3
`

type AddOutputAccountUsageParams struct {
	Bytes     int64
	Frames    int64
	AccountID int64
}

func (q *Queries) AddOutputAccountUsage(ctx context.Context, arg AddOutputAccountUsageParams) error {
	_, err := q.db.ExecContext(ctx, addOutputAccountUsage, arg.Bytes, arg.Frames, arg.AccountID)
	return err
}

const addOutputNodeUsage = `-- name: AddOutputNodeUsage :exec
UPDATE output_node_usage SET charged_bytes = charged_bytes + ?1,
    frame_count = frame_count + ?2 WHERE singleton = 1
`

type AddOutputNodeUsageParams struct {
	Bytes  int64
	Frames int64
}

func (q *Queries) AddOutputNodeUsage(ctx context.Context, arg AddOutputNodeUsageParams) error {
	_, err := q.db.ExecContext(ctx, addOutputNodeUsage, arg.Bytes, arg.Frames)
	return err
}

const advanceDebugletOutput = `-- name: AdvanceDebugletOutput :execrows
UPDATE debuglet_output SET committed_sequence = ?1,
    byte_count = byte_count + ?2, frame_count = frame_count + 1,
    last_log_id = ?3
WHERE debuglet_id = ?4 AND final_sequence IS NULL AND committed_sequence = ?1 - 1
`

type AdvanceDebugletOutputParams struct {
	Sequence   int64
	Bytes      int64
	LogID      int64
	DebugletID int64
}

func (q *Queries) AdvanceDebugletOutput(ctx context.Context, arg AdvanceDebugletOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceDebugletOutput,
		arg.Sequence,
		arg.Bytes,
		arg.LogID,
		arg.DebugletID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceLegacyDebugletOutput = `-- name: AdvanceLegacyDebugletOutput :execrows
UPDATE debuglet_output SET byte_count = byte_count + ?1, frame_count = frame_count + 1,
    last_log_id = ?2
WHERE debuglet_id = ?3 AND output_version = 0 AND final_sequence IS NULL
`

type AdvanceLegacyDebugletOutputParams struct {
	Bytes      int64
	LogID      int64
	DebugletID int64
}

func (q *Queries) AdvanceLegacyDebugletOutput(ctx context.Context, arg AdvanceLegacyDebugletOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceLegacyDebugletOutput, arg.Bytes, arg.LogID, arg.DebugletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDebugletOutput = `-- name: CreateDebugletOutput :exec
INSERT INTO debuglet_output (debuglet_id, output_version, owner_fingerprint, account_id, byte_count, frame_count, last_log_id)
SELECT d.id, ?1, ?2,
    COALESCE((SELECT MIN(user_id) FROM debuglet_users WHERE debuglet_id = d.id), 0),
    COALESCE((SELECT SUM(length(output)) FROM debuglet_logs WHERE debuglet_id = d.id), 0),
    (SELECT COUNT(*) FROM debuglet_logs WHERE debuglet_id = d.id),
    COALESCE((SELECT MAX(id) FROM debuglet_logs WHERE debuglet_id = d.id), 0)
FROM debuglets d WHERE d.uuid = ?3
`

type CreateDebugletOutputParams struct {
	OutputVersion    int64
	OwnerFingerprint string
	Uuid             uuid.UUID
}

func (q *Queries) CreateDebugletOutput(ctx context.Context, arg CreateDebugletOutputParams) error {
	_, err := q.db.ExecContext(ctx, createDebugletOutput, arg.OutputVersion, arg.OwnerFingerprint, arg.Uuid)
	return err
}

const createSequencedDebugletLog = `-- name: CreateSequencedDebugletLog :one
INSERT INTO debuglet_logs (debuglet_id, timestamp, output, source_sequence) VALUES (?, ?, ?, ?)
RETURNING id, debuglet_id, timestamp, output, source_sequence
`

type CreateSequencedDebugletLogParams struct {
	DebugletID     int64
	Timestamp      models.UTCTime
	Output         []byte
	SourceSequence sql.NullInt64
}

func (q *Queries) CreateSequencedDebugletLog(ctx context.Context, arg CreateSequencedDebugletLogParams) (DebugletLog, error) {
	row := q.db.QueryRowContext(ctx, createSequencedDebugletLog,
		arg.DebugletID,
		arg.Timestamp,
		arg.Output,
		arg.SourceSequence,
	)
	var i DebugletLog
	err := row.Scan(
		&i.ID,
		&i.DebugletID,
		&i.Timestamp,
		&i.Output,
		&i.SourceSequence,
	)
	return i, err
}

const ensureOutputAccountUsage = `-- name: EnsureOutputAccountUsage :exec
INSERT INTO output_account_usage (account_id, charged_bytes, frame_count) VALUES (?, 0, 0)
ON CONFLICT (account_id) DO NOTHING
`

func (q *Queries) EnsureOutputAccountUsage(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, ensureOutputAccountUsage, accountID)
	return err
}

const finishDebugletOutput = `-- name: FinishDebugletOutput :execrows
UPDATE debuglet_output SET final_sequence = committed_sequence, final_cursor = last_log_id,
    status = ?1, reason = ?2
WHERE debuglet_id = ?3 AND final_sequence IS NULL AND committed_sequence = ?4
`

type FinishDebugletOutputParams struct {
	Status     string
	Reason     string
	DebugletID int64
	Sequence   int64
}

func (q *Queries) FinishDebugletOutput(ctx context.Context, arg FinishDebugletOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishDebugletOutput,
		arg.Status,
		arg.Reason,
		arg.DebugletID,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDebugletOutput = `-- name: GetDebugletOutput :one
SELECT o.debuglet_id, o.output_version, o.owner_fingerprint, o.account_id, o.committed_sequence, o.byte_count, o.frame_count, o.last_log_id, o.final_sequence, o.final_cursor, o.status, o.reason, d.uuid, d.executor_id, d.dispatcher_incarnation, d.session_id
FROM debuglet_output o JOIN debuglets d ON d.id = o.debuglet_id WHERE d.uuid = ?
`

type GetDebugletOutputRow struct {
	DebugletID            int64
	OutputVersion         int64
	OwnerFingerprint      string
	AccountID             int64
	CommittedSequence     int64
	ByteCount             int64
	FrameCount            int64
	LastLogID             int64
	FinalSequence         sql.NullInt64
	FinalCursor           sql.NullInt64
	Status                string
	Reason                string
	Uuid                  uuid.UUID
	ExecutorID            string
	DispatcherIncarnation string
	SessionID             string
}

func (q *Queries) GetDebugletOutput(ctx context.Context, argUuid uuid.UUID) (GetDebugletOutputRow, error) {
	row := q.db.QueryRowContext(ctx, getDebugletOutput, argUuid)
	var i GetDebugletOutputRow
	err := row.Scan(
		&i.DebugletID,
		&i.OutputVersion,
		&i.OwnerFingerprint,
		&i.AccountID,
		&i.CommittedSequence,
		&i.ByteCount,
		&i.FrameCount,
		&i.LastLogID,
		&i.FinalSequence,
		&i.FinalCursor,
		&i.Status,
		&i.Reason,
		&i.Uuid,
		&i.ExecutorID,
		&i.DispatcherIncarnation,
		&i.SessionID,
	)
	return i, err
}

const getOutputAccountUsage = `-- name: GetOutputAccountUsage :one
SELECT account_id, charged_bytes, frame_count FROM output_account_usage WHERE account_id = ?1
`

func (q *Queries) GetOutputAccountUsage(ctx context.Context, accountID int64) (OutputAccountUsage, error) {
	row := q.db.QueryRowContext(ctx, getOutputAccountUsage, accountID)
	var i OutputAccountUsage
	err := row.Scan(&i.AccountID, &i.ChargedBytes, &i.FrameCount)
	return i, err
}

const getOutputNodeUsage = `-- name: GetOutputNodeUsage :one
SELECT singleton, charged_bytes, frame_count FROM output_node_usage WHERE singleton = 1
`

func (q *Queries) GetOutputNodeUsage(ctx context.Context) (OutputNodeUsage, error) {
	row := q.db.QueryRowContext(ctx, getOutputNodeUsage)
	var i OutputNodeUsage
	err := row.Scan(&i.Singleton, &i.ChargedBytes, &i.FrameCount)
	return i, err
}

const getSequencedDebugletLog = `-- name: GetSequencedDebugletLog :one
SELECT id, debuglet_id, timestamp, output, source_sequence FROM debuglet_logs WHERE debuglet_id = ? AND source_sequence = ?
`

type GetSequencedDebugletLogParams struct {
	DebugletID     int64
	SourceSequence sql.NullInt64
}

func (q *Queries) GetSequencedDebugletLog(ctx context.Context, arg GetSequencedDebugletLogParams) (DebugletLog, error) {
	row := q.db.QueryRowContext(ctx, getSequencedDebugletLog, arg.DebugletID, arg.SourceSequence)
	var i DebugletLog
	err := row.Scan(
		&i.ID,
		&i.DebugletID,
		&i.Timestamp,
		&i.Output,
		&i.SourceSequence,
	)
	return i, err
}

const interruptUnresumableOutput = `-- name: InterruptUnresumableOutput :execrows
UPDATE debuglet_output SET final_sequence = committed_sequence, final_cursor = last_log_id,
    status = 'truncated', reason = 'executor_interrupted'
WHERE final_sequence IS NULL AND (output_version = 0 OR owner_fingerprint = '')
  AND debuglet_id IN (SELECT id FROM debuglets
                      WHERE dispatcher_incarnation = ?1 AND session_id = ?2)
`

type InterruptUnresumableOutputParams struct {
	DispatcherIncarnation string
	SessionID             string
}

// Output bound to an ended session can continue only over an enrolled
// credential. Legacy and unenrolled output therefore ends at its committed prefix.
func (q *Queries) InterruptUnresumableOutput(ctx context.Context, arg InterruptUnresumableOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptUnresumableOutput, arg.DispatcherIncarnation, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
