// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owned_executors.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const createOwnedExecutor = `-- name: CreateOwnedExecutor :execrows
INSERT INTO owned_executors (executor_id, user_id, name, created_at)
SELECT ?1, users.id, ?2, ?3 FROM users
WHERE users.uuid = ?4
AND (SELECT count(*) FROM owned_executors WHERE user_id = users.id) < 10
`

type CreateOwnedExecutorParams struct {
	ExecutorID string
	Name       string
	CreatedAt  models.UTCTime
	Uuid       uuid.UUID
}

func (q *Queries) CreateOwnedExecutor(ctx context.Context, arg CreateOwnedExecutorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOwnedExecutor,
		arg.ExecutorID,
		arg.Name,
		arg.CreatedAt,
		arg.Uuid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOwnedExecutor = `-- name: GetOwnedExecutor :one
SELECT owned_executors.executor_id, owned_executors.name,
    EXISTS(SELECT 1 FROM executor_enrollments WHERE executor_id = owned_executors.executor_id) AS enrolled
FROM owned_executors JOIN users ON users.id = owned_executors.user_id
WHERE users.uuid = ?1 AND owned_executors.executor_id = ?2
`

type GetOwnedExecutorParams struct {
	Uuid       uuid.UUID
	ExecutorID string
}

type GetOwnedExecutorRow struct {
	ExecutorID string
	Name       string
	Enrolled   bool
}

func (q *Queries) GetOwnedExecutor(ctx context.Context, arg GetOwnedExecutorParams) (GetOwnedExecutorRow, error) {
	row := q.db.QueryRowContext(ctx, getOwnedExecutor, arg.Uuid, arg.ExecutorID)
	var i GetOwnedExecutorRow
	err := row.Scan(&i.ExecutorID, &i.Name, &i.Enrolled)
	return i, err
}

const listOwnedExecutors = `-- name: ListOwnedExecutors :many
SELECT owned_executors.executor_id, owned_executors.name,
    EXISTS(SELECT 1 FROM executor_enrollments WHERE executor_id = owned_executors.executor_id) AS enrolled
FROM owned_executors JOIN users ON users.id = owned_executors.user_id
WHERE users.uuid = ? ORDER BY owned_executors.created_at, owned_executors.executor_id
`

type ListOwnedExecutorsRow struct {
	ExecutorID string
	Name       string
	Enrolled   bool
}

func (q *Queries) ListOwnedExecutors(ctx context.Context, argUuid uuid.UUID) ([]ListOwnedExecutorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnedExecutors, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedExecutorsRow
	for rows.Next() {
		var i ListOwnedExecutorsRow
		if err := rows.Scan(&i.ExecutorID, &i.Name, &i.Enrolled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
