// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe_status.sql

package database

import (
	"context"
)

const extendProbeAddress = `-- name: ExtendProbeAddress :execrows
UPDATE probe_addresses SET last_observed = MAX(last_observed, CAST(?1 AS INTEGER))
WHERE probe_addresses.executor_id = ?2 AND probe_addresses.family = ?3 AND probe_addresses.address = ?4
    AND probe_addresses.first_observed = (SELECT MAX(latest.first_observed) FROM probe_addresses AS latest
        WHERE latest.executor_id = ?2 AND latest.family = ?3)
`

type ExtendProbeAddressParams struct {
	At         int64
	ExecutorID string
	Family     int64
	Address    string
}

// Extends the family's latest run when it has the same address.
func (q *Queries) ExtendProbeAddress(ctx context.Context, arg ExtendProbeAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendProbeAddress,
		arg.At,
		arg.ExecutorID,
		arg.Family,
		arg.Address,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listConnectedProbeIDs = `-- name: ListConnectedProbeIDs :many
SELECT executor_id FROM probe_status WHERE connected = 1 ORDER BY executor_id
`

func (q *Queries) ListConnectedProbeIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listConnectedProbeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var executor_id string
		if err := rows.Scan(&executor_id); err != nil {
			return nil, err
		}
		items = append(items, executor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolledExecutorIDs = `-- name: ListEnrolledExecutorIDs :many
SELECT executor_id FROM executor_enrollments
UNION
SELECT executor_id FROM owned_executors
ORDER BY executor_id
`

func (q *Queries) ListEnrolledExecutorIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEnrolledExecutorIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var executor_id string
		if err := rows.Scan(&executor_id); err != nil {
			return nil, err
		}
		items = append(items, executor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestProbeAddresses = `-- name: ListLatestProbeAddresses :many
SELECT a.executor_id, a.family, a.address, a.via, a.first_observed, a.last_observed
FROM probe_addresses AS a
WHERE a.first_observed = (SELECT MAX(b.first_observed) FROM probe_addresses AS b
    WHERE b.executor_id = a.executor_id AND b.family = a.family)
ORDER BY a.executor_id, a.family
`

func (q *Queries) ListLatestProbeAddresses(ctx context.Context) ([]ProbeAddress, error) {
	rows, err := q.db.QueryContext(ctx, listLatestProbeAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProbeAddress
	for rows.Next() {
		var i ProbeAddress
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Family,
			&i.Address,
			&i.Via,
			&i.FirstObserved,
			&i.LastObserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeStatus = `-- name: ListProbeStatus :many
SELECT executor_id, first_connected, last_connected, connected, status_since, total_uptime, is_public, host_tags, version
FROM probe_status ORDER BY executor_id
`

func (q *Queries) ListProbeStatus(ctx context.Context) ([]ProbeStatus, error) {
	rows, err := q.db.QueryContext(ctx, listProbeStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProbeStatus
	for rows.Next() {
		var i ProbeStatus
		if err := rows.Scan(
			&i.ExecutorID,
			&i.FirstConnected,
			&i.LastConnected,
			&i.Connected,
			&i.StatusSince,
			&i.TotalUptime,
			&i.IsPublic,
			&i.HostTags,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneProbeAddresses = `-- name: PruneProbeAddresses :execrows
DELETE FROM probe_addresses WHERE probe_addresses.last_observed < CAST(?1 AS INTEGER)
    AND probe_addresses.first_observed < (SELECT MAX(latest.first_observed) FROM probe_addresses AS latest
        WHERE latest.executor_id = probe_addresses.executor_id AND latest.family = probe_addresses.family)
`

// Keeps every family's latest run, whatever its age.
func (q *Queries) PruneProbeAddresses(ctx context.Context, cutoff int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneProbeAddresses, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordProbeConnected = `-- name: RecordProbeConnected :exec
INSERT INTO probe_status (executor_id, first_connected, last_connected, connected, status_since, total_uptime, is_public, host_tags, version)
VALUES (?1, ?2, ?2, 1, ?2, 0, ?3, ?4, ?5)
ON CONFLICT (executor_id) DO UPDATE SET
    status_since = CASE
        WHEN probe_status.connected = 1 AND excluded.last_connected >= probe_status.last_connected
            AND excluded.last_connected - probe_status.last_connected <= 120
        THEN probe_status.status_since ELSE excluded.status_since END,
    total_uptime = probe_status.total_uptime + CASE
        WHEN probe_status.connected = 1 AND excluded.last_connected >= probe_status.last_connected
            AND excluded.last_connected - probe_status.last_connected <= 120
        THEN excluded.last_connected - probe_status.last_connected ELSE 0 END,
    last_connected = MAX(probe_status.last_connected, excluded.last_connected),
    connected = 1,
    is_public = excluded.is_public,
    host_tags = excluded.host_tags,
    version = excluded.version
`

type RecordProbeConnectedParams struct {
	ExecutorID string
	Now        int64
	IsPublic   int64
	HostTags   string
	Version    string
}

// A registration within 120 seconds (probeStreakGrace) of the last connected
// record of a connected row (a replacement session, or a dispatcher restart) continues
// that row's streak and its uptime; otherwise the old streak ended at its
// last_connected and a new one starts now.
func (q *Queries) RecordProbeConnected(ctx context.Context, arg RecordProbeConnectedParams) error {
	_, err := q.db.ExecContext(ctx, recordProbeConnected,
		arg.ExecutorID,
		arg.Now,
		arg.IsPublic,
		arg.HostTags,
		arg.Version,
	)
	return err
}

const recordProbeDisconnected = `-- name: RecordProbeDisconnected :execrows
UPDATE probe_status SET connected = 0, status_since = last_connected
WHERE executor_id = ? AND connected = 1
`

// The executor was last known connected at last_connected; it disconnected
// then, as far as this record can tell.
func (q *Queries) RecordProbeDisconnected(ctx context.Context, executorID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordProbeDisconnected, executorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startProbeAddress = `-- name: StartProbeAddress :execrows
INSERT INTO probe_addresses (executor_id, family, address, via, first_observed, last_observed)
SELECT ?1, ?2, ?3, ?4, CAST(?5 AS INTEGER), CAST(?5 AS INTEGER)
WHERE NOT EXISTS (SELECT 1 FROM probe_addresses AS covered
    WHERE covered.executor_id = ?1 AND covered.family = ?2 AND covered.last_observed >= CAST(?5 AS INTEGER))
`

type StartProbeAddressParams struct {
	ExecutorID string
	Family     int64
	Address    string
	Via        string
	At         int64
}

// Starts a new run, unless a run already covers this time, so an older
// observation never opens a run after a newer one.
func (q *Queries) StartProbeAddress(ctx context.Context, arg StartProbeAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startProbeAddress,
		arg.ExecutorID,
		arg.Family,
		arg.Address,
		arg.Via,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchProbeConnected = `-- name: TouchProbeConnected :execrows
UPDATE probe_status SET
    total_uptime = total_uptime + (CAST(?1 AS INTEGER) - last_connected),
    last_connected = CAST(?1 AS INTEGER)
WHERE executor_id = ?2 AND connected = 1 AND CAST(?1 AS INTEGER) >= last_connected
`

type TouchProbeConnectedParams struct {
	Now        int64
	ExecutorID string
}

func (q *Queries) TouchProbeConnected(ctx context.Context, arg TouchProbeConnectedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchProbeConnected, arg.Now, arg.ExecutorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
