// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement.sql

package database

import (
	"context"
	"database/sql"

	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const getPaymentReceipt = `-- name: GetPaymentReceipt :one
SELECT tx_digest, event_seq, nonce, disposition, amount, coin_type, receiver, checkpoint, observed_at, detail FROM payment_receipts
WHERE tx_digest = ? AND event_seq = ?
`

type GetPaymentReceiptParams struct {
	TxDigest string
	EventSeq int64
}

func (q *Queries) GetPaymentReceipt(ctx context.Context, arg GetPaymentReceiptParams) (PaymentReceipt, error) {
	row := q.db.QueryRowContext(ctx, getPaymentReceipt, arg.TxDigest, arg.EventSeq)
	var i PaymentReceipt
	err := row.Scan(
		&i.TxDigest,
		&i.EventSeq,
		&i.Nonce,
		&i.Disposition,
		&i.Amount,
		&i.CoinType,
		&i.Receiver,
		&i.Checkpoint,
		&i.ObservedAt,
		&i.Detail,
	)
	return i, err
}

const insertPaymentReceipt = `-- name: InsertPaymentReceipt :exec
INSERT INTO payment_receipts (tx_digest, event_seq, nonce, disposition, amount, coin_type, receiver, checkpoint, observed_at, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaymentReceiptParams struct {
	TxDigest    string
	EventSeq    int64
	Nonce       string
	Disposition string
	Amount      string
	CoinType    string
	Receiver    string
	Checkpoint  sql.NullInt64
	ObservedAt  models.UTCTime
	Detail      string
}

func (q *Queries) InsertPaymentReceipt(ctx context.Context, arg InsertPaymentReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertPaymentReceipt,
		arg.TxDigest,
		arg.EventSeq,
		arg.Nonce,
		arg.Disposition,
		arg.Amount,
		arg.CoinType,
		arg.Receiver,
		arg.Checkpoint,
		arg.ObservedAt,
		arg.Detail,
	)
	return err
}

const listPaymentReceiptsByNonce = `-- name: ListPaymentReceiptsByNonce :many
SELECT tx_digest, event_seq, nonce, disposition, amount, coin_type, receiver, checkpoint, observed_at, detail FROM payment_receipts
WHERE nonce = ?
ORDER BY observed_at, tx_digest, event_seq
`

func (q *Queries) ListPaymentReceiptsByNonce(ctx context.Context, nonce string) ([]PaymentReceipt, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentReceiptsByNonce, nonce)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentReceipt
	for rows.Next() {
		var i PaymentReceipt
		if err := rows.Scan(
			&i.TxDigest,
			&i.EventSeq,
			&i.Nonce,
			&i.Disposition,
			&i.Amount,
			&i.CoinType,
			&i.Receiver,
			&i.Checkpoint,
			&i.ObservedAt,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionPaid = `-- name: MarkTransactionPaid :execrows
UPDATE transactions
SET status = ?1
WHERE id = ?2 AND status = ?3
`

type MarkTransactionPaidParams struct {
	Paid        int64
	ID          string
	Outstanding int64
}

func (q *Queries) MarkTransactionPaid(ctx context.Context, arg MarkTransactionPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTransactionPaid, arg.Paid, arg.ID, arg.Outstanding)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
