// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terminal_cleanup.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTerminalCleanup = `-- name: CreateTerminalCleanup :exec
INSERT INTO debuglet_terminal_cleanup (debuglet_id) VALUES (?)
`

func (q *Queries) CreateTerminalCleanup(ctx context.Context, debugletID int64) error {
	_, err := q.db.ExecContext(ctx, createTerminalCleanup, debugletID)
	return err
}

const deleteTerminalCleanup = `-- name: DeleteTerminalCleanup :exec
DELETE FROM debuglet_terminal_cleanup WHERE debuglet_id = ?
`

func (q *Queries) DeleteTerminalCleanup(ctx context.Context, debugletID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTerminalCleanup, debugletID)
	return err
}

const getTerminalCleanup = `-- name: GetTerminalCleanup :one
SELECT d.id, d.uuid, d.start_time, d.end_time, d.usage, d.ceil_bw, d.executor_id, d.addresses, d.state, d.error, d.transaction_id, d.order_id, d.dispatcher_incarnation, d.session_id FROM debuglets d
JOIN debuglet_terminal_cleanup c ON c.debuglet_id = d.id
WHERE d.uuid = ?
`

func (q *Queries) GetTerminalCleanup(ctx context.Context, argUuid uuid.UUID) (Debuglet, error) {
	row := q.db.QueryRowContext(ctx, getTerminalCleanup, argUuid)
	var i Debuglet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.StartTime,
		&i.EndTime,
		&i.Usage,
		&i.CeilBw,
		&i.ExecutorID,
		&i.Addresses,
		&i.State,
		&i.Error,
		&i.TransactionID,
		&i.OrderID,
		&i.DispatcherIncarnation,
		&i.SessionID,
	)
	return i, err
}

const listTerminalCleanup = `-- name: ListTerminalCleanup :many
SELECT d.id, d.uuid, d.start_time, d.end_time, d.usage, d.ceil_bw, d.executor_id, d.addresses, d.state, d.error, d.transaction_id, d.order_id, d.dispatcher_incarnation, d.session_id FROM debuglets d
JOIN debuglet_terminal_cleanup c ON c.debuglet_id = d.id
ORDER BY d.id LIMIT ?
`

func (q *Queries) ListTerminalCleanup(ctx context.Context, limit int64) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listTerminalCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.CeilBw,
			&i.ExecutorID,
			&i.Addresses,
			&i.State,
			&i.Error,
			&i.TransactionID,
			&i.OrderID,
			&i.DispatcherIncarnation,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
