// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"

	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const addEarnings = `-- name: AddEarnings :exec
UPDATE earnings
SET total_income = total_income + ?1,
    current_balance = current_balance + ?1
WHERE executor_id = ?2 AND currency = ?3
`

type AddEarningsParams struct {
	Amount     int64
	ExecutorID string
	Currency   string
}

func (q *Queries) AddEarnings(ctx context.Context, arg AddEarningsParams) error {
	_, err := q.db.ExecContext(ctx, addEarnings, arg.Amount, arg.ExecutorID, arg.Currency)
	return err
}

const createDebugletOrder = `-- name: CreateDebugletOrder :one
INSERT INTO debuglet_order (transaction_id, order_id, executor_id, price, currency, refund_address, state )
VALUES (?,?,?,?,?,?,?)
RETURNING transaction_id, order_id, executor_id, price, currency, state, refund_address
`

type CreateDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
	RefundAddress string
	State         int64
}

func (q *Queries) CreateDebugletOrder(ctx context.Context, arg CreateDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, createDebugletOrder,
		arg.TransactionID,
		arg.OrderID,
		arg.ExecutorID,
		arg.Price,
		arg.Currency,
		arg.RefundAddress,
		arg.State,
	)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
	)
	return i, err
}

const createEarnings = `-- name: CreateEarnings :one
INSERT INTO earnings (executor_id, currency, sui_wallet_address, total_income, current_balance)
VALUES (?,?,?,0,0)
RETURNING executor_id, currency, total_income, current_balance, sui_wallet_address
`

type CreateEarningsParams struct {
	ExecutorID       string
	Currency         string
	SuiWalletAddress string
}

func (q *Queries) CreateEarnings(ctx context.Context, arg CreateEarningsParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, createEarnings, arg.ExecutorID, arg.Currency, arg.SuiWalletAddress)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
		&i.SuiWalletAddress,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, auth_key, price, currency, method, expires_at, status, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, auth_key, price, method, expires_at, hash, currency, status
`

type CreateTransactionParams struct {
	ID        string
	AuthKey   string
	Price     int64
	Currency  string
	Method    string
	ExpiresAt models.UTCTime
	Status    int64
	Hash      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.AuthKey,
		arg.Price,
		arg.Currency,
		arg.Method,
		arg.ExpiresAt,
		arg.Status,
		arg.Hash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
	)
	return i, err
}

const getDebugletOrder = `-- name: GetDebugletOrder :one
/*

DEBUGLET_ORDER

*/

SELECT transaction_id, order_id, executor_id, price, currency, state, refund_address FROM debuglet_order
WHERE transaction_id = ? AND order_id = ?
`

type GetDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
}

func (q *Queries) GetDebugletOrder(ctx context.Context, arg GetDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, getDebugletOrder, arg.TransactionID, arg.OrderID)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
	)
	return i, err
}

const getEarnings = `-- name: GetEarnings :many
/*

EARNINGS

*/

SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
`

func (q *Queries) GetEarnings(ctx context.Context) ([]Earning, error) {
	rows, err := q.db.QueryContext(ctx, getEarnings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Currency,
			&i.TotalIncome,
			&i.CurrentBalance,
			&i.SuiWalletAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsIn = `-- name: GetEarningsIn :one
SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
WHERE executor_id = ? AND currency = ?
`

type GetEarningsInParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) GetEarningsIn(ctx context.Context, arg GetEarningsInParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, getEarningsIn, arg.ExecutorID, arg.Currency)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
		&i.SuiWalletAddress,
	)
	return i, err
}

const getEarningsOf = `-- name: GetEarningsOf :many
SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
WHERE executor_id = ?
`

func (q *Queries) GetEarningsOf(ctx context.Context, executorID string) ([]Earning, error) {
	rows, err := q.db.QueryContext(ctx, getEarningsOf, executorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Currency,
			&i.TotalIncome,
			&i.CurrentBalance,
			&i.SuiWalletAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, auth_key, price, method, expires_at, hash, currency, status FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
	)
	return i, err
}

const getTransactionOrders = `-- name: GetTransactionOrders :many
SELECT transaction_id, order_id, executor_id, price, currency, state, refund_address FROM debuglet_order
WHERE transaction_id = ?
`

func (q *Queries) GetTransactionOrders(ctx context.Context, transactionID string) ([]DebugletOrder, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionOrders, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletOrder
	for rows.Next() {
		var i DebugletOrder
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.ExecutorID,
			&i.Price,
			&i.Currency,
			&i.State,
			&i.RefundAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionState = `-- name: GetTransactionState :one
SELECT "key", value FROM transaction_states
WHERE key = ?
`

func (q *Queries) GetTransactionState(ctx context.Context, key string) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, getTransactionState, key)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const setRefundAddress = `-- name: SetRefundAddress :exec
UPDATE debuglet_order
SET refund_address = ?
WHERE transaction_id = ? AND order_id = ?
`

type SetRefundAddressParams struct {
	RefundAddress string
	TransactionID string
	OrderID       int64
}

func (q *Queries) SetRefundAddress(ctx context.Context, arg SetRefundAddressParams) error {
	_, err := q.db.ExecContext(ctx, setRefundAddress, arg.RefundAddress, arg.TransactionID, arg.OrderID)
	return err
}

const settleEarning = `-- name: SettleEarning :exec
UPDATE earnings 
SET current_balance = 0
WHERE executor_id = ? AND currency = ?
`

type SettleEarningParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) SettleEarning(ctx context.Context, arg SettleEarningParams) error {
	_, err := q.db.ExecContext(ctx, settleEarning, arg.ExecutorID, arg.Currency)
	return err
}

const updateDebugletOrderState = `-- name: UpdateDebugletOrderState :one
UPDATE debuglet_order
SET state = ? 
WHERE transaction_id = ? AND order_id = ?
RETURNING transaction_id, order_id, executor_id, price, currency, state, refund_address
`

type UpdateDebugletOrderStateParams struct {
	State         int64
	TransactionID string
	OrderID       int64
}

func (q *Queries) UpdateDebugletOrderState(ctx context.Context, arg UpdateDebugletOrderStateParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, updateDebugletOrderState, arg.State, arg.TransactionID, arg.OrderID)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
INSERT OR REPLACE INTO transaction_states (key, value)
VALUES (?, ?)
RETURNING "key", value
`

type UpdateTransactionStateParams struct {
	Key   string
	Value string
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionState, arg.Key, arg.Value)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = ?
WHERE id = ?
`

type UpdateTransactionStatusParams struct {
	Status int64
	ID     string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionStatus, arg.Status, arg.ID)
	return err
}
