// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/netsec-ethz/debuglet/internal/dispatcher/models"
)

const addEarnings = `-- name: AddEarnings :exec
UPDATE earnings
SET total_income = total_income + ?1,
    current_balance = current_balance + ?1
WHERE executor_id = ?2 AND currency = ?3
`

type AddEarningsParams struct {
	Amount     int64
	ExecutorID string
	Currency   string
}

func (q *Queries) AddEarnings(ctx context.Context, arg AddEarningsParams) error {
	_, err := q.db.ExecContext(ctx, addEarnings, arg.Amount, arg.ExecutorID, arg.Currency)
	return err
}

const claimDebugletOrder = `-- name: ClaimDebugletOrder :execrows
UPDATE debuglet_order
SET debuglet_id = ?1
WHERE transaction_id = ?2 AND order_id = ?3
  AND debuglet_id IS NULL AND state = ?4
  AND EXISTS (
    SELECT 1 FROM transactions
    WHERE transactions.id = debuglet_order.transaction_id
      AND transactions.status = ?5
  )
`

type ClaimDebugletOrderParams struct {
	DebugletID       sql.NullInt64
	TransactionID    string
	OrderID          int64
	OutstandingState int64
	PaidStatus       int64
}

func (q *Queries) ClaimDebugletOrder(ctx context.Context, arg ClaimDebugletOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimDebugletOrder,
		arg.DebugletID,
		arg.TransactionID,
		arg.OrderID,
		arg.OutstandingState,
		arg.PaidStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDebugletOrder = `-- name: CreateDebugletOrder :one
INSERT INTO debuglet_order (transaction_id, order_id, executor_id, price, currency, refund_address, state )
VALUES (?,?,?,?,?,?,?)
RETURNING transaction_id, order_id, executor_id, price, currency, state, refund_address, debuglet_id
`

type CreateDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
	ExecutorID    string
	Price         int64
	Currency      string
	RefundAddress string
	State         int64
}

func (q *Queries) CreateDebugletOrder(ctx context.Context, arg CreateDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, createDebugletOrder,
		arg.TransactionID,
		arg.OrderID,
		arg.ExecutorID,
		arg.Price,
		arg.Currency,
		arg.RefundAddress,
		arg.State,
	)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
		&i.DebugletID,
	)
	return i, err
}

const createEarnings = `-- name: CreateEarnings :one
INSERT INTO earnings (executor_id, currency, sui_wallet_address, total_income, current_balance)
VALUES (?,?,?,0,0)
RETURNING executor_id, currency, total_income, current_balance, sui_wallet_address
`

type CreateEarningsParams struct {
	ExecutorID       string
	Currency         string
	SuiWalletAddress string
}

func (q *Queries) CreateEarnings(ctx context.Context, arg CreateEarningsParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, createEarnings, arg.ExecutorID, arg.Currency, arg.SuiWalletAddress)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
		&i.SuiWalletAddress,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, auth_key, price, currency, method, expires_at, status, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, auth_key, price, method, expires_at, hash, currency, status, pricing_rule
`

type CreateTransactionParams struct {
	ID        string
	AuthKey   string
	Price     int64
	Currency  string
	Method    string
	ExpiresAt models.UTCTime
	Status    int64
	Hash      string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.AuthKey,
		arg.Price,
		arg.Currency,
		arg.Method,
		arg.ExpiresAt,
		arg.Status,
		arg.Hash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
		&i.PricingRule,
	)
	return i, err
}

const getAdmittedRuns = `-- name: GetAdmittedRuns :many
SELECT o.order_id, d.uuid FROM debuglet_order o
JOIN debuglets d ON d.id = o.debuglet_id
WHERE o.transaction_id = ?
ORDER BY o.order_id
`

type GetAdmittedRunsRow struct {
	OrderID int64
	Uuid    uuid.UUID
}

func (q *Queries) GetAdmittedRuns(ctx context.Context, transactionID string) ([]GetAdmittedRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdmittedRuns, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdmittedRunsRow
	for rows.Next() {
		var i GetAdmittedRunsRow
		if err := rows.Scan(&i.OrderID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebugletOrder = `-- name: GetDebugletOrder :one
/*

DEBUGLET_ORDER

*/

SELECT transaction_id, order_id, executor_id, price, currency, state, refund_address, debuglet_id FROM debuglet_order
WHERE transaction_id = ? AND order_id = ?
`

type GetDebugletOrderParams struct {
	TransactionID string
	OrderID       int64
}

func (q *Queries) GetDebugletOrder(ctx context.Context, arg GetDebugletOrderParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, getDebugletOrder, arg.TransactionID, arg.OrderID)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
		&i.DebugletID,
	)
	return i, err
}

const getEarnings = `-- name: GetEarnings :many
/*

EARNINGS

*/

SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
`

func (q *Queries) GetEarnings(ctx context.Context) ([]Earning, error) {
	rows, err := q.db.QueryContext(ctx, getEarnings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Currency,
			&i.TotalIncome,
			&i.CurrentBalance,
			&i.SuiWalletAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarningsIn = `-- name: GetEarningsIn :one
SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
WHERE executor_id = ? AND currency = ?
`

type GetEarningsInParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) GetEarningsIn(ctx context.Context, arg GetEarningsInParams) (Earning, error) {
	row := q.db.QueryRowContext(ctx, getEarningsIn, arg.ExecutorID, arg.Currency)
	var i Earning
	err := row.Scan(
		&i.ExecutorID,
		&i.Currency,
		&i.TotalIncome,
		&i.CurrentBalance,
		&i.SuiWalletAddress,
	)
	return i, err
}

const getEarningsOf = `-- name: GetEarningsOf :many
SELECT executor_id, currency, total_income, current_balance, sui_wallet_address FROM earnings
WHERE executor_id = ?
`

func (q *Queries) GetEarningsOf(ctx context.Context, executorID string) ([]Earning, error) {
	rows, err := q.db.QueryContext(ctx, getEarningsOf, executorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earning
	for rows.Next() {
		var i Earning
		if err := rows.Scan(
			&i.ExecutorID,
			&i.Currency,
			&i.TotalIncome,
			&i.CurrentBalance,
			&i.SuiWalletAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderSettlement = `-- name: GetOrderSettlement :one
SELECT transaction_id, order_id, kind, amount, currency, executor_id, debuglet_id, recorded_at FROM order_settlements
WHERE transaction_id = ? AND order_id = ?
`

type GetOrderSettlementParams struct {
	TransactionID string
	OrderID       int64
}

func (q *Queries) GetOrderSettlement(ctx context.Context, arg GetOrderSettlementParams) (OrderSettlement, error) {
	row := q.db.QueryRowContext(ctx, getOrderSettlement, arg.TransactionID, arg.OrderID)
	var i OrderSettlement
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.Kind,
		&i.Amount,
		&i.Currency,
		&i.ExecutorID,
		&i.DebugletID,
		&i.RecordedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, auth_key, price, method, expires_at, hash, currency, status, pricing_rule FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AuthKey,
		&i.Price,
		&i.Method,
		&i.ExpiresAt,
		&i.Hash,
		&i.Currency,
		&i.Status,
		&i.PricingRule,
	)
	return i, err
}

const getTransactionOrders = `-- name: GetTransactionOrders :many
SELECT transaction_id, order_id, executor_id, price, currency, state, refund_address, debuglet_id FROM debuglet_order
WHERE transaction_id = ?
`

func (q *Queries) GetTransactionOrders(ctx context.Context, transactionID string) ([]DebugletOrder, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionOrders, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugletOrder
	for rows.Next() {
		var i DebugletOrder
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.ExecutorID,
			&i.Price,
			&i.Currency,
			&i.State,
			&i.RefundAddress,
			&i.DebugletID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionState = `-- name: GetTransactionState :one
SELECT "key", value FROM transaction_states
WHERE key = ?
`

func (q *Queries) GetTransactionState(ctx context.Context, key string) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, getTransactionState, key)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const insertOrderSettlement = `-- name: InsertOrderSettlement :exec
INSERT INTO order_settlements (transaction_id, order_id, kind, amount, currency, executor_id, debuglet_id, recorded_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOrderSettlementParams struct {
	TransactionID string
	OrderID       int64
	Kind          string
	Amount        int64
	Currency      string
	ExecutorID    string
	DebugletID    sql.NullInt64
	RecordedAt    models.UTCTime
}

func (q *Queries) InsertOrderSettlement(ctx context.Context, arg InsertOrderSettlementParams) error {
	_, err := q.db.ExecContext(ctx, insertOrderSettlement,
		arg.TransactionID,
		arg.OrderID,
		arg.Kind,
		arg.Amount,
		arg.Currency,
		arg.ExecutorID,
		arg.DebugletID,
		arg.RecordedAt,
	)
	return err
}

const listPendingSettlements = `-- name: ListPendingSettlements :many
SELECT d.id, d.uuid, d.start_time, d.end_time, d.usage, d.ceil_bw, d.executor_id, d.addresses, d.state, d.error, d.transaction_id, d.order_id, d.dispatcher_incarnation, d.session_id, e.exit_code, o.currency FROM debuglet_order o
JOIN debuglets d ON d.id = o.debuglet_id
  AND d.transaction_id = o.transaction_id AND d.order_id = o.order_id
JOIN measurement_execution e ON e.debuglet_id = d.id
WHERE o.state = ?1 AND d.state = ?2
  AND e.exit_code IS NOT NULL AND (e.exit_code = 0 OR o.currency = 'TEST')
  AND d.id > ?3
ORDER BY d.id
LIMIT ?4
`

type ListPendingSettlementsParams struct {
	OutstandingState int64
	ExitedState      models.DebugletRunState
	AfterID          int64
	RowLimit         int64
}

type ListPendingSettlementsRow struct {
	Debuglet Debuglet
	ExitCode sql.NullInt64
	Currency string
}

// Only wholly local settlements: credits of any currency and TEST refunds.
func (q *Queries) ListPendingSettlements(ctx context.Context, arg ListPendingSettlementsParams) ([]ListPendingSettlementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSettlements,
		arg.OutstandingState,
		arg.ExitedState,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSettlementsRow
	for rows.Next() {
		var i ListPendingSettlementsRow
		if err := rows.Scan(
			&i.Debuglet.ID,
			&i.Debuglet.Uuid,
			&i.Debuglet.StartTime,
			&i.Debuglet.EndTime,
			&i.Debuglet.Usage,
			&i.Debuglet.CeilBw,
			&i.Debuglet.ExecutorID,
			&i.Debuglet.Addresses,
			&i.Debuglet.State,
			&i.Debuglet.Error,
			&i.Debuglet.TransactionID,
			&i.Debuglet.OrderID,
			&i.Debuglet.DispatcherIncarnation,
			&i.Debuglet.SessionID,
			&i.ExitCode,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundUnadmittedTransaction = `-- name: RefundUnadmittedTransaction :execrows
UPDATE transactions
SET status = ?1
WHERE id = ?2 AND status = ?3
  AND NOT EXISTS (
    SELECT 1 FROM debuglet_order
    WHERE debuglet_order.transaction_id = transactions.id AND debuglet_id IS NOT NULL
  )
`

type RefundUnadmittedTransactionParams struct {
	RefundedStatus int64
	TransactionID  string
	PaidStatus     int64
}

func (q *Queries) RefundUnadmittedTransaction(ctx context.Context, arg RefundUnadmittedTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refundUnadmittedTransaction, arg.RefundedStatus, arg.TransactionID, arg.PaidStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRefundAddress = `-- name: SetRefundAddress :exec
UPDATE debuglet_order
SET refund_address = ?
WHERE transaction_id = ? AND order_id = ?
`

type SetRefundAddressParams struct {
	RefundAddress string
	TransactionID string
	OrderID       int64
}

func (q *Queries) SetRefundAddress(ctx context.Context, arg SetRefundAddressParams) error {
	_, err := q.db.ExecContext(ctx, setRefundAddress, arg.RefundAddress, arg.TransactionID, arg.OrderID)
	return err
}

const setTransactionPricingRule = `-- name: SetTransactionPricingRule :exec
UPDATE transactions
SET pricing_rule = ?
WHERE id = ?
`

type SetTransactionPricingRuleParams struct {
	PricingRule string
	ID          string
}

func (q *Queries) SetTransactionPricingRule(ctx context.Context, arg SetTransactionPricingRuleParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionPricingRule, arg.PricingRule, arg.ID)
	return err
}

const settleEarning = `-- name: SettleEarning :exec
UPDATE earnings 
SET current_balance = 0
WHERE executor_id = ? AND currency = ?
`

type SettleEarningParams struct {
	ExecutorID string
	Currency   string
}

func (q *Queries) SettleEarning(ctx context.Context, arg SettleEarningParams) error {
	_, err := q.db.ExecContext(ctx, settleEarning, arg.ExecutorID, arg.Currency)
	return err
}

const transitionDebugletOrder = `-- name: TransitionDebugletOrder :execrows
UPDATE debuglet_order
SET state = ?1
WHERE transaction_id = ?2 AND order_id = ?3
  AND state = ?4
`

type TransitionDebugletOrderParams struct {
	ToState       int64
	TransactionID string
	OrderID       int64
	FromState     int64
}

func (q *Queries) TransitionDebugletOrder(ctx context.Context, arg TransitionDebugletOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionDebugletOrder,
		arg.ToState,
		arg.TransactionID,
		arg.OrderID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDebugletOrderState = `-- name: UpdateDebugletOrderState :one
UPDATE debuglet_order
SET state = ? 
WHERE transaction_id = ? AND order_id = ?
RETURNING transaction_id, order_id, executor_id, price, currency, state, refund_address, debuglet_id
`

type UpdateDebugletOrderStateParams struct {
	State         int64
	TransactionID string
	OrderID       int64
}

func (q *Queries) UpdateDebugletOrderState(ctx context.Context, arg UpdateDebugletOrderStateParams) (DebugletOrder, error) {
	row := q.db.QueryRowContext(ctx, updateDebugletOrderState, arg.State, arg.TransactionID, arg.OrderID)
	var i DebugletOrder
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.ExecutorID,
		&i.Price,
		&i.Currency,
		&i.State,
		&i.RefundAddress,
		&i.DebugletID,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
INSERT OR REPLACE INTO transaction_states (key, value)
VALUES (?, ?)
RETURNING "key", value
`

type UpdateTransactionStateParams struct {
	Key   string
	Value string
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (TransactionState, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionState, arg.Key, arg.Value)
	var i TransactionState
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = ?
WHERE id = ?
`

type UpdateTransactionStatusParams struct {
	Status int64
	ID     string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionStatus, arg.Status, arg.ID)
	return err
}
