// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (uuid, name)
VALUES (?, ?)
RETURNING id, uuid, name
`

type CreateUserParams struct {
	Uuid uuid.UUID
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Uuid, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Uuid, &i.Name)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, name
FROM users
WHERE uuid=?
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(&i.ID, &i.Uuid, &i.Name)
	return i, err
}

const insertDebugletUser = `-- name: InsertDebugletUser :exec
INSERT INTO debuglet_users (debuglet_id, user_id)
VALUES (
    (SELECT id FROM debuglets WHERE debuglets.uuid=?1),
    (SELECT id FROM users WHERE users.uuid=?2)
)
`

type InsertDebugletUserParams struct {
	DebUuid  uuid.UUID
	UserUuid uuid.UUID
}

func (q *Queries) InsertDebugletUser(ctx context.Context, arg InsertDebugletUserParams) error {
	_, err := q.db.ExecContext(ctx, insertDebugletUser, arg.DebUuid, arg.UserUuid)
	return err
}

const listDebugletsByUserUUID = `-- name: ListDebugletsByUserUUID :many
SELECT id, uuid, start_time, end_time, usage, ceil_bw, executor_id, addresses, state, error
FROM debuglets
WHERE id IN (
    SELECT debuglet_id
    FROM debuglet_users
    INNER JOIN users ON debuglet_users.user_id = users.id
    WHERE users.uuid=?
)
LIMIT ? OFFSET ?
`

type ListDebugletsByUserUUIDParams struct {
	Uuid   uuid.UUID
	Limit  int64
	Offset int64
}

func (q *Queries) ListDebugletsByUserUUID(ctx context.Context, arg ListDebugletsByUserUUIDParams) ([]Debuglet, error) {
	rows, err := q.db.QueryContext(ctx, listDebugletsByUserUUID, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debuglet
	for rows.Next() {
		var i Debuglet
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.StartTime,
			&i.EndTime,
			&i.Usage,
			&i.CeilBw,
			&i.ExecutorID,
			&i.Addresses,
			&i.State,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUUIDs = `-- name: ListUserUUIDs :many
SELECT uuid
FROM users
`

func (q *Queries) ListUserUUIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listUserUUIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
