//go:build linux

// Copyright 2025 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package bpf provides an eBPF-based IPv4 IPID tagger for Linux.
//
// The eBPF program (tagger.c) is compiled at build time into a Go byte-slice
// via bpf2go and loaded at runtime via cilium/ebpf. It attaches to the TC
// egress hook on a named network interface.
//
// Key architecture:
//   - The Go-side KeyManager periodically updates a BPF hash map with the
//     current per-measurement authentication key (ak).
//   - The eBPF program reads ak from the map, runs SipHash-2-4 over the packet,
//     and writes the 16-bit result into the IPv4 IPID field.
//   - The Linux kernel's BPF_F_RECOMPUTE_CSUM flag causes the checksum to be
//     updated in-place, so no userspace checksum fix is needed.
//
// # Performance comparison
//
// Use the benchmark in bpf_linux_test.go to compare eBPF vs the pure-Go
// tagger (pkg/tagger) at different packet rates.
package bpf

import (
	"encoding/binary"
	"fmt"
	"hash/fnv"
	"net"
	"os"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"

	"debuglet/pkg/tesla"
)

// akEntry mirrors the struct ak_entry in tagger.c.
// The 32-byte HMAC key is split into two 64-bit SipHash key words.
type akEntry struct {
	K0 uint64
	K1 uint64
}

// akFromKey converts a 32-byte TESLA authentication key to a BPF ak_entry.
func akFromKey(ak []byte) akEntry {
	if len(ak) < 16 {
		panic("ak must be at least 16 bytes")
	}
	return akEntry{
		K0: binary.LittleEndian.Uint64(ak[0:8]),
		K1: binary.LittleEndian.Uint64(ak[8:16]),
	}
}

// BPFObjects holds the loaded eBPF objects (maps + programs).
// Generated by bpf2go — kept as a manual struct here for transparency.
type BPFObjects struct {
	AkMap       *ebpf.Map     `ebpf:"ak_map"`
	DebugletTag *ebpf.Program `ebpf:"debuglet_tag"`
}

// BPFTagger loads, attaches, and manages the eBPF packet tagger.
// It implements pkg/tagger.TaggerInterface (eBPF side) and exposes a
// KeyManager for periodic key updates.
type BPFTagger struct {
	objs      BPFObjects
	qdisc     link.Link
	iface     *net.Interface
	schedule  *tesla.KeySchedule
	measureID []byte
	stopCh    chan struct{}
}

// NewBPFTagger loads the compiled eBPF object, attaches the TC egress program
// to iface, and starts the key-update goroutine.
//
// The caller must call Close() when done to detach the program and release BPF
// resources.
func NewBPFTagger(ifaceName string, schedule *tesla.KeySchedule, measurementID []byte) (*BPFTagger, error) {
	// Remove memlock limits (required for eBPF map allocation on older kernels).
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("bpf: remove memlock: %w", err)
	}

	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return nil, fmt.Errorf("bpf: interface %q not found: %w", ifaceName, err)
	}

	// Load pre-compiled eBPF objects from the embedded byte slice.
	// In a full build this would use bpf2go-generated loadTaggerObjects().
	// Here we load the .o file from disk for development flexibility.
	objPath := os.Getenv("DEBUGLET_BPF_OBJ")
	if objPath == "" {
		// Try local path first for development
		if _, err := os.Stat("internal/executor/bpf/c/tagger.o"); err == nil {
			objPath = "internal/executor/bpf/c/tagger.o"
		} else {
			objPath = "/etc/debuglet/bpf/tagger.o"
		}
	}

	spec, err := ebpf.LoadCollectionSpec(objPath)
	if err != nil {
		return nil, fmt.Errorf("bpf: load collection spec from %q: %w", objPath, err)
	}

	var objs BPFObjects
	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		return nil, fmt.Errorf("bpf: load and assign objects: %w", err)
	}

	fmt.Printf("bpf: attempting to attach TCX tagger to %s (index %d)\n", ifaceName, iface.Index)
	// Attach to TC egress using TCX.
	l, err := link.AttachTCX(link.TCXOptions{
		Interface: iface.Index,
		Program:   objs.DebugletTag,
		Attach:    ebpf.AttachTCXEgress,
	})
	if err != nil {
		objs.AkMap.Close()
		objs.DebugletTag.Close()
		fmt.Printf("bpf: attach TCX to %s failed: %v\n", ifaceName, err)
		return nil, fmt.Errorf("bpf: attach TCX: %w", err)
	}

	fmt.Printf("bpf: successfully attached tagger to %s via TCX\n", ifaceName)

	mid := make([]byte, len(measurementID))
	copy(mid, measurementID)

	bt := &BPFTagger{
		objs:      objs,
		qdisc:     l,
		iface:     iface,
		schedule:  schedule,
		measureID: mid,
		stopCh:    make(chan struct{}),
	}

	// Push initial key.
	if err := bt.updateKey(); err != nil {
		bt.Close()
		return nil, fmt.Errorf("bpf: initial key update: %w", err)
	}

	// Start background key refresh.
	go bt.keyRefreshLoop()

	return bt, nil
}

// updateKey derives the current ak and writes it to the BPF map at the slot
// identified by the measurement ID hash.
func (bt *BPFTagger) updateKey() error {
	k := bt.schedule.CurrentKey(time.Now())
	ak, err := tesla.DeriveAK(k, bt.measureID)
	if err != nil {
		return fmt.Errorf("DeriveAK: %w", err)
	}
	entry := akFromKey(ak)
	key := bt.MapKey()
	return bt.objs.AkMap.Put(&key, &entry)
}

func (bt *BPFTagger) MapKey() uint32 {
	h := fnv.New32a()
	h.Write(bt.measureID)
	return h.Sum32()
}

// keyRefreshLoop updates the BPF map at the start of each new TESLA epoch.
func (bt *BPFTagger) keyRefreshLoop() {
	cfg := bt.schedule.Config()
	ticker := time.NewTicker(cfg.Delay / 2)
	defer ticker.Stop()
	for {
		select {
		case <-bt.stopCh:
			return
		case <-ticker.C:
			_ = bt.updateKey() // best-effort; errors are transient
		}
	}
}

// TagPacket is a no-op on the eBPF path because tagging is done in the kernel.
// It satisfies the TaggerInterface so BPFTagger can be used interchangeably
// with the pure-Go Tagger in tests.
func (bt *BPFTagger) TagPacket(pkt []byte) ([]byte, error) {
	// eBPF tagging is transparent — the kernel modifies packets in the egress
	// path before they hit the wire, without involving userspace.
	return pkt, nil
}

// Close detaches the eBPF program and releases all BPF resources.
func (bt *BPFTagger) Close() error {
	close(bt.stopCh)
	if bt.qdisc != nil {
		bt.qdisc.Close()
	}
	if bt.objs.DebugletTag != nil {
		bt.objs.DebugletTag.Close()
	}
	if bt.objs.AkMap != nil {
		bt.objs.AkMap.Close()
	}
	return nil
}

func (bt *BPFTagger) Schedule() *tesla.KeySchedule {
	return bt.schedule
}

func (bt *BPFTagger) SetSocketMark(fd int) error {
	mark := bt.MapKey()
	if err := syscall.SetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SO_MARK, int(mark)); err != nil {
		return fmt.Errorf("setsockopt SO_MARK: %w", err)
	}
	fmt.Printf("bpf: set socket mark to %x\n", mark)
	return nil
}
