"""tools/verify_pcap.py: debuglet-tag-v1 pinned by the shared vectors, and the
verification window.

testdata/tag-vectors-v1.json is generated by tools/tag_vectors.py, an
implementation independent of verify_pcap.py; the Go and kernel tests read the
same file. The window tests pin candidate epochs t and t-1 only, a disclosure
delay of at least two epochs, and no key that may already have been public
when the packet was captured.
"""
import base64
import hashlib
import http.server
import json
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import threading
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
import verify_pcap  # noqa: E402

vp = verify_pcap
VECTORS = json.loads((ROOT / 'testdata' / 'tag-vectors-v1.json').read_text())
SRC = '192.0.2.10'
EXECUTOR = 'exec-vectors'
DELAY = 10
ANCHOR_NS = 1_700_000_000 * 1_000_000_000


def vector(name):
    return next(v for v in VECTORS['vectors'] if v['name'] == name)


class VectorTest(unittest.TestCase):
    def test_generator_reproduces_the_committed_vectors(self):
        result = subprocess.run([sys.executable, str(ROOT / 'tools' / 'tag_vectors.py'), '--check'],
                                capture_output=True, text=True, timeout=120, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_spec_version(self):
        self.assertEqual(VECTORS['spec'], verify_pcap.TAG_SPEC)

    def test_siphash_reference_vectors(self):
        key = bytes.fromhex(VECTORS['siphash_reference']['key_hex'])
        for n, want in enumerate(VECTORS['siphash_reference']['outputs_hex']):
            got = struct.pack('<Q', verify_pcap.siphash24(key, bytes(range(n)))).hex()
            self.assertEqual(got, want, f'{n}-byte message')

    def test_key_derivation(self):
        ak = verify_pcap.hkdf_sha256(bytes.fromhex(VECTORS['k_t_hex']),
                                     VECTORS['measurement_id'].encode())
        self.assertEqual(ak.hex(), VECTORS['ak_hex'])
        keys = [bytes.fromhex(k) for k in VECTORS['chain']['keys_hex']]
        for i, k in enumerate(keys):
            self.assertTrue(verify_pcap.verify_chain(keys[0], k, i))

    def test_every_vector(self):
        ak = bytes.fromhex(VECTORS['ak_hex'])
        for v in VECTORS['vectors']:
            with self.subTest(v['name']):
                data, reason = verify_pcap.tag_input(bytes.fromhex(v['packet_hex']))
                if not v['supported']:
                    self.assertIsNone(data)
                    self.assertEqual(reason, v['unsupported_reason'])
                    self.assertIn(reason, verify_pcap.UNSUPPORTED)
                    continue
                self.assertIsNone(reason)
                self.assertEqual(data.hex(), v['input_hex'])
                self.assertEqual(struct.pack('<Q', verify_pcap.siphash24(ak[:16], data)).hex(),
                                 v['siphash_hex'])
                self.assertEqual(verify_pcap.compute_tag(ak, data), v['tag'])
                tagged = bytes.fromhex(v['tagged_packet_hex'])
                self.assertEqual(verify_pcap.tag_input(tagged)[0], data,
                                 'the tagged packet has the same input')
                self.assertEqual(struct.unpack('>H', tagged[4:6])[0], v['tag'])
                self.assertTrue(tagged[6] & 0x40, 'DF is set')


def pcap(packets):
    """Classic pcap, LINKTYPE_RAW, one packet per (ts_ns, bytes)."""
    out = struct.pack('<IHHiIII', 0xA1B23C4D, 2, 4, 0, 0, 65535, 101)
    for ts_ns, pkt in packets:
        out += struct.pack('<IIII', ts_ns // 1_000_000_000, ts_ns % 1_000_000_000,
                           len(pkt), len(pkt)) + pkt
    return out


class FakeDispatcher(http.server.BaseHTTPRequestHandler):
    tag_spec = VECTORS['spec']

    def log_message(self, *args):
        pass

    def do_GET(self):
        keys = VECTORS['chain']['keys_hex']
        disclosed = 2
        routes = {
            f'/executors/by-ip?ip={SRC}': {'executor_id': EXECUTOR,
                                          'debuglet_ids': [VECTORS['measurement_id']]},
            f'/executors/{EXECUTOR}/tesla': {
                'anchor_key': base64.b64encode(bytes.fromhex(keys[0])).decode(),
                'anchor_timestamp_ns': ANCHOR_NS, 'epoch_seconds': DELAY,
                'delay_sec': DELAY, 'disclosure_delay_epochs': 2,
                'disclosed_epoch': disclosed,
                'disclosed_key': base64.b64encode(bytes.fromhex(keys[disclosed])).decode()},
            '/executors': [{'id': EXECUTOR, 'capabilities': {'tagging': {
                'ipv4': 'ebpf', 'ipv6': 'none', 'scion': 'none', 'tag_spec': self.tag_spec}}}],
        }
        body = routes.get(self.path)
        if body is None:
            self.send_response(404)
            self.end_headers()
            return
        data = json.dumps(body).encode()
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(data)))
        self.end_headers()
        self.wfile.write(data)


class CaptureReportTest(unittest.TestCase):
    def run_verifier(self, names, tag_spec=VECTORS['spec']):
        handler = type('Handler', (FakeDispatcher,), {'tag_spec': tag_spec})
        server = http.server.ThreadingHTTPServer(('127.0.0.1', 0), handler)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        self.addCleanup(server.server_close)
        self.addCleanup(server.shutdown)
        ts = ANCHOR_NS + int(1.5 * DELAY * 1_000_000_000)  # epoch 1
        packets = []
        for name in names:
            v = vector(name)
            packets.append((ts, bytes.fromhex(v.get('tagged_packet_hex') or v['packet_hex'])))
        with tempfile.NamedTemporaryFile(suffix='.pcap', delete=False) as f:
            f.write(pcap(packets))
        self.addCleanup(Path(f.name).unlink, missing_ok=True)
        return subprocess.run(
            [sys.executable, str(ROOT / 'tools' / 'verify_pcap.py'), '--pcap', f.name,
             '--server', f'http://127.0.0.1:{server.server_address[1]}'],
            capture_output=True, text=True, timeout=120, check=False)

    def test_reports_spec_and_unsupported_reasons_per_packet(self):
        result = self.run_verifier(['udp_base', 'tcp_total_1500', 'unsupported_more_fragments',
                                    'unsupported_ipv6', 'unsupported_short_capture'])
        out = result.stdout
        self.assertEqual(result.returncode, 0, out + result.stderr)
        self.assertIn('Tag specification: debuglet-tag-v1', out)
        self.assertIn('tag_spec=debuglet-tag-v1', out)
        mid = VECTORS['measurement_id']
        self.assertEqual(out.count(f'debuglet-tag-v1: verified {mid} (epoch 1)'), 2, out)
        self.assertIn('unsupported under debuglet-tag-v1 (fragment)', out)
        self.assertIn('unsupported under debuglet-tag-v1 (ipv6)', out)
        self.assertIn('unsupported under debuglet-tag-v1 (too_short)', out)
        self.assertIn('Result (debuglet-tag-v1): 2/5 packets', out)
        self.assertIn('Unsupported: 1 fragment, 1 ipv6, 1 too_short', out)

    def test_altered_packet_is_a_mismatch_not_unsupported(self):
        v = vector('udp_base')
        altered = bytearray.fromhex(v['tagged_packet_hex'])
        altered[40] ^= 1  # inside the 64-byte input
        pkt = verify_pcap.Packet(ANCHOR_NS + int(1.5 * DELAY * 1e9), bytes(altered))
        keys = VECTORS['chain']['keys_hex']
        tesla = {'anchor_key': base64.b64encode(bytes.fromhex(keys[0])).decode(),
                 'anchor_timestamp_ns': ANCHOR_NS, 'epoch_seconds': DELAY,
                 'disclosure_delay_epochs': 2, 'disclosed_epoch': 2,
                 'disclosed_key': base64.b64encode(bytes.fromhex(keys[2])).decode()}
        matched, reason = verify_pcap.verify_packet(pkt, tesla, [VECTORS['measurement_id']])
        self.assertEqual(matched, [])
        self.assertNotIn('unsupported', reason)
        matched, _ = verify_pcap.verify_packet(
            verify_pcap.Packet(pkt.ts_ns, bytes.fromhex(v['tagged_packet_hex'])), tesla,
            [VECTORS['measurement_id']])
        self.assertEqual(matched, [(VECTORS['measurement_id'], 1, 'debuglet-tag-v1')])

    def test_other_reported_spec_is_unsupported(self):
        result = self.run_verifier(['udp_base'], tag_spec='debuglet-tag-v9')
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertIn('unsupported: the executor reports tag spec debuglet-tag-v9', result.stdout)



# The verification window.

SECOND = 1_000_000_000
EPOCH_S = 10
LENGTH = 16
DEBUGLET = "00000000-0000-4000-8000-000000000001"


def window_chain(length=LENGTH):
    """keys[i] is k_i of a backward chain whose tail is a fixed seed."""
    keys = [b""] * (length + 1)
    keys[length] = bytes(range(32))
    for i in range(length - 1, -1, -1):
        keys[i] = hashlib.sha256(keys[i + 1]).digest()
    return keys


KEYS = window_chain()


def window_packet(ts_ns, epoch):
    """An IPv4 packet whose IP-ID carries the tag of epoch's key."""
    ip = bytearray(struct.pack(">BBHHHBBH4s4s", 0x45, 0, 28, 0, 0, 64, 17, 0,
                               bytes([192, 0, 2, 1]), bytes([198, 51, 100, 2])))
    ip += b"payload!"
    ak = vp.hkdf_sha256(KEYS[epoch], DEBUGLET.encode())
    tag = vp.compute_tag(ak, vp.tag_input(bytes(ip))[0])
    struct.pack_into(">H", ip, 4, tag)
    return vp.Packet(ts_ns, bytes(ip))


def schedule(disclosed, d=2, **extra):
    info = {
        "anchor_timestamp_ns": ANCHOR_NS,
        "epoch_seconds": EPOCH_S,
        "delay_sec": EPOCH_S,
        "anchor_key": base64.b64encode(KEYS[0]).decode(),
        "disclosed_epoch": disclosed,
        "disclosed_key": base64.b64encode(KEYS[disclosed]).decode(),
    }
    if d is not None:
        info["disclosure_delay_epochs"] = d
    info.update(extra)
    return info


def at(epoch, offset_s=0.0):
    return ANCHOR_NS + epoch * EPOCH_S * SECOND + int(offset_s * SECOND)


class VerificationWindowTest(unittest.TestCase):
    def verify(self, pkt, info):
        return vp.verify_packet(pkt, info, [DEBUGLET], 0)

    def test_current_and_previous_epoch_verify(self):
        for signed in (5, 4):
            matched, reason = self.verify(window_packet(at(5, 1), signed), schedule(9))
            self.assertEqual(matched, [(DEBUGLET, signed, vp.TAG_SPEC)], reason)

    def test_next_epoch_is_not_a_candidate(self):
        matched, reason = self.verify(window_packet(at(5, 1), 6), schedule(9))
        self.assertEqual(matched, [])
        self.assertIn("produces this tag", reason)

    def test_key_public_at_capture_time_is_refused(self):
        # With d = 2, k_4 may be disclosed from the start of epoch 6, less the
        # dispatcher's skew allowance: a packet late in epoch 5 cannot prove
        # it was tagged before anyone else could compute k_4.
        late = at(6, -vp.DISPATCHER_CLOCK_SKEW_S + 1)
        matched, reason = self.verify(window_packet(late, 4), schedule(9))
        self.assertEqual(matched, [])
        self.assertIn("still secret", reason)
        # The current epoch's key is still secret at that time.
        matched, _ = self.verify(window_packet(late, 5), schedule(9))
        self.assertEqual(matched, [(DEBUGLET, 5, vp.TAG_SPEC)])
        # The capture clock tolerance widens the refused interval.
        early = at(6, -vp.DISPATCHER_CLOCK_SKEW_S - 2)
        self.assertTrue(vp.verify_packet(window_packet(early, 4), schedule(9), [DEBUGLET], 0)[0])
        self.assertFalse(vp.verify_packet(window_packet(early, 4), schedule(9), [DEBUGLET], 3 * SECOND)[0])

    def test_short_or_missing_disclosure_delay_is_refused(self):
        for d in (None, 0, 1):
            matched, reason = self.verify(window_packet(at(5, 1), 5), schedule(9, d=d))
            self.assertEqual(matched, [], d)
            self.assertIn("at least 2", reason)

    def test_undisclosed_key_names_its_due_time(self):
        matched, reason = self.verify(window_packet(at(5, 1), 5), schedule(3))
        self.assertEqual(matched, [])
        self.assertIn(str(at(7)), reason)

    def test_older_dispatcher_names_only_delay_sec(self):
        info = schedule(9)
        del info["epoch_seconds"]
        matched, reason = self.verify(window_packet(at(5, 1), 5), info)
        self.assertEqual(matched, [(DEBUGLET, 5, vp.TAG_SPEC)], reason)


if __name__ == '__main__':
    unittest.main()
