"""Fixture checks for the tracked-source formatting gate, not a CI run."""
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

SCRIPT = Path(__file__).resolve().parents[1] / 'scripts' / 'ci-fmt.sh'
FORMATTED = 'package fixture\n\nfunc Fixture() int {\n\treturn 1\n}\n'
UNFORMATTED = 'package fixture\n\nfunc Fixture()  int {\n        return 1\n}\n'
GENERATED = '// Code generated by a fixture generator; DO NOT EDIT.\n\n'
UNPARSABLE = 'package fixture\n\nfunc Fixture() int {\n'


class FormattingGateTest(unittest.TestCase):
    def checkout(self, tracked, untracked=None):
        """Build a git checkout whose tracked Go files are `tracked`."""
        root = Path(tempfile.mkdtemp(prefix='debuglet-fmt-fixture-'))
        self.addCleanup(shutil.rmtree, root, ignore_errors=True)
        subprocess.run(['git', 'init', '-q', str(root)], check=True)
        (root / 'scripts').mkdir()
        shutil.copyfile(SCRIPT, root / 'scripts' / 'ci-fmt.sh')
        (root / '.gitignore').write_text('/.cache\n')
        for name, content in tracked.items():
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            subprocess.run(['git', '-C', str(root), 'add', '--', name], check=True)
        for name, content in (untracked or {}).items():
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        return root

    def check(self, root):
        return subprocess.run(['bash', 'scripts/ci-fmt.sh'], cwd=root,
                              capture_output=True, timeout=120, check=False)

    def test_formatted_checkout_passes(self):
        root = self.checkout({
            'internal/fixture/fixture.go': FORMATTED,
            'internal/fixture/generated.go': GENERATED + FORMATTED,
        })
        result = self.check(root)
        self.assertEqual(result.returncode, 0, result.stderr.decode())
        self.assertIn(b'2 tracked Go files are formatted', result.stdout)
        self.assertEqual((root / '.cache/ci/gofmt.txt').read_text(), '')

    def test_unformatted_tracked_file_is_reported_and_kept(self):
        root = self.checkout({'internal/fixture/fixture.go': UNFORMATTED})
        result = self.check(root)
        self.assertEqual(result.returncode, 1, result.stdout.decode())
        self.assertIn(b'internal/fixture/fixture.go', result.stderr)
        self.assertIn(b'gofmt', result.stderr)
        # Reporting must not rewrite the checkout.
        self.assertEqual((root / 'internal/fixture/fixture.go').read_text(), UNFORMATTED)
        self.assertEqual((root / '.cache/ci/gofmt.txt').read_text(),
                         'internal/fixture/fixture.go\n')

    def test_generated_files_are_checked_like_handwritten_ones(self):
        root = self.checkout({
            'internal/fixture/fixture.go': FORMATTED,
            'protocol/fixture.pb.go': GENERATED + UNFORMATTED,
        })
        result = self.check(root)
        self.assertEqual(result.returncode, 1, result.stdout.decode())
        self.assertEqual((root / '.cache/ci/gofmt.txt').read_text(), 'protocol/fixture.pb.go\n')

    def test_untracked_and_ignored_paths_are_not_traversed(self):
        root = self.checkout({'internal/fixture/fixture.go': FORMATTED}, untracked={
            '.cache/ci/dist/leftover.go': UNPARSABLE,
            'scratch.go': UNFORMATTED,
        })
        result = self.check(root)
        self.assertEqual(result.returncode, 0, result.stderr.decode())
        self.assertEqual((root / '.cache/ci/gofmt.txt').read_text(), '')

    def test_unparsable_tracked_source_fails(self):
        root = self.checkout({'internal/fixture/fixture.go': UNPARSABLE})
        result = self.check(root)
        self.assertNotEqual(result.returncode, 0, result.stdout.decode())
        self.assertIn(b'internal/fixture/fixture.go', result.stderr)

    def test_missing_git_checkout_fails(self):
        root = self.checkout({'internal/fixture/fixture.go': FORMATTED})
        shutil.rmtree(root / '.git')
        environment = dict(os.environ, GIT_CEILING_DIRECTORIES=str(root.parent))
        result = subprocess.run(['bash', 'scripts/ci-fmt.sh'], cwd=root, env=environment,
                                capture_output=True, timeout=120, check=False)
        self.assertEqual(result.returncode, 1, result.stdout.decode())
        self.assertIn(b'git checkout', result.stderr)


if __name__ == '__main__':
    unittest.main()
